context("Inv-Gaussian (Shifted Wald)")

test_that("rcogmod_invgaussian matches theoretical moments", {
  n_samples <- 15000
  set.seed(123)
  drift_values <- c(0.5, 1, 3, 5)
  boundary_values <- c(0.1, 0.5, 1, 2)
  ndt_values <- c(0, 0.1, 0.3, 0.5) # Keep ndt
  tol_mean <- 0.05
  tol_sd_abs <- 0.05 # Base absolute tolerance
  tol_sd_rel <- 0.15 # Relaxed relative tolerance component to 15%

  for (drift in drift_values) {
    for (boundary in boundary_values) {
      for (ndt in ndt_values) { # Keep ndt
        label <- sprintf("params(drift=%.1f, boundary=%.1f, ndt=%.1f)", drift, boundary, ndt) # Keep ndt
        rts <- rcogmod_invgaussian(n_samples, drift = drift, boundary = boundary, ndt = ndt) # Keep ndt

        if(any(is.na(rts))) {
            warning("NA values generated by rcogmod_invgaussian for ", label)
            next
        }

        theo_mean <- boundary / drift + ndt # Keep ndt
        theo_var <- boundary / (drift^3)
        theo_sd <- sqrt(theo_var)
        emp_mean <- mean(rts)
        emp_sd <- sd(rts)

        expect_equal(emp_mean, theo_mean, tolerance = tol_mean,
                     label = paste(label, "- Mean: Empirical vs Theoretical"))

        # Use a combined absolute and relaxed relative tolerance for SD
        current_tol_sd <- max(tol_sd_abs, theo_sd * tol_sd_rel)
        expect_equal(emp_sd, theo_sd, tolerance = current_tol_sd,
                     label = paste(label, "- SD: Empirical vs Theoretical"))
      }
    }
  }
})

test_that("dcogmod_invgaussian integrates correctly", {
  n_samples_for_range <- 5000
  set.seed(456)
  tol_integration <- 1e-3 # Relaxed tolerance

  drift_values <- c(0.8, 2, 4)
  boundary_values <- c(0.2, 0.7, 1.5)
  ndt_values <- c(0.05, 0.2, 0.4)

  for (drift in drift_values) {
    for (boundary in boundary_values) {
      for (ndt in ndt_values) {
        label <- sprintf("params(drift=%.1f, boundary=%.1f, ndt=%.1f)", drift, boundary, ndt)
        integrand <- function(x_int) {
          dcogmod_invgaussian(x_int, drift = drift, boundary = boundary, ndt = ndt)
        }
        x_sample_range <- rcogmod_invgaussian(n_samples_for_range, drift = drift, boundary = boundary, ndt = ndt)
        # Ensure sample range is valid before calculating quantiles/sd
         if(any(is.na(x_sample_range)) || length(x_sample_range) < 2) {
             warning("Skipping integration test for ", label, " due to invalid sample range.")
             next
         }
        upper_limit <- quantile(x_sample_range, 0.9999, na.rm = TRUE) + 10 * sd(x_sample_range, na.rm = TRUE) # Increased range capture
        if (!is.finite(upper_limit) || upper_limit < ndt + 10) upper_limit <- ndt + 100

        integral_result <- tryCatch(
          stats::integrate(integrand, lower = ndt + .Machine$double.eps, upper = upper_limit,
                           subdivisions = 1000, rel.tol = tol_integration/10, abs.tol = tol_integration/10)$value, # Increased subdivisions, tighter integrate tol
          error = function(e) {
            warning("Integration failed for ", label, ": ", e$message)
            NA
          }
        )

        if (!is.na(integral_result)) {
          expect_equal(integral_result, 1, tolerance = tol_integration, # Use relaxed test tolerance
                       label = paste(label, "- Density integrates to 1"))
        }
      }
    }
  }
})


test_that("pcogmod_invgaussian matches rcogmod_invgaussian and has correct properties", {
  n_samples <- 20000 # More samples for better ECDF accuracy
  set.seed(789)
  tol_cdf <- 0.05 # Tolerance for comparing pcogmod_invgaussian to ECDF

  drift_values <- c(0.8, 3)
  boundary_values <- c(0.3, 1.0)
  ndt_values <- c(0.1, 0.4)

  for (drift in drift_values) {
    for (boundary in boundary_values) {
      for (ndt in ndt_values) {
        label <- sprintf("params(drift=%.1f, boundary=%.1f, ndt=%.1f)", drift, boundary, ndt)

        # Generate samples
        rts <- rcogmod_invgaussian(n_samples, drift = drift, boundary = boundary, ndt = ndt)
        if(any(is.na(rts))) {
            warning("NA values generated by rcogmod_invgaussian for ", label)
            next
        }

        # Calculate empirical CDF
        ecdf_rts <- stats::ecdf(rts)

        # Test points (quantiles from empirical distribution)
        test_quantiles <- quantile(rts, probs = c(0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99), na.rm = TRUE)
        # Add edge cases near ndt
        test_quantiles <- c(ndt + 1e-6, ndt + 0.01, test_quantiles)
        test_quantiles <- unique(test_quantiles[is.finite(test_quantiles) & test_quantiles > ndt])

        # 1. Compare pcogmod_invgaussian with empirical CDF
        p_values <- pcogmod_invgaussian(test_quantiles, drift = drift, boundary = boundary, ndt = ndt)
        ecdf_values <- ecdf_rts(test_quantiles)
        expect_equal(p_values, ecdf_values, tolerance = tol_cdf,
                     label = paste(label, "- CDF: pcogmod_invgaussian vs Empirical"))

        # 2. Check boundary conditions
        expect_equal(pcogmod_invgaussian(ndt, drift = drift, boundary = boundary, ndt = ndt), 0,
                     label = paste(label, "- CDF at ndt is 0"))
        expect_equal(pcogmod_invgaussian(ndt - 1e-6, drift = drift, boundary = boundary, ndt = ndt), 0,
                     label = paste(label, "- CDF below ndt is 0"))
        expect_equal(pcogmod_invgaussian(Inf, drift = drift, boundary = boundary, ndt = ndt), 1,
                     label = paste(label, "- CDF at Inf is 1"))

        # 3. Check lower.tail argument
        p_upper <- pcogmod_invgaussian(test_quantiles, drift = drift, boundary = boundary, ndt = ndt, lower.tail = FALSE)
        expect_equal(p_upper, 1 - p_values, tolerance = 1e-7,
                     label = paste(label, "- CDF lower.tail=FALSE"))

        # 4. Check log.p argument
        p_log <- pcogmod_invgaussian(test_quantiles, drift = drift, boundary = boundary, ndt = ndt, log.p = TRUE)
        # Avoid log(0) issues for comparison by filtering p_values > 0
        valid_idx <- p_values > 0
        expect_equal(p_log[valid_idx], log(p_values[valid_idx]), tolerance = 1e-7,
                     label = paste(label, "- CDF log.p=TRUE"))
        # Check that where p_values is 0, log.p is -Inf
        expect_true(all(p_log[!valid_idx] == -Inf),
                    label = paste(label, "- CDF log.p=TRUE gives -Inf for p=0"))

      }
    }
  }
})



context("Inv-Gaussian (Shifted Wald) - brms")



test_that("Shifted Wald model can recover parameters with brms", {

  skip_if_not_installed("brms")
  skip_if_not_installed("cmdstanr")

  set.seed(555)
  n_obs <- 400

  # True parameters
  true_mu <- 2.5
  true_boundary <- 0.8
  true_ndt <- 0.16
  true_poutlier <- 0.03

  # Simulate data
  df <- data.frame(rt = rcogmod_invgaussian(n_obs, drift = true_mu, boundary = true_boundary,
                                        ndt = true_ndt,
                                        poutlier = true_poutlier))

  # ndt is estimated directly now, on a log link, alongside poutlier
  f <- brms::bf(rt ~ 1, boundary ~ 1, ndt ~ 1, poutlier ~ 1,
                family = cogmod_invgaussian())

  fit <- brms::brm(f,
              data = df,
              prior = cogmod_priors(f, df),
              stanvars = cogmod_invgaussian_stanvars(),
              backend = "cmdstanr",
              algorithm = "pathfinder", # VI
              refresh = 0)

  fixed_effects <- summary(fit)$fixed

  # Intercepts are on their link scales: softplus for mu/boundary, log for ndt
  expect_equal(log1p(exp(fixed_effects["Intercept", "Estimate"])), true_mu,
               tolerance = 0.3, label = "mu recovery")
  expect_equal(log1p(exp(fixed_effects["boundary_Intercept", "Estimate"])), true_boundary,
               tolerance = 0.5, label = "boundary recovery")
  expect_equal(exp(fixed_effects["ndt_Intercept", "Estimate"]), true_ndt,
               tolerance = 0.1, label = "ndt recovery")
})


test_that("Stan cogmod_invgaussian_lpdf matches R dcogmod_invgaussian function", {
  skip_if_not_installed("cmdstanr")

  cogmod_invgaussian_lpdf <- cogmod_invgaussian_lpdf_expose()

  mu_values <- c(1.0, 3.0, 5.0)
  boundary_values <- c(0.3, 0.8, 1.5)
  ndt_values <- c(0, 0.1, 0.25)
  pout_values <- c(0, 0.03, 0.4)
  y_offsets <- c(0.05, 0.2, 1.0)

  for (mu_val in mu_values) {
    for (boundary in boundary_values) {
      for (ndt_val in ndt_values) {
        for (pout in pout_values) {
          for (y_offset in y_offsets) {
            y_val <- ndt_val + y_offset

            label <- sprintf(
              "mu=%.1f, boundary=%.1f, ndt=%.2f, poutlier=%.2f, Y=%.3f",
              mu_val, boundary, ndt_val, pout, y_val)

            r_loglik <- dcogmod_invgaussian(y_val, drift = mu_val, boundary = boundary,
                                        ndt = ndt_val, poutlier = pout,
                                        log = TRUE)
            stan_loglik <- cogmod_invgaussian_lpdf(Y = y_val, mu = mu_val, boundary = boundary,
                                               ndt = ndt_val, poutlier = pout)
            expect_equal(stan_loglik, r_loglik, tolerance = 1e-8, label = label)
          }
        }
      }
    }
  }

  mu_val <- 3.0
  alpha_val <- 0.5
  ndt_val <- 0.2

  # Below ndt: with no outlier component the response is impossible...
  y_below <- 0.15
  expect_equal(
    cogmod_invgaussian_lpdf(Y = y_below, mu = mu_val, boundary = alpha_val,
                        ndt = ndt_val, poutlier = 0),
    -Inf, label = "Y < ndt, poutlier = 0")

  # ...but with one it keeps positive density, which is the whole point
  lp <- cogmod_invgaussian_lpdf(Y = y_below, mu = mu_val, boundary = alpha_val,
                            ndt = ndt_val, poutlier = 0.02)
  expect_true(is.finite(lp))
  expect_equal(lp, dcogmod_invgaussian(y_below, drift = mu_val, boundary = alpha_val,
                                   ndt = ndt_val, poutlier = 0.02, log = TRUE),
               tolerance = 1e-10, label = "Y < ndt, poutlier > 0")

  # Y exactly at ndt behaves the same way
  expect_equal(
    cogmod_invgaussian_lpdf(Y = ndt_val, mu = mu_val, boundary = alpha_val,
                        ndt = ndt_val, poutlier = 0),
    -Inf, label = "Y == ndt")

  # Invalid parameters
  expect_equal(cogmod_invgaussian_lpdf(Y = 0.3, mu = -1.0, boundary = alpha_val,
                                   ndt = ndt_val, poutlier = 0.02), -Inf)
  expect_equal(cogmod_invgaussian_lpdf(Y = 0.3, mu = mu_val, boundary = 0.0,
                                   ndt = ndt_val, poutlier = 0.02), -Inf)
  expect_equal(cogmod_invgaussian_lpdf(Y = 0.3, mu = mu_val, boundary = alpha_val,
                                   ndt = -0.1, poutlier = 0.02), -Inf)
  expect_equal(cogmod_invgaussian_lpdf(Y = 0.3, mu = mu_val, boundary = alpha_val,
                                   ndt = ndt_val, poutlier = 1.1), -Inf)

  # ndt = 0 is now an ordinary interior value, not a boundary
  expect_equal(
    cogmod_invgaussian_lpdf(Y = 0.1, mu = mu_val, boundary = alpha_val, ndt = 0,
                        poutlier = 0),
    dcogmod_invgaussian(0.1, drift = mu_val, boundary = alpha_val, ndt = 0, log = TRUE),
    tolerance = 1e-8, label = "ndt = 0")
})
