context("Single-Accumulator LBA")

test_that("rrt_lba produces valid reaction times and responds to parameters", {
  skip_on_cran()
  set.seed(123)
  n <- 10000  # Large sample size for reliable means

  # Parameter combinations for basic property tests
  param_combinations <- expand.grid(
    drift = c(1, 3),
    sigma = 1,
    sigmabias = 0.5,
    bs = 0.5,
    ndt = 0.3
  )

  # 1. Basic property tests
  for (i in 1:nrow(param_combinations)) {
    params <- param_combinations[i, ]
    label <- sprintf("params(drift=%.1f, sigma=%.1f, sigmabias=%.1f, bs=%.1f, ndt=%.1f)",
                     params$drift, params$sigma, params$sigmabias, params$bs, params$ndt)
    rts <- rrt_lba(n, drift = params$drift, sigma = params$sigma,
                   sigmabias = params$sigmabias, bs = params$bs, ndt = params$ndt)

    # Check for NA values
    if (any(is.na(rts))) {
      warning("NA values generated by rrt_lba for ", label)
      next
    }

    # All RTs should be >= ndt
    expect_true(all(rts >= params$ndt),
                label = paste(label, "- All RTs >= ndt"))

    # All RTs should be finite
    expect_true(all(is.finite(rts)),
                label = paste(label, "- All RTs are finite"))
  }

  # 2. Parameter sensitivity tests
  # Effect of drift: higher drift should decrease mean RT
  params_low_drift <- list(drift = 1, sigma = 1, sigmabias = 0.5, bs = 0.5, ndt = 0.3)
  params_high_drift <- list(drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5, ndt = 0.3)

  rts_low_drift <- rrt_lba(n, drift = params_low_drift$drift, sigma = params_low_drift$sigma,
                           sigmabias = params_low_drift$sigmabias, bs = params_low_drift$bs,
                           ndt = params_low_drift$ndt)
  rts_high_drift <- rrt_lba(n, drift = params_high_drift$drift, sigma = params_high_drift$sigma,
                            sigmabias = params_high_drift$sigmabias, bs = params_high_drift$bs,
                            ndt = params_high_drift$ndt)

  mean_low_drift <- mean(rts_low_drift)
  mean_high_drift <- mean(rts_high_drift)

  expect_true(mean_high_drift < mean_low_drift,
              label = "Mean RT decreases with increasing drift")

  # Effect of bs: higher bs should increase mean RT
  params_low_bs <- list(drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5, ndt = 0.3)
  params_high_bs <- list(drift = 3, sigma = 1, sigmabias = 0.5, bs = 1, ndt = 0.3)

  rts_low_bs <- rrt_lba(n, drift = params_low_bs$drift, sigma = params_low_bs$sigma,
                        sigmabias = params_low_bs$sigmabias, bs = params_low_bs$bs,
                        ndt = params_low_bs$ndt)
  rts_high_bs <- rrt_lba(n, drift = params_high_bs$drift, sigma = params_high_bs$sigma,
                         sigmabias = params_high_bs$sigmabias, bs = params_high_bs$bs,
                         ndt = params_high_bs$ndt)

  mean_low_bs <- mean(rts_low_bs)
  mean_high_bs <- mean(rts_high_bs)

  expect_true(mean_high_bs > mean_low_bs,
              label = "Mean RT increases with increasing bs")
})



test_that("drt_lba integrates correctly and returns valid densities", {
  skip_on_cran()
  set.seed(456)
  n_samples_for_range <- 5000
  tol_integration <- 1e-3  # Tolerance for integration

  # Parameter combinations
  param_combinations <- expand.grid(
    drift = c(1, 3),
    sigma = c(0.5, 1),
    sigmabias = c(0.2, 0.5),
    bs = 0.5,
    ndt = 0.3
  )

  # 1. Integration test
  for (i in 1:nrow(param_combinations)) {
    params <- param_combinations[i, ]
    label <- sprintf("params(drift=%.1f, sigma=%.1f, sigmabias=%.1f, bs=%.1f, ndt=%.1f)",
                     params$drift, params$sigma, params$sigmabias, params$bs, params$ndt)

    # Define the integrand
    integrand <- function(x) {
      drt_lba(x, drift = params$drift, sigma = params$sigma,
              sigmabias = params$sigmabias, bs = params$bs, ndt = params$ndt)
    }

    # Determine integration upper limit using simulated RTs
    x_sample_range <- rrt_lba(n_samples_for_range, drift = params$drift,
                              sigma = params$sigma, sigmabias = params$sigmabias,
                              bs = params$bs, ndt = params$ndt)
    if (any(is.na(x_sample_range)) || length(x_sample_range) < 2) {
      warning("Skipping integration test for ", label, " due to invalid sample range.")
      next
    }
    upper_limit <- quantile(x_sample_range, 0.9999, na.rm = TRUE) +
      10 * sd(x_sample_range, na.rm = TRUE)
    if (!is.finite(upper_limit) || upper_limit < params$ndt + 10) {
      upper_limit <- params$ndt + 100
    }

    # Compute the integral
    integral_result <- tryCatch(
      stats::integrate(integrand, lower = params$ndt + .Machine$double.eps,
                       upper = upper_limit, subdivisions = 1000,
                       rel.tol = tol_integration / 10, abs.tol = tol_integration / 10)$value,
      error = function(e) {
        warning("Integration failed for ", label, ": ", e$message)
        NA
      }
    )

    if (!is.na(integral_result)) {
      expect_equal(integral_result, 1, tolerance = tol_integration,
                   label = paste(label, "- Density integrates to 1"))
    }
  }

  # 2. Density value tests with a single parameter set
  params <- list(drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5, ndt = 0.3)
  rt_below_ndt <- params$ndt - 0.1
  rt_at_ndt <- params$ndt
  rt_above_ndt <- params$ndt + 0.5

  # Density should be 0 for RT < ndt
  expect_equal(drt_lba(rt_below_ndt, drift = params$drift, sigma = params$sigma,
                       sigmabias = params$sigmabias, bs = params$bs, ndt = params$ndt),
               0, label = "Density is 0 for RT < ndt")

  # Density should be non-negative at RT = ndt
  density_at_ndt <- drt_lba(rt_at_ndt, drift = params$drift, sigma = params$sigma,
                            sigmabias = params$sigmabias, bs = params$bs, ndt = params$ndt)
  expect_true(density_at_ndt >= 0,
              label = "Density is non-negative at RT = ndt")

  # Density should be non-negative for RT > ndt
  density_above_ndt <- drt_lba(rt_above_ndt, drift = params$drift, sigma = params$sigma,
                               sigmabias = params$sigmabias, bs = params$bs, ndt = params$ndt)
  expect_true(density_above_ndt >= 0,
              label = "Density is non-negative for RT > ndt")
})



context("Single-Accumulator LBA - brms")

test_that("lba model can recover parameters with brms", {
  skip_on_cran()
  skip_if_not_installed("brms")
  skip_if_not_installed("cmdstanr")

  set.seed(1234)
  n <- 4000
  true_drift <- 4
  true_sigma <- 1
  true_sigmabias <- 0.5
  true_bs <- 0.3
  true_ndt <- 0.16
  true_poutlier <- 0.02

  df <- data.frame(rt = rrt_lba(n, drift = true_drift, sigma = true_sigma,
                                sigmabias = true_sigmabias, bs = true_bs,
                                ndt = true_ndt, poutlier = true_poutlier))
  df <- df[df$rt < 1, , drop = FALSE]

  # sigma is fixed to 1: the evidence scale is arbitrary, so drift, sigmabias
  # and bs are only identified relative to it. ndt is now estimated directly.
  f <- brms::bf(
    rt ~ 1,
    sigma = 1,
    sigmabias ~ 1,
    bs ~ 1,
    ndt ~ 1,
    poutlier ~ 1,
    family = rt_lba()
  )

  priors <- c(
    cogmod_priors(f, df),
    brms::set_prior("normal(3, 1)", class = "Intercept", dpar = ""),
    brms::set_prior("normal(0, 1)", class = "Intercept", dpar = "sigmabias"),
    replace = TRUE
  )

  fit <- brms::brm(
    formula = f,
    data = df,
    prior = priors,
    stanvars = rt_lba_stanvars(),
    backend = "cmdstanr",
    algorithm = "pathfinder",
    init = 0,
    refresh = 0
  )

  fixed <- summary(fit)$fixed
  # ndt is on a log link and is the parameter the reparameterization is about
  expect_equal(exp(fixed["ndt_Intercept", "Estimate"]), true_ndt,
               tolerance = 0.08, label = "ndt recovery")
  expect_true(is.finite(fixed["Intercept", "Estimate"]))
})


test_that("Stan rt_lba_lpdf matches R drt_lba", {
  skip_on_cran()
  skip_if_not_installed("cmdstanr")

  rt_lba_lpdf_stan <- rt_lba_lpdf_expose()

  grid <- expand.grid(
    Y = c(0.3, 0.5, 0.8, 1.2, 2.0),
    drift = c(1, 3),
    sigma = c(0.5, 1),
    # the small start-point ranges are the ones that used to break: both
    # differences in the LBA bracket cancel as sigmabias -> 0
    sigmabias = c(1e-6, 1e-3, 0.5, 1.0),
    bs = c(0.2, 0.5),
    ndt = c(0, 0.1, 0.25),
    poutlier = c(0, 0.03)
  )

  for (k in seq_len(nrow(grid))) {
    g <- grid[k, ]
    stan_lpdf <- rt_lba_lpdf_stan(g$Y, g$drift, g$sigma, g$sigmabias, g$bs,
                                  g$ndt, g$poutlier)
    r_lpdf <- drt_lba(g$Y, drift = g$drift, sigma = g$sigma,
                      sigmabias = g$sigmabias, bs = g$bs, ndt = g$ndt,
                      poutlier = g$poutlier, log = TRUE)
    label <- sprintf("Y=%.2f, drift=%.1f, sigma=%.1f, A=%g, bs=%.1f, ndt=%.2f, p=%.2f",
                     g$Y, g$drift, g$sigma, g$sigmabias, g$bs, g$ndt, g$poutlier)
    expect_equal(stan_lpdf, r_lpdf, tolerance = 1e-8,
                 label = paste("Density mismatch:", label))
  }
})


test_that("the density stays normalised as the start-point range shrinks", {
  skip_on_cran()
  # Regression test. The bracket
  #   drift * (Phi(z2) - Phi(z1)) + sigma * (phi(z1) - phi(z2))
  # is divided by the start-point range A, and both differences vanish linearly
  # in A. Evaluating them directly (and flooring the result at 1e-10, as the
  # previous implementation did) made the density stop integrating to one below
  # about A = 0.1, and diverge outright below A = 0.01.
  for (A in c(2, 0.5, 0.1, 1e-2, 1e-4, 1e-6, 1e-8)) {
    total <- integrate(
      function(z) drt_lba(z, drift = 3, sigma = 1, sigmabias = A, bs = 0.5,
                          ndt = 0.3),
      lower = 0.3, upper = Inf, rel.tol = 1e-10
    )$value
    expect_equal(total, 1, tolerance = 1e-5,
                 label = sprintf("integral at sigmabias = %g", A))
  }

  # As the start-point range vanishes the model becomes the recinormal (LATER),
  # in which 1 / (RT - ndt) is normally distributed. Convergence is O(A), with
  # the relative error settling at about 9 * A for these parameters.
  recinormal <- function(t, drift = 3, s = 1, b = 0.5, ndt = 0.3) {
    dnorm(b / (t - ndt), drift, s) / (1 - pnorm(0, drift, s)) * b / (t - ndt)^2
  }
  x <- c(0.4, 0.5, 0.8)
  prev <- Inf
  for (A in c(1e-2, 1e-4, 1e-6)) {
    rel <- max(abs(drt_lba(x, sigmabias = A, ndt = 0.3) / recinormal(x) - 1))
    expect_lt(rel, 12 * A)
    expect_lt(rel, prev)
    prev <- rel
  }
})
