#' @title Log-Normal Race (LNR) Model
#'
#' @description
#' The Log-Normal Race (LNR) model is useful for modeling reaction times and
#' choices in decision-making tasks. Each choice option (accumulator) draws a
#' processing time from a LogNormal distribution; the winning accumulator (the
#' minimum draw) determines both the observed reaction time and the choice. The
#' observed RT is that decision time shifted by a non-decision time `ndt`, and a
#' fixed proportion `poutlier` of responses is generated by an outlier process
#' instead of by the race.
#'
#' Functions:
#' - `rcogmod_lnr()`: Simulates random draws from the LNR model.
#' - `dcogmod_lnr()`: Computes the density (likelihood).
#' - `cogmod_lnr()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `cogmod_lnr_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Parameterization
#'
#' Each accumulator `k` finishes at a LogNormal time with `meanlog = -nu_k` and
#' `sdlog = sigma_k`, so **larger `nu` means faster**. The observed reaction time
#' is `ndt + min(T_0, T_1)` and the observed choice is whichever accumulator got
#' there first.
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Nothing about it is taken from the data: it is not bounded by the
#' fastest observed response, so a non-decision time that varies by condition or
#' by participant can exceed the sample minimum wherever the data support it.
#'
#' This replaces the earlier `tau` / `minrt` pair, in which `ndt = tau * minrt`
#' with `minrt` set to the fastest observed RT. That capped the non-decision
#' time at an order statistic of the sample, so any condition or participant
#' whose true `ndt` exceeded the fastest observed response was inexpressible,
#' and the misfit surfaced as spurious effects on the race parameters.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable. That is what makes the direct parameterization of
#' `ndt` workable without taking a bound from the data.
#'
#' Because this model produces a **choice as well as a time**, the contaminant
#' has to produce both. It is a guess: the choice is uniform over the two
#' options, and the RT is a **half Student-t** with `3` degrees of freedom and
#' scale `minrt`.
#'
#' \deqn{f(t, k) = p \frac{1}{K} g(t) + (1 - p) f_k(t - ndt)}
#'
#' The `1 / K` is what keeps the total summing to one over the response options;
#' without it it would come to `1 + poutlier`. The half-t is used for the timing
#' because it is **flat at the origin** (zero derivative), so the very fastest
#' responses - the ones least plausibly decisions - are not starved of density,
#' and because its tails are heavy enough to cover the whole plausible RT range.
#' Plot it with `curve(2 * dt(x / 0.3, 3) / 0.3, 0, 3)`.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' # `minrt`
#'
#' `minrt` is the **fastest reaction time that could plausibly be a real
#' decision** - a conceptual floor for the task, not an observed statistic. It
#' is used directly as the scale of the outlier component, so it fixes what
#' "too fast to be a decision" means, and `ndt` is not bounded by it.
#'
#' It is **not estimated**: it is a constant that fixes the timescale. It rarely
#' needs touching, except when reaction times are not in seconds, where leaving
#' it at `0.3` is a silent failure rather than a loud one. See the `minrt`
#' section of [cogmod_lognormal()] for the full account, which applies
#' unchanged here.
#'
#' Put the family on the formula: `minrt` has to reach the Stan code, the
#' prediction methods and the priors, and carrying it in one place is what stops
#' them drifting apart. [cogmod_priors()], [cogmod_inits()] and
#' [cogmod_stanvars()] all read it off the formula.
#'
#' # Fitting
#'
#' ```r
#' f <- brms::bf(RT | dec(Error) ~ Condition, nuone ~ Condition,
#'               sigmazero ~ 1, sigmaone ~ 1, ndt ~ 1, poutlier ~ 1,
#'               family = cogmod_lnr())
#' brms::brm(f, data = df,
#'           prior    = cogmod_priors(f, df),
#'           init     = cogmod_inits(f, df),
#'           stanvars = cogmod_stanvars(f))
#' ```
#'
#' Use [cogmod_inits()] rather than `init = 0`. `brms` initialises on the
#' unconstrained scale, so `init = 0` puts `ndt` at `exp(0) = 1` second - above
#' nearly every sub-second RT, which leaves every response attributed to the
#' outlier component and the race parameters with no gradient at all.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` describes the **race alone** by default, as if
#' `poutlier` were zero, because the outlier component is a fixed regularizer
#' rather than a claim about how guesses are distributed. Use [with_outliers()]
#' for the fitted mixture - chiefly for `brms::pp_check()` - and
#' [without_outliers()] to go back. `log_lik()` is always the full mixture.
#'
#' `posterior_epred()` is not provided: for a race model the expectation needs
#' numerical integration per draw and per observation, and users are better off
#' summarising `posterior_predict()` draws.
#'
#' @param n Number of simulated trials. If `length(n) > 1`, the length is taken
#'   to be the number required.
#' @param nuzero,nuone The (inverse of the) log-space mean parameter for both
#'   accumulators (choice 0 and 1). Controls the central tendency of the
#'   reaction time. Can take any real value (-Inf, Inf), with larger values
#'   leading to *faster* RTs. Named 'nu' (=-meanlog) for consistency with other
#'   race models.
#' @param sigmazero,sigmaone The log-space standard deviation for both
#'   accumulators (choice 0 and 1). Controls the variability of reaction times.
#'   Must be positive (0, Inf). Larger values increase variability.
#' @param ndt Non-decision time (shift parameter), in seconds. Represents the
#'   time taken for processes unrelated to the decision (e.g., encoding, motor
#'   response). Must be non-negative. Range: [0, Inf).
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the race. Range: `[0, 1]`. At `poutlier = 0` the
#'   distribution reduces to the plain shifted LNR.
#' @param minrt Fastest reaction time that could plausibly be a real decision,
#'   in the same unit as the data. Used directly as the scale of the outlier
#'   component. A judgement about the task rather than a statistic: it is a
#'   constant, never estimated, is not read off the sample, and does not bound
#'   `ndt`. Defaults to `0.3`; change it for data that are not in seconds. See
#'   Details.
#'
#' @references
#' - Rouder, J. N., Province, J. M., Morey, R. D., Gomez, P., & Heathcote, A. (2015).
#'   The lognormal race: A cognitive-process model of choice and latency with desirable
#'   psychometric properties. Psychometrika, 80(2), 491-513.
#'
#' @examples
#' # Simulate data, with 2% of trials from the outlier process
#' data <- rcogmod_lnr(1000,
#'   nuzero = 1, nuone = 0.5, sigmazero = 1, sigmaone = 0.8,
#'   ndt = 0.2, poutlier = 0.02
#' )
#' head(data)
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_lnr(0.1, ndt = 0.2, response = 0, poutlier = 0.02)
#' dcogmod_lnr(0.1, ndt = 0.2, response = 0, poutlier = 0)
#'
#' @export
rcogmod_lnr <- function(n, nuzero = 0, nuone = 0, sigmazero = 1, sigmaone = 1,
                        ndt = 0.2, poutlier = 0, minrt = 0.3) {
  .rchoice("cogmod_lnr", n = n, ndt = ndt, poutlier = poutlier, minrt = minrt,
           mu = nuzero, nuone = nuone, sigmazero = sigmazero,
           sigmaone = sigmaone)
}


#' @rdname rcogmod_lnr
#' @param x The observed reaction time (RT).
#' @param response The decision indicator (0 or 1). 0 for choice 0, 1 for
#'   choice 1.
#' @param log Logical; if TRUE, returns the log-density. Default: FALSE.
#' @export
dcogmod_lnr <- function(x, nuzero = 0, nuone = 0, sigmazero = 1, sigmaone = 1,
                        ndt = 0.2, response, poutlier = 0, minrt = 0.3,
                        log = FALSE) {
  .dchoice("cogmod_lnr", x = x, response = response, ndt = ndt,
           poutlier = poutlier, minrt = minrt, log = log,
           mu = nuzero, nuone = nuone, sigmazero = sigmazero,
           sigmaone = sigmaone)
}


# Family ------------------------------------------------------------------

#' @rdname rcogmod_lnr
#' @param link_mu,link_nuone Link function for the nu parameters. `mu` is
#'   `nuzero`: `brms` requires the first distributional parameter of a custom
#'   family to be called `mu`, so that is the name the formula and this
#'   argument use, and `nuzero` is what it means.
#' @param link_sigmazero,link_sigmaone Link function for the sigma parameters.
#' @param link_ndt,link_poutlier Link functions for the non-decision time and
#'   the outlier rate.
#' @param predict_outliers Logical; whether `posterior_predict()` should include
#'   the outlier component. `FALSE` (the default) fixes `poutlier` to zero for
#'   prediction, so predictions describe the race alone; the likelihood is
#'   always the full mixture either way. On the prediction method itself the
#'   default is `NULL`, which defers to the flag carried on the model - see
#'   [with_outliers()] to change it after fitting. See Details.
#' @export
cogmod_lnr <- function(
  link_mu = "identity",
  link_nuone = "identity",
  link_sigmazero = "softplus",
  link_sigmaone = "softplus",
  link_ndt = "log",
  link_poutlier = "logit",
  predict_outliers = FALSE,
  minrt = 0.3
) {
  .choice_family(
    "cogmod_lnr",
    links = c(link_mu, link_nuone, link_sigmazero, link_sigmaone),
    predict_outliers = predict_outliers,
    minrt = minrt
  )
}


# Stanvars ----------------------------------------------------------------

#' @keywords internal
.cogmod_lnr_lpdf <- function(minrt = 0.3) {
  .choice_lpdf("cogmod_lnr", minrt = minrt)
}


#' @rdname rcogmod_lnr
#' @examples
#' \dontrun{
#' # You can expose the lpdf function as follows:
#' insight::check_if_installed("cmdstanr")
#' lpdf <- cogmod_lnr_lpdf_expose()
#' lpdf(
#'   Y = 0.5, mu = 0.5, nuone = 0.2, sigmazero = 1.0, sigmaone = 0.8,
#'   ndt = 0.2, poutlier = 0.02, dec = 0
#' )
#' }
#'
#' @export
cogmod_lnr_lpdf_expose <- function(minrt = 0.3) {
  .choice_expose("cogmod_lnr", minrt)
}


#' @rdname rcogmod_lnr
#' @export
cogmod_lnr_stanvars <- function(minrt = 0.3) {
  brms::stanvar(
    scode = .cogmod_lnr_lpdf(.as_minrt(minrt)),
    block = "functions"
  )
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_lnr
#' @inheritParams rcogmod_betagate
#' @export
log_lik_cogmod_lnr <- function(i, prep) {
  .log_lik_choice("cogmod_lnr", i, prep)
}


#' @rdname rcogmod_lnr
#' @inheritParams rcogmod_betagate
#' @importFrom brms get_dpar
#' @export
posterior_predict_cogmod_lnr <- function(i, prep, predict_outliers = NULL,
                                         ...) {
  .posterior_predict_choice("cogmod_lnr", i, prep, predict_outliers)
}


#' @rdname rcogmod_lnr
#' @export
posterior_epred_cogmod_lnr <- function(prep) {
  stop(
    "Computing posterior_epred for a race model needs numerical integration ",
    "per draw and per observation, which is prohibitive here. Use ",
    "posterior_predict() and summarise the draws instead.",
    call. = FALSE
  )
}
