#' @title Shifted Weibull Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Weibull distribution. A Weibull-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rcogmod_weibull()`: Simulates random draws.
#' - `dcogmod_weibull()`: Computes the density (likelihood).
#' - `cogmod_weibull()`: Creates a `brms::custom_family()`.
#' - `cogmod_weibull_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `mu` is the **shape** and `sigma` the **scale** of the Weibull decision time,
#' whose mean is `sigma * gamma(1 + 1 / mu)`.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [cogmod_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rcogmod_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' Note that the Weibull density is **unbounded at `ndt`** whenever the shape
#' `mu < 1`, which makes the likelihood unbounded as `ndt` approaches the fastest
#' response; the outlier component adds density rather than capping it, so it
#' cannot repair that. [cogmod_loggamma()] nests this family at `shape = 1` and lets
#' the data choose the shape instead of fixing it.
#'
#' Do **not** fit this with `init = 0`: it puts `ndt` at `exp(0) = 1` second and
#' the shape at `softplus(0) = 0.69`, inside the unbounded region above, and no
#' single scalar avoids both. Use [cogmod_inits()], which sets them separately:
#'
#' ```r
#' brms::brm(f, data = df, prior = cogmod_priors(f, df),
#'           stanvars = cogmod_stanvars(f), init = cogmod_inits(f, df))
#' ```
#'
#' See [cogmod_inits()] for why, and `?rcogmod_gamma` for what it costs when
#' ignored.
#'
#' @inheritParams rcogmod_lognormal
#' @inheritParams cogmod_lnr
#' @param mu Shape of the Weibull decision time. Must be positive.
#' @param sigma Scale of the Weibull decision time. Must be positive.
#'
#' @examples
#' rts <- rcogmod_weibull(1000, mu = 2, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' dcogmod_weibull(0.1, ndt = 0.3, poutlier = 0.02)
#' dcogmod_weibull(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rcogmod_weibull <- function(n, mu = 2, sigma = 0.5, ndt = 0.2, poutlier = 0,
                      minrt = 0.3) {
  .rshifted("cogmod_weibull", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_weibull
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
dcogmod_weibull <- function(x, mu = 2, sigma = 0.5, ndt = 0.2, poutlier = 0,
                      minrt = 0.3, log = FALSE) {
  .dshifted("cogmod_weibull", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_weibull
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
cogmod_weibull <- function(link_mu = "softplus", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE, minrt = 0.3) {
  .shifted_family("cogmod_weibull", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers, minrt = minrt)
}


#' @keywords internal
.cogmod_weibull_lpdf <- function(minrt = 0.3) {
  .shifted_lpdf("cogmod_weibull", minrt = minrt)
}


#' @rdname rcogmod_weibull
#' @export
cogmod_weibull_lpdf_expose <- function(minrt = 0.3) {
  .shifted_expose("cogmod_weibull", minrt)
}


#' @rdname rcogmod_weibull
#' @export
cogmod_weibull_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .cogmod_weibull_lpdf(.as_minrt(minrt)), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_weibull
#' @export
log_lik_cogmod_weibull <- function(i, prep) {
  .log_lik_shifted("cogmod_weibull", i, prep)
}


#' @rdname rcogmod_weibull
#' @export
posterior_predict_cogmod_weibull <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("cogmod_weibull", i, prep, predict_outliers)
}


#' @rdname rcogmod_weibull
#' @export
posterior_epred_cogmod_weibull <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("cogmod_weibull", prep, predict_outliers)
}
