#' @title Shifted LogNormal Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted LogNormal
#' distribution. A LogNormal-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rcogmod_lognormal()`: Simulates random draws from the shifted LogNormal model.
#' - `dcogmod_lognormal()`: Computes the density (likelihood).
#' - `cogmod_lognormal()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `cogmod_lognormal_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Parameterization
#'
#' The observed reaction time is `ndt + LogNormal(mu, sigma)`, so `mu` and
#' `sigma` are the mean and SD of the *decision time* on the log scale, and the
#' median reaction time is `ndt + exp(mu)`.
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Nothing about it is taken from the data: it is not bounded by the
#' fastest observed response, so a non-decision time that varies by condition or
#' by participant can exceed the sample minimum wherever the data support it.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable. That is what makes the direct parameterization of
#' `ndt` workable without taking a bound from the data.
#'
#' The outlier component is a **half Student-t** with `3` degrees of freedom and
#' scale `minrt`, i.e. `2 * dt(x / 0.3, df = 3) / 0.3` on `[0, Inf)` at the
#' default. Two properties motivate the shape. It is **flat at the origin**
#' (zero derivative), so the very fastest responses - the ones least plausibly
#' decisions - are not starved of density; a LogNormal or Gamma vanishes at zero
#' and an Exponential peaks there with maximal slope, and all three get this
#' backwards. And its tails are heavy, so it keeps positive density across the
#' whole plausible RT range rather than only in the fast region. Plot it with
#' `curve(2 * dt(x / 0.3, 3) / 0.3, 0, 3)`.
#'
#' # `minrt`
#'
#' `minrt` is the **fastest reaction time that could plausibly be a real
#' decision** - a conceptual floor for the task, not an observed statistic. It
#' is used directly as the scale of the outlier component, so it fixes what
#' "too fast to be a decision" means.
#'
#' It is a judgement about the task, not a statistic: nothing is read off the
#' sample, and `ndt` is not bounded by it. `minrt` only sets where the outlier
#' component has its mass.
#'
#' Because it is the scale itself, the component's shape relative to it is
#' fixed whatever value you choose: **61%** of the outlier mass falls below
#' `minrt`, and the density there is still 66% of its peak. The default of
#' `0.3` seconds suits keypress paradigms - the conditional accuracy functions
#' in the *Outliers* article show responses at chance below about 0.30 s across
#' three very different tasks.
#'
#' It is **not estimated**: it is a constant that fixes the timescale, in the
#' same way that the number of response options is a constant in an ordinal
#' model. It rarely needs touching, except when reaction times are not in
#' seconds:
#'
#' ```r
#' f <- brms::bf(RT ~ 1, sigma ~ 1, ndt ~ 1, poutlier ~ 1,
#'               family = cogmod_lognormal(minrt = 300)) # milliseconds
#' brms::brm(f, data = df,
#'           prior = cogmod_priors(f, df),
#'           stanvars = cogmod_stanvars(f),
#'           init = cogmod_inits(f, df))
#' ```
#'
#' Put the family on the formula and name it only there: `minrt` has to reach
#' the Stan code, the prediction methods and the priors, and carrying it in one
#' place is what stops them drifting apart. [cogmod_priors()],
#' [cogmod_stanvars()] and [cogmod_inits()] all read it off the formula.
#'
#' Leaving it at `0.3` with millisecond data is a silent failure rather than a
#' loud one: the component ends up many orders of magnitude below the decision
#' density everywhere in the data, `poutlier` collapses toward zero, and `ndt`
#' reverts to being pinned by the fastest observed response. Setting `minrt` in
#' the unit of the data makes the likelihood exactly equivariant to that unit,
#' so `ndt` comes back in whatever unit was supplied and `poutlier` is
#' unchanged.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' # Trimmed data: pin `poutlier` down, but not to zero
#'
#' `poutlier` is only weakly identified when there is little to identify it
#' *from* - which is why [cogmod_priors()] gives it an informative prior rather
#' than leaving it flat. If the data have already been trimmed, or only a
#' handful of implausibly fast responses remain, it is reasonable to stop asking
#' the data to estimate a rate at all.
#'
#' The right way to do that is a **very tight prior near zero**, not a hard zero:
#'
#' ```r
#' f <- brms::bf(RT ~ 1, sigma ~ 1, ndt ~ 1, poutlier ~ 1,
#'               family = cogmod_lognormal())
#' priors <- c(
#'   cogmod_priors(f, df),
#'   brms::prior(normal(-7, 0.5), class = "Intercept", dpar = "poutlier"),
#'   replace = TRUE
#' )
#' ```
#'
#' `normal(-7, 0.5)` on the logit scale is centred at about 0.09%, with 95% of
#' its mass between 0.03% and 0.24% - small enough to assert "there is
#' essentially no contamination here", while leaving the rate free to rise if
#' the data insist.
#'
#' Fixing it outright is also possible, with `poutlier = 0` in the `bf()`, which
#' makes `brms` treat it as a constant and reduces the model to the plain
#' shifted family. **Prefer the tight prior.** At exactly zero the density is
#' once again exactly zero below `ndt`, so the hard min-RT boundary returns and
#' `ndt` is pinned by the fastest observed response - which is the very problem
#' the outlier component was introduced to solve, reintroduced deliberately. A
#' rate of 0.1% is numerically negligible for every other purpose but still
#' keeps the density positive below `ndt`, so the likelihood stays smooth and
#' `ndt` stays free.
#'
#' Trim first either way. Neither option makes slow contaminants safe: those are
#' confounded with the right tail and bias `ndt` upward, so filter them before
#' fitting.
#'
#' Slow outliers are deliberately not handled by this component. A slow
#' contaminant is statistically confounded with the right tail of the RT
#' distribution itself, so it cannot be identified, and leaving such trials in
#' the data biases `ndt` upward. Filter implausibly slow responses before
#' fitting.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` and `posterior_epred()` describe the **decision process
#' alone** by default, as if `poutlier` were zero. For visualising effects the
#' outlier component is a nuisance that pulls expected values toward its own mean
#' and adds a spike of implausibly fast draws; it is also a fixed regularizer
#' rather than a claim about how guesses are distributed, so simulating from it
#' means simulating from something the model does not assert.
#'
#' ```r
#' brms::posterior_epred(m)
#' modelbased::estimate_means(m, by = "Condition")
#' marginaleffects::avg_predictions(m, by = "Condition")
#' ```
#'
#' Use [with_outliers()] for the fitted mixture, and [without_outliers()] to go
#' back. The one case that genuinely wants the mixture is a posterior predictive
#' check, since on untrimmed data the decision-only predictive has no fast spike
#' to match the one in the data:
#'
#' ```r
#' brms::pp_check(with_outliers(m))
#' ```
#'
#' The same flag can be set up front, with `cogmod_lognormal(predict_outliers =
#' TRUE)`.
#'
#' The flag is carried on the model rather than passed as an argument for a
#' reason. `brms` sends the `...` of `posterior_predict()` and
#' `posterior_epred()` to `prepare_predictions()`, not down to the family method;
#' `posterior_epred` reaches the family method with `prep` and nothing else. So
#' `posterior_epred(m, predict_outliers = TRUE)` is *silently ignored* rather
#' than erroring, and `insight`, `modelbased` and `marginaleffects` inherit that
#' behaviour. Carrying the flag on the object is what makes it work everywhere.
#'
#' The `predict_outliers` argument on the methods themselves still works when
#' they are called directly, and overrides the flag.
#'
#' `log_lik` has no such argument: the likelihood *is* the mixture, and dropping
#' a component from it would not be a different summary of the same model but a
#' different model. One consequence is that `posterior_predict()` and `log_lik()`
#' do not describe the same distribution by default. This also desyncs
#' `loo_pit()`, `loo_predict()` and `bayes_R2()` from `loo()`, not just
#' hand-rolled checks - anything that compares a simulated replicate against the
#' likelihood should be run on [with_outliers()].
#'
#' @param n Number of observations. If `length(n) > 1`, the length is taken to be
#'   the number required.
#' @param mu Mean of the decision time on the log scale (`meanlog`). Can take any
#'   real value. Range: (-Inf, Inf).
#' @param sigma SD of the decision time on the log scale (`sdlog`). Must be
#'   positive. Range: (0, Inf).
#' @param ndt Non-decision time (shift parameter), in seconds. Must be
#'   non-negative. Represents time for processes such as stimulus encoding and
#'   response execution. Range: [0, Inf).
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the decision process. Range: `[0, 1]`. At `poutlier = 0` the
#'   distribution reduces to the plain shifted LogNormal.
#' @param minrt Fastest reaction time that could plausibly be a real decision,
#'   in the same unit as the data. Used directly as the scale of the outlier
#'   component. A judgement about the task rather than a statistic: it is a
#'   constant, never estimated, is not read off the sample, and does not bound
#'   `ndt`. Defaults to `0.3`; change it for data that are not in seconds. See
#'   Details.
#'
#' @examples
#' # Simulate 1000 RTs with 2% outliers
#' rts <- rcogmod_lognormal(1000, mu = -0.7, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, main = "Simulated shifted LogNormal RTs", xlab = "RT (s)")
#'
#' # Responses faster than ndt have positive density, unlike the unmixed model
#' dcogmod_lognormal(0.1, ndt = 0.3, poutlier = 0.02)
#' dcogmod_lognormal(0.1, ndt = 0.3, poutlier = 0)
#'
#' # Setting minrt in the unit of the data makes the density equivariant to it
#' dcogmod_lognormal(1, mu = -0.7, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' 1000 * dcogmod_lognormal(1000,
#'   mu = -0.7 + log(1000), sigma = 0.5, ndt = 300,
#'   poutlier = 0.02, minrt = 300
#' )
#'
#' # Density of the outlier component alone
#' # curve(2 * dt(x / 0.3, df = 3) / 0.3, from = 0, to = 3, n = 1000)
#'
#' @export
rcogmod_lognormal <- function(n, mu = -0.7, sigma = 0.5, ndt = 0.2,
                              poutlier = 0, minrt = 0.3) {
  .rshifted("cogmod_lognormal", n = n, ndt = ndt, poutlier = poutlier,
            minrt = minrt, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_lognormal
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
dcogmod_lognormal <- function(x, mu = -0.7, sigma = 0.5, ndt = 0.2,
                              poutlier = 0, minrt = 0.3, log = FALSE) {
  .dshifted("cogmod_lognormal", x = x, ndt = ndt, poutlier = poutlier,
            minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rcogmod_lognormal
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default in `cogmod_lognormal()`) fixes `poutlier` to zero for prediction, so
#'   predictions describe the decision process alone; the likelihood is always
#'   the full mixture either way. On the prediction methods themselves the
#'   default is `NULL`, which defers to the flag carried on the model - see
#'   [with_outliers()] to change it after fitting. See Details.
#' @export
cogmod_lognormal <- function(
  link_mu = "identity",
  link_sigma = "softplus",
  link_ndt = "log",
  link_poutlier = "logit",
  predict_outliers = FALSE,
  minrt = 0.3
) {
  fam <- brms::custom_family(
    name = "cogmod_lognormal",
    dpars = c("mu", "sigma", "ndt", "poutlier"),
    links = c(link_mu, link_sigma, link_ndt, link_poutlier),
    lb = c(NA, 0, 0, 0), # sigma > 0, ndt > 0, poutlier >= 0
    ub = c(NA, NA, NA, 1), # poutlier <= 1
    type = "real" # Continuous outcome variable (RT)
  )
  # Both ride on the family because that is the only thing brms carries down to
  # a custom family's prediction methods. See the Details section of
  # ?rcogmod_lognormal, and with_outliers() for flipping the flag after fitting.
  #
  # `minrt` is deliberately not a dpar. brms has no notion of a default for
  # one: a dpar left out of the formula is *estimated*, not defaulted, so
  # `minrt` would silently become a free parameter for every user who did not
  # write `minrt = 0.3` into their bf(). Carrying it on the family gives it a
  # real default; the matching Stan constant comes from cogmod_lognormal_stanvars().
  fam$predict_outliers <- isTRUE(predict_outliers)
  invisible(.validate_minrt(minrt)) # validate before storing
  fam$minrt <- minrt
  fam
}


#' @keywords internal
.cogmod_lognormal_lpdf <- function(minrt = 0.3) {
  .shifted_lpdf("cogmod_lognormal", minrt = minrt)
}


#' @rdname rcogmod_lognormal
#' @export
cogmod_lognormal_lpdf_expose <- function(minrt = 0.3) {
  .shifted_expose("cogmod_lognormal", minrt)
}


#' @rdname rcogmod_lognormal
#' @export
cogmod_lognormal_stanvars <- function(minrt = 0.3) {
  brms::stanvar(
    scode = .cogmod_lognormal_lpdf(.as_minrt(minrt)),
    block = "functions"
  )
}


# brms methods ------------------------------------------------------------

#' @rdname rcogmod_lognormal
#' @inheritParams cogmod_lnr
#' @export
log_lik_cogmod_lognormal <- function(i, prep) {
  .log_lik_shifted("cogmod_lognormal", i, prep)
}


#' @rdname rcogmod_lognormal
#' @export
posterior_predict_cogmod_lognormal <- function(i, prep,
                                               predict_outliers = NULL,
                                               ...) {
  .posterior_predict_shifted("cogmod_lognormal", i, prep, predict_outliers)
}


#' @rdname rcogmod_lognormal
#' @export
posterior_epred_cogmod_lognormal <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("cogmod_lognormal", prep, predict_outliers)
}
