#' @title Shifted Gamma Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted Gamma
#' distribution. A Gamma-distributed decision time is shifted by a non-decision
#' time `ndt`, and a fixed proportion `poutlier` of responses is generated by an
#' outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_gamma()`: Simulates random draws.
#' - `drt_gamma()`: Computes the density (likelihood).
#' - `rt_gamma()`: Creates a `brms::custom_family()`.
#' - `rt_gamma_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `mu` is the **shape** and `sigma` the **scale** of the Gamma decision time,
#' so the mean decision time is `mu * sigma` and the median reaction time is
#' `ndt` plus the Gamma median.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rrt_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' Note that the Gamma density is **unbounded at `ndt`** whenever the shape
#' `mu < 1`, which makes the likelihood unbounded as `ndt` approaches the
#' fastest response. The outlier component cannot repair that, since it adds
#' density rather than capping it. Fit with `init = 0` and keep an eye on `mu`.
#' [rt_loggamma()] nests this family at `shape = sigma` and lets the data choose
#' the shape instead of fixing it.
#'
#' @inheritParams rrt_lognormal
#' @inheritParams lnr
#' @param mu Shape of the Gamma decision time. Must be positive.
#' @param sigma Scale of the Gamma decision time. Must be positive.
#'
#' @examples
#' rts <- rrt_gamma(1000, mu = 3, sigma = 0.15, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density
#' drt_gamma(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_gamma(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_gamma <- function(n, mu = 3, sigma = 0.15, ndt = 0.2, poutlier = 0,
                      minrt = 0.3) {
  .rrt_shifted("rt_gamma", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = mu, sigma = sigma)
}

#' @rdname rrt_gamma
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_gamma <- function(x, mu = 3, sigma = 0.15, ndt = 0.2, poutlier = 0,
                      minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_gamma", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rrt_gamma
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
rt_gamma <- function(link_mu = "softplus", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE, minrt = 0.3) {
  .rt_shifted_family("rt_gamma", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers, minrt = minrt)
}

#' @keywords internal
.rt_gamma_lpdf <- function(minrt = 0.3) {
  .rt_shifted_lpdf("rt_gamma", minrt = minrt)
}

#' @rdname rrt_gamma
#' @export
rt_gamma_lpdf_expose <- function(minrt = 0.3) {
  .rt_shifted_expose("rt_gamma", minrt)
}

#' @rdname rrt_gamma
#' @export
rt_gamma_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .rt_gamma_lpdf(.as_minrt(minrt)), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rrt_gamma
#' @export
log_lik_rt_gamma <- function(i, prep) {
  .log_lik_shifted("rt_gamma", i, prep)
}

#' @rdname rrt_gamma
#' @export
posterior_predict_rt_gamma <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("rt_gamma", i, prep, predict_outliers)
}

#' @rdname rrt_gamma
#' @export
posterior_epred_rt_gamma <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("rt_gamma", prep, predict_outliers)
}
