#' @title Shifted Inverse Gamma Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Inverse Gamma distribution. A Inverse Gamma-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_invgamma()`: Simulates random draws.
#' - `drt_invgamma()`: Computes the density (likelihood).
#' - `rt_invgamma()`: Creates a `brms::custom_family()`.
#' - `rt_invgamma_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `mu` is the **shape** and `sigma` the **scale** of the inverse Gamma
#' decision time, whose mean is `sigma / (mu - 1)` and exists only for `mu > 1`.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rrt_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' `posterior_epred()` returns `Inf` where `mu <= 1`, because the inverse Gamma
#' has no mean there. The right tail is a power law, so this family is the one to
#' reach for when the slow tail is heavy; [rt_loggamma()] covers the same
#' territory continuously through negative `shape`.
#'
#' @inheritParams rrt_lognormal
#' @inheritParams lnr
#' @param mu Shape of the inverse Gamma decision time. Must be positive.
#' @param sigma Scale of the inverse Gamma decision time. Must be positive.
#'
#' @examples
#' rts <- rrt_invgamma(1000, mu = 4, sigma = 1.5, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' drt_invgamma(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_invgamma(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_invgamma <- function(n, mu = 4, sigma = 1.5, ndt = 0.2, poutlier = 0,
                      minrt = 0.3) {
  .rrt_shifted("rt_invgamma", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = mu, sigma = sigma)
}


#' @rdname rrt_invgamma
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_invgamma <- function(x, mu = 4, sigma = 1.5, ndt = 0.2, poutlier = 0,
                      minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_invgamma", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rrt_invgamma
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
rt_invgamma <- function(link_mu = "softplus", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE, minrt = 0.3) {
  .rt_shifted_family("rt_invgamma", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers, minrt = minrt)
}


#' @keywords internal
.rt_invgamma_lpdf <- function(minrt = 0.3) {
  .rt_shifted_lpdf("rt_invgamma", minrt = minrt)
}


#' @rdname rrt_invgamma
#' @export
rt_invgamma_lpdf_expose <- function(minrt = 0.3) {
  .rt_shifted_expose("rt_invgamma", minrt)
}


#' @rdname rrt_invgamma
#' @export
rt_invgamma_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .rt_invgamma_lpdf(.as_minrt(minrt)), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rrt_invgamma
#' @export
log_lik_rt_invgamma <- function(i, prep) {
  .log_lik_shifted("rt_invgamma", i, prep)
}


#' @rdname rrt_invgamma
#' @export
posterior_predict_rt_invgamma <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("rt_invgamma", i, prep, predict_outliers)
}


#' @rdname rrt_invgamma
#' @export
posterior_epred_rt_invgamma <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("rt_invgamma", prep, predict_outliers)
}
