#' @title Shifted Wald Model (Inverse Gaussian)
#'
#' @description
#' Density, distribution function, random generation, and `brms` custom family
#' for the Shifted Wald distribution, also known as the Shifted Inverse Gaussian.
#' A Wald-distributed decision time is shifted by a non-decision time `ndt`, and
#' a fixed proportion `poutlier` of responses is generated by an outlier process
#' instead of by the decision process.
#'
#' Functions:
#' - `rrt_invgaussian()`: Simulates random draws.
#' - `drt_invgaussian()`: Computes the density (likelihood).
#' - `prt_invgaussian()`: Computes the cumulative distribution function (CDF).
#' - `rt_invgaussian()`: Creates a `brms::custom_family()`.
#' - `rt_invgaussian_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' The Wald distribution describes the time it takes for a Wiener diffusion
#' process starting at 0 to reach a threshold `bs` > 0, given a positive drift
#' rate `drift` > 0. That time is then shifted by a non-decision time `ndt`.
#'
#' It is mathematically equivalent to shifting an Inverse Gaussian distribution
#' with mean `bs / drift` and shape `bs^2`. In the `brms` family the drift rate
#' is named `mu`, since `brms` requires a parameter of that name.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rrt_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' The Wald density vanishes at the shift with all derivatives, like the
#' LogNormal, so `ndt` is well behaved here and there is no unbounded-likelihood
#' boundary of the kind [rt_gamma()] and [rt_weibull()] have at shape `< 1`.
#'
#' The random generation algorithm is that of Michael, Schucany, and Haas
#' (1976), as used in the `statmod` package.
#'
#' @inheritParams rrt_lognormal
#' @inheritParams lnr
#' @param drift Drift rate. Must be positive. Represents the average speed of
#'   evidence accumulation. Range: (0, Inf).
#' @param bs Decision threshold (boundary separation). Must be positive.
#'   Represents the amount of evidence needed to make a decision.
#'   Range: (0, Inf).
#'
#' @references
#' - Michael, J. R., Schucany, W. R., & Haas, R. W. (1976). Generating Random Variates Using
#'     Transformations with Multiple Roots. *The American Statistician*, *30*(2), 88-90. \doi{10.2307/2683801}
#' - Anders, R., Alario, F., & Van Maanen, L. (2016). The shifted Wald distribution for
#'     response time data analysis. *Psychological Methods*, *21*(3), 309-327. \doi{10.1037/met0000063}
#' - Matzke, D., & Wagenmakers, E. J. (2009). Psychological interpretation of the ex-Gaussian
#'     and shifted Wald parameters: A diffusion model analysis. *Psychonomic Bulletin & Review*,
#'     *16*(5), 798-817. \doi{10.3758/PBR.16.5.798}
#' - Folks, J. L., & Chhikara, R. S. (1978). The inverse Gaussian distribution and its
#'     statistical application-a review. *Journal of the Royal Statistical Society Series B:
#'     Statistical Methodology*, *40*(3), 263-275.
#'
#' @examples
#' # Simulate 1000 RTs with 2% outliers
#' rts <- rrt_invgaussian(1000, drift = 3, bs = 0.5, ndt = 0.2, poutlier = 0.02)
#' # hist(rts, breaks = 50, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' drt_invgaussian(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_invgaussian(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_invgaussian <- function(n, drift = 3, bs = 0.5, ndt = 0.2, poutlier = 0,
                            minrt = 0.3) {
  .rrt_shifted("rt_invgaussian", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = drift, bs = bs)
}


#' @rdname rrt_invgaussian
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_invgaussian <- function(x, drift = 3, bs = 0.5, ndt = 0.2, poutlier = 0,
                            minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_invgaussian", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = drift, bs = bs)
}


#' @rdname rrt_invgaussian
#' @param q Vector of quantiles (observed reaction times).
#' @param lower.tail Logical; if TRUE (default), probabilities are `P[X <= x]`,
#'   otherwise `P[X > x]`.
#' @param log.p Logical; if TRUE, probabilities p are given as log(p).
#' @export
prt_invgaussian <- function(q, drift = 3, bs = 0.5, ndt = 0.2, poutlier = 0,
                            minrt = 0.3, lower.tail = TRUE, log.p = FALSE) {
  params <- .prepare_rt_shifted("rt_invgaussian", x = q, ndt = ndt,
                                poutlier = poutlier, mu = drift, bs = bs)

  t <- params$x - params$ndt
  cdf_dec <- rep(NA_real_, params$ndraws)
  cdf_dec[t <= 0] <- 0
  inf_idx <- is.infinite(t)
  cdf_dec[inf_idx] <- 1

  calc <- (t > 0) & !inf_idx
  if (any(calc)) {
    ig_mu <- params$bs[calc] / params$mu[calc]
    lambda <- params$bs[calc]^2
    tv <- t[calc]

    sqrt_l_t <- sqrt(lambda / tv)
    t_mu <- tv / ig_mu

    v <- stats::pnorm(sqrt_l_t * (t_mu - 1)) +
      exp(2 * lambda / ig_mu) * stats::pnorm(-sqrt_l_t * (t_mu + 1))
    cdf_dec[calc] <- pmin(pmax(v, 0), 1)
  }

  # Mixture CDF: the outlier component has support over the whole positive line
  cdf <- params$poutlier * .pcontam(params$x, minrt = minrt) +
    (1 - params$poutlier) * cdf_dec

  if (!lower.tail) cdf <- 1 - cdf
  if (log.p) cdf <- log(cdf)
  cdf
}


#' @rdname rrt_invgaussian
#' @param link_mu,link_bs,link_ndt,link_poutlier Link functions for the
#'   parameters. `mu` is the drift rate.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
rt_invgaussian <- function(link_mu = "softplus", link_bs = "softplus",
                           link_ndt = "log", link_poutlier = "logit",
                           predict_outliers = FALSE, minrt = 0.3) {
  .rt_shifted_family("rt_invgaussian", links = c(link_mu, link_bs),
                     predict_outliers = predict_outliers, minrt = minrt)
}


#' @keywords internal
.rt_invgaussian_lpdf <- function(minrt = 0.3) {
  .rt_shifted_lpdf("rt_invgaussian", minrt = minrt)
}


#' @rdname rrt_invgaussian
#' @export
rt_invgaussian_lpdf_expose <- function(minrt = 0.3) {
  .rt_shifted_expose("rt_invgaussian", minrt)
}


#' @rdname rrt_invgaussian
#' @export
rt_invgaussian_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .rt_invgaussian_lpdf(.as_minrt(minrt)),
                block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rrt_invgaussian
#' @export
log_lik_rt_invgaussian <- function(i, prep) {
  .log_lik_shifted("rt_invgaussian", i, prep)
}


#' @rdname rrt_invgaussian
#' @export
posterior_predict_rt_invgaussian <- function(i, prep, predict_outliers = NULL,
                                             ...) {
  .posterior_predict_shifted("rt_invgaussian", i, prep, predict_outliers)
}


#' @rdname rrt_invgaussian
#' @export
posterior_epred_rt_invgaussian <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("rt_invgaussian", prep, predict_outliers)
}
