#' @title Shifted Inverse Weibull Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Inverse Weibull distribution. A Inverse Weibull-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_invweibull()`: Simulates random draws.
#' - `drt_invweibull()`: Computes the density (likelihood).
#' - `rt_invweibull()`: Creates a `brms::custom_family()`.
#' - `rt_invweibull_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `mu` is the **shape** and `sigma` the **scale** of the inverse Weibull
#' (Frechet) decision time, whose mean is `sigma * gamma(1 - 1 / mu)` and exists
#' only for `mu > 1`.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rrt_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' `posterior_epred()` returns `Inf` where `mu <= 1`, because the Frechet has no
#' mean there. [rt_loggamma()] nests this family at `shape = -1`.
#'
#' @inheritParams rrt_lognormal
#' @inheritParams lnr
#' @param mu Shape of the inverse Weibull (Frechet) decision time. Must be positive.
#' @param sigma Scale of the inverse Weibull (Frechet) decision time. Must be positive.
#'
#' @examples
#' rts <- rrt_invweibull(1000, mu = 3, sigma = 0.4, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' drt_invweibull(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_invweibull(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_invweibull <- function(n, mu = 3, sigma = 0.4, ndt = 0.2, poutlier = 0,
                      minrt = 0.3) {
  .rrt_shifted("rt_invweibull", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = mu, sigma = sigma)
}


#' @rdname rrt_invweibull
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_invweibull <- function(x, mu = 3, sigma = 0.4, ndt = 0.2, poutlier = 0,
                      minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_invweibull", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rrt_invweibull
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
rt_invweibull <- function(link_mu = "softplus", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE, minrt = 0.3) {
  .rt_shifted_family("rt_invweibull", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers, minrt = minrt)
}


#' @keywords internal
.rt_invweibull_lpdf <- function(minrt = 0.3) {
  .rt_shifted_lpdf("rt_invweibull", minrt = minrt)
}


#' @rdname rrt_invweibull
#' @export
rt_invweibull_lpdf_expose <- function(minrt = 0.3) {
  .rt_shifted_expose("rt_invweibull", minrt)
}


#' @rdname rrt_invweibull
#' @export
rt_invweibull_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .rt_invweibull_lpdf(.as_minrt(minrt)), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rrt_invweibull
#' @export
log_lik_rt_invweibull <- function(i, prep) {
  .log_lik_shifted("rt_invweibull", i, prep)
}


#' @rdname rrt_invweibull
#' @export
posterior_predict_rt_invweibull <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("rt_invweibull", i, prep, predict_outliers)
}


#' @rdname rrt_invweibull
#' @export
posterior_epred_rt_invweibull <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("rt_invweibull", prep, predict_outliers)
}
