#' @title Shifted LogNormal Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted LogNormal
#' distribution. A LogNormal-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_lognormal()`: Simulates random draws from the shifted LogNormal model.
#' - `drt_lognormal()`: Computes the density (likelihood).
#' - `rt_lognormal()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `rt_lognormal_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Parameterization
#'
#' The observed reaction time is `ndt + LogNormal(mu, sigma)`, so `mu` and
#' `sigma` are the mean and SD of the *decision time* on the log scale, and the
#' median reaction time is `ndt + exp(mu)`.
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Earlier versions expressed it as `tau * minrt`, a proportion of the
#' minimum observed RT injected as data. That capped `ndt` at an order statistic
#' of the sample, so a non-decision time larger than the fastest observed
#' response could not be represented - a real limitation once `ndt` varies by
#' condition or participant, because the cap is then shared across all of them.
#' `tau` and `minrt` no longer exist.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable. That is what makes the direct parameterization of
#' `ndt` workable without taking a bound from the data.
#'
#' The outlier component is fixed at a **half Student-t** with scale `0.4` and
#' `3` degrees of freedom, i.e. `2 * dt(x / 0.4, df = 3) / 0.4` on `[0, Inf)`.
#' Two properties motivate it. It is **flat at the origin** (zero derivative), so
#' the very fastest responses - the ones least plausibly decisions - are not
#' starved of density; a LogNormal or Gamma vanishes at zero and an Exponential
#' peaks there with maximal slope, and all three get this backwards. And its
#' tails are heavy, so it keeps positive density across the whole plausible RT
#' range rather than only in the fast region. Plot it with
#' `curve(2 * dt(x / 0.4, 3) / 0.4, 0, 3)`.
#'
#' Because these hyperparameters are fixed, **reaction times are assumed to be
#' measured in seconds**. Millisecond-scale data will fit without erroring - the
#' heavy tails degrade gracefully rather than underflowing - but the outlier
#' component will be badly calibrated.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' Slow outliers are deliberately not handled by this component. A slow
#' contaminant is statistically confounded with the right tail of the RT
#' distribution itself, so it cannot be identified, and leaving such trials in
#' the data biases `ndt` upward. Filter implausibly slow responses before
#' fitting.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` and `posterior_epred()` describe the **decision process
#' alone** by default, as if `poutlier` were zero. For visualising effects the
#' outlier component is a nuisance that pulls expected values toward its own mean
#' and adds a spike of implausibly fast draws; it is also a fixed regularizer
#' rather than a claim about how guesses are distributed, so simulating from it
#' means simulating from something the model does not assert.
#'
#' ```r
#' brms::posterior_epred(m)
#' modelbased::estimate_means(m, by = "Condition")
#' marginaleffects::avg_predictions(m, by = "Condition")
#' ```
#'
#' Use [with_outliers()] for the fitted mixture, and [without_outliers()] to go
#' back. The one case that genuinely wants the mixture is a posterior predictive
#' check, since on untrimmed data the decision-only predictive has no fast spike
#' to match the one in the data:
#'
#' ```r
#' brms::pp_check(with_outliers(m))
#' ```
#'
#' The same flag can be set up front, with `rt_lognormal(predict_outliers =
#' TRUE)`.
#'
#' The flag is carried on the model rather than passed as an argument for a
#' reason. `brms` sends the `...` of `posterior_predict()` and
#' `posterior_epred()` to `prepare_predictions()`, not down to the family method;
#' `posterior_epred` reaches the family method with `prep` and nothing else. So
#' `posterior_epred(m, predict_outliers = TRUE)` is *silently ignored* rather
#' than erroring, and `insight`, `modelbased` and `marginaleffects` inherit that
#' behaviour. Carrying the flag on the object is what makes it work everywhere.
#'
#' The `predict_outliers` argument on the methods themselves still works when
#' they are called directly, and overrides the flag.
#'
#' `log_lik` has no such argument: the likelihood *is* the mixture, and dropping
#' a component from it would not be a different summary of the same model but a
#' different model. One consequence is that `posterior_predict()` and `log_lik()`
#' no longer describe the same distribution by default, so a hand-rolled LOO-PIT
#' check should use [with_outliers()].
#'
#' @param n Number of observations. If `length(n) > 1`, the length is taken to be
#'   the number required.
#' @param mu Mean of the decision time on the log scale (`meanlog`). Can take any
#'   real value. Range: (-Inf, Inf).
#' @param sigma SD of the decision time on the log scale (`sdlog`). Must be
#'   positive. Range: (0, Inf).
#' @param ndt Non-decision time (shift parameter), in seconds. Must be
#'   non-negative. Represents time for processes such as stimulus encoding and
#'   response execution. Range: [0, Inf).
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the decision process. Range: `[0, 1]`. At `poutlier = 0` the
#'   distribution reduces to the plain shifted LogNormal.
#'
#' @examples
#' # Simulate 1000 RTs with 2% outliers
#' rts <- rrt_lognormal(1000, mu = -0.7, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, main = "Simulated shifted LogNormal RTs", xlab = "RT (s)")
#'
#' # Responses faster than ndt have positive density, unlike the unmixed model
#' drt_lognormal(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_lognormal(0.1, ndt = 0.3, poutlier = 0)
#'
#' # Density of the outlier component alone
#' # curve(2 * dt(x / 0.4, df = 3) / 0.4, from = 0, to = 3, n = 1000)
#'
#' @export
rrt_lognormal <- function(n, mu = -0.7, sigma = 0.5, ndt = 0.2, poutlier = 0) {
  # Prepare and validate all inputs for RNG
  params <- .prepare_rt_lognormal(
    x = NULL,
    n = n,
    mu = mu,
    sigma = sigma,
    ndt = ndt,
    poutlier = poutlier
  )
  m <- params$ndraws

  # Draw the mixture indicator, then the corresponding component
  is_out <- stats::runif(m) < params$poutlier
  out <- numeric(m)

  if (any(is_out)) {
    out[is_out] <- abs(.CONTAM_SCALE * stats::rt(sum(is_out), df = .CONTAM_DF))
  }
  if (any(!is_out)) {
    keep <- !is_out
    out[keep] <- stats::rlnorm(
      sum(keep),
      meanlog = params$mu[keep],
      sdlog = params$sigma[keep]
    ) + params$ndt[keep]
  }
  out
}


#' @rdname rrt_lognormal
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_lognormal <- function(
  x,
  mu = -0.7,
  sigma = 0.5,
  ndt = 0.2,
  poutlier = 0,
  log = FALSE
) {
  # Prepare and validate inputs for density. Invalid parameter values give a
  # zero density rather than an error, so that the function can be applied
  # across posterior draws without a single bad draw aborting the call.
  params <- tryCatch(
    .prepare_rt_lognormal(
      x = x,
      n = NULL,
      mu = mu,
      sigma = sigma,
      ndt = ndt,
      poutlier = poutlier
    ),
    error = function(e) {
      warning(conditionMessage(e), ". Returning 0 density / -Inf log-density.")
      list(ndraws = length(x), error = TRUE)
    }
  )
  if (!is.null(params$error)) {
    return(rep(ifelse(log, -Inf, 0), params$ndraws))
  }

  # Outlier component: supported over the whole positive line
  lp_out <- .dcontam(params$x, log = TRUE)

  # Decision component: zero density at or below ndt
  x_adj <- params$x - params$ndt
  lp_dec <- ifelse(
    x_adj > 0,
    stats::dlnorm(
      pmax(x_adj, 1e-300),
      meanlog = params$mu,
      sdlog = params$sigma,
      log = TRUE
    ),
    -Inf
  )

  log_density <- .log_mix(params$poutlier, lp_out, lp_dec)
  log_density[is.na(log_density)] <- -Inf

  if (log) {
    log_density
  } else {
    exp(log_density)
  }
}


# Internals ---------------------------------------------------------------

# Fixed hyperparameters of the outlier component: a half Student-t on [0, Inf).
# Hard-coded rather than exposed - `ndt` recovery is insensitive to them over a
# wide range, so there is nothing useful to tune, and fixing them keeps
# `poutlier` comparable across datasets.
#
# The half-t is flat at the origin (zero derivative), which matters: the fastest
# responses are the ones least likely to be decisions, so the component must not
# thin out there. A LogNormal or Gamma vanishes at 0 and an Exponential peaks
# there with maximal slope; all three get this wrong. df = 3 keeps tails heavy
# enough that a unit error (RT in ms) degrades rather than underflowing to zero,
# while keeping the mean finite for posterior_epred().
.CONTAM_SCALE <- 0.4
.CONTAM_DF <- 3

# Density of the half-t component.
#' @keywords internal
.dcontam <- function(x, log = FALSE) {
  ld <- log(2) + stats::dt(x / .CONTAM_SCALE, df = .CONTAM_DF, log = TRUE) -
    log(.CONTAM_SCALE)
  ld[x <= 0] <- -Inf
  if (log) ld else exp(ld)
}

# Mean of the half-t; finite for df > 1.
#' @keywords internal
.mcontam <- function() {
  nu <- .CONTAM_DF
  2 * .CONTAM_SCALE * sqrt(nu) * gamma((nu + 1) / 2) /
    (sqrt(pi) * (nu - 1) * gamma(nu / 2))
}


#' @keywords internal
.prepare_rt_lognormal <- function(x = NULL, n = NULL, mu, sigma, ndt, poutlier) {
  # --- Basic Validation ---
  if (any(sigma <= 0, na.rm = TRUE)) stop("`sigma` must be positive.")
  if (any(ndt < 0, na.rm = TRUE)) stop("`ndt` must be non-negative.")
  if (any(poutlier < 0 | poutlier > 1, na.rm = TRUE)) {
    stop("`poutlier` must be in [0, 1].")
  }
  # mu can be any real number, no check needed.

  # --- Determine Target Length ---
  if (!is.null(x)) {
    # For Density (drt_lognormal)
    m <- max(length(x), length(mu), length(sigma), length(ndt), length(poutlier))
    if (m == 0) stop("At least one input vector must have non-zero length.")
  } else if (!is.null(n)) {
    # For RNG (rrt_lognormal)
    if (length(n) > 1) n <- length(n)
    if (length(n) != 1 || n < 0 || n != floor(n)) {
      stop("n must be a single non-negative integer.")
    }
    m <- max(n, length(mu), length(sigma), length(ndt), length(poutlier))
    if (n == 0) m <- 0
  } else {
    stop("Either 'x' or 'n' must be provided.")
  }

  # --- Recycle Parameters ---
  params <- list(
    mu = rep_len(mu, m),
    sigma = rep_len(sigma, m),
    ndt = rep_len(ndt, m),
    poutlier = rep_len(poutlier, m)
  )
  if (!is.null(x)) params$x <- rep_len(x, m)

  params$ndraws <- m
  params
}
