#' @title Shifted Log-Weibull Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted
#' Log-Weibull distribution. A Log-Weibull-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_logweibull()`: Simulates random draws.
#' - `drt_logweibull()`: Computes the density (likelihood).
#' - `rt_logweibull()`: Creates a `brms::custom_family()`.
#' - `rt_logweibull_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' `log(RT - ndt)` follows a **Gumbel** distribution with location `mu` and scale
#' `sigma` - the log-Weibull. The mean decision time is `exp(mu) * gamma(1 - sigma)`,
#' which exists only for `sigma < 1`.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()], [p_outlier()] and
#' [cogmod_priors()] all work here too. See `?rrt_lognormal` for why `ndt` is
#' expressed directly in seconds rather than as a fraction of the fastest
#' observed response, what the half Student-t outlier component is for, and why
#' `minrt` is a constant on the family rather than a `dpar`.
#'
#' `posterior_epred()` returns `Inf` where `sigma >= 1`, because the mean does not
#' exist there. Note this mean is *not* `exp(mu + sigma * 0.5772)`, which is the
#' geometric mean (the exponential of `E[log(RT - ndt)]`) rather than `E[RT - ndt]`.
#'
#' @inheritParams rrt_lognormal
#' @inheritParams lnr
#' @param mu Location of the Gumbel distribution on the log scale. Any real value.
#' @param sigma Scale of the Gumbel distribution on the log scale. Must be positive.
#'
#' @examples
#' rts <- rrt_logweibull(1000, mu = -0.8, sigma = 0.3, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' drt_logweibull(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_logweibull(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_logweibull <- function(n, mu = -0.8, sigma = 0.3, ndt = 0.2, poutlier = 0,
                      minrt = 0.3) {
  .rrt_shifted("rt_logweibull", n = n, ndt = ndt, poutlier = poutlier,
               minrt = minrt, mu = mu, sigma = sigma)
}


#' @rdname rrt_logweibull
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_logweibull <- function(x, mu = -0.8, sigma = 0.3, ndt = 0.2, poutlier = 0,
                      minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_logweibull", x = x, ndt = ndt, poutlier = poutlier,
               minrt = minrt, log = log, mu = mu, sigma = sigma)
}


#' @rdname rrt_logweibull
#' @param link_mu,link_sigma,link_ndt,link_poutlier Link functions for the
#'   parameters.
#' @param predict_outliers Logical; whether `posterior_predict()` and
#'   `posterior_epred()` should include the outlier component. `FALSE` (the
#'   default) fixes `poutlier` to zero for prediction, so predictions describe
#'   the decision process alone; the likelihood is always the full mixture
#'   either way. See [with_outliers()].
#' @export
rt_logweibull <- function(link_mu = "identity", link_sigma = "softplus",
                     link_ndt = "log", link_poutlier = "logit",
                     predict_outliers = FALSE, minrt = 0.3) {
  .rt_shifted_family("rt_logweibull", links = c(link_mu, link_sigma),
                     predict_outliers = predict_outliers, minrt = minrt)
}


#' @keywords internal
.rt_logweibull_lpdf <- function(minrt = 0.3) {
  .rt_shifted_lpdf("rt_logweibull", minrt = minrt)
}


#' @rdname rrt_logweibull
#' @export
rt_logweibull_lpdf_expose <- function(minrt = 0.3) {
  .rt_shifted_expose("rt_logweibull", minrt)
}


#' @rdname rrt_logweibull
#' @export
rt_logweibull_stanvars <- function(minrt = 0.3) {
  brms::stanvar(scode = .rt_logweibull_lpdf(.as_minrt(minrt)), block = "functions")
}


# brms methods ------------------------------------------------------------

#' @rdname rrt_logweibull
#' @export
log_lik_rt_logweibull <- function(i, prep) {
  .log_lik_shifted("rt_logweibull", i, prep)
}


#' @rdname rrt_logweibull
#' @export
posterior_predict_rt_logweibull <- function(i, prep, predict_outliers = NULL, ...) {
  .posterior_predict_shifted("rt_logweibull", i, prep, predict_outliers)
}


#' @rdname rrt_logweibull
#' @export
posterior_epred_rt_logweibull <- function(prep, predict_outliers = NULL) {
  .posterior_epred_shifted("rt_logweibull", prep, predict_outliers)
}
