#' @title Shifted Single-Accumulator LBA Model
#'
#' @description
#' Density, random generation, and `brms` custom family for a single-accumulator
#' Linear Ballistic Accumulator. Evidence rises linearly and ballistically - no
#' within-trial noise - from a start point drawn uniformly on `[0, sigmabias]`
#' at a rate drawn from a normal truncated at zero, until it reaches the
#' threshold `b = sigmabias + bs`. That finishing time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead.
#'
#' Functions:
#' - `rrt_lba()`: Simulates random draws.
#' - `drt_lba()`: Computes the density (likelihood).
#' - `rt_lba()`: Creates a `brms::custom_family()`.
#' - `rt_lba_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#'
#' @details
#' The full LBA is a race between one accumulator per response option, with the
#' winner determining both the choice and the RT. With no choice to model there
#' is nothing to race, so this is the single-accumulator version and the RT is
#' just that one accumulator's finishing time. All the RT variability comes from
#' across-trial variability in the start point and the drift rate, rather than
#' from moment-to-moment noise within the trial.
#'
#' `sigma` is conventionally **fixed to 1** rather than estimated, because the
#' evidence scale is arbitrary: multiplying `mu`, `sigma`, `sigmabias` and `bs`
#' by a common constant leaves the decision time `(b - start) / drift` unchanged,
#' so only ratios are identified and one parameter must be pinned to fix the
#' scale. Fix it in the formula with `sigma = 1`.
#'
#' As `sigmabias` shrinks toward zero the model reduces to the *recinormal*, in
#' which `1 / (RT - ndt)` is normally distributed - the LATER model.
#'
#' `ndt`, `poutlier` and `minrt` mean exactly what they do in [rt_lognormal()],
#' and [with_outliers()], [without_outliers()] and [cogmod_priors()] work here
#' too. See `?rrt_lognormal` for the full account.
#'
#' Note that `posterior_epred()` is not available: the decision time has no
#' finite mean, because `E[1 / drift]` diverges for a normal truncated at zero.
#'
#' @inheritParams rrt_lognormal
#' @param drift Mean drift rate.
#' @param sigma Standard deviation of the drift rate. Conventionally fixed to 1.
#' @param sigmabias The starting-point range (`A`); must be positive.
#' @param bs The threshold offset, such that `b = sigmabias + bs`; must be
#'   positive.
#'
#' @examples
#' # Simulate 1000 trials with 2% outliers
#' rts <- rrt_lba(1000, drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5,
#'                ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, xlab = "RT (s)")
#'
#' # Responses faster than ndt keep positive density, unlike the unmixed model
#' drt_lba(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_lba(0.1, ndt = 0.3, poutlier = 0)
#'
#' @export
rrt_lba <- function(n, drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5,
                    ndt = 0.3, poutlier = 0, minrt = 0.3) {
  .rrt_shifted("rt_lba", n = n, ndt = ndt, poutlier = poutlier, minrt = minrt,
               mu = drift, sigma = sigma, sigmabias = sigmabias, bs = bs)
}


#' @rdname rrt_lba
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_lba <- function(x, drift = 3, sigma = 1, sigmabias = 0.5, bs = 0.5,
                    ndt = 0.3, poutlier = 0, minrt = 0.3, log = FALSE) {
  .drt_shifted("rt_lba", x = x, ndt = ndt, poutlier = poutlier, minrt = minrt,
               log = log, mu = drift, sigma = sigma, sigmabias = sigmabias,
               bs = bs)
}


# Internal helpers --------------------------------------------------

# The LBA defective density divided by the start-point range A, i.e.
#
#   [ drift * (Phi(z2) - Phi(z1)) + sigma * (phi(z1) - phi(z2)) ] / A
#
# with z2 = z1 + delta and delta = A / (sigma * t).
#
# Both differences vanish linearly in delta, so evaluating them directly and
# then dividing by A loses every significant digit once the start-point range is
# small: at A = 1e-2 the density is already wrong, and by A = 1e-4 it no longer
# integrates to one. (The previous implementation also floored the bracket at
# 1e-10, which turned that underflow into a spurious density floor spread over
# the whole line, so the "density" integrated to far more than one.)
#
# Below delta = 1e-4 the Taylor expansion in delta is used instead. Its
# truncation error there is ~1e-12 relative, while the direct form still has
# ~12 good digits, so the two agree across the switch. Above it, the two
# differences are taken tail-aware: Phi(z2) - Phi(z1) from the upper tail when
# both are positive, and phi(z1) - phi(z2) as phi(z1) * -expm1(...), which stays
# accurate however close the two arguments are.
#' @keywords internal
.lba_dens_over_A <- function(drift, sigma, st, z1, delta) {
  n <- max(length(drift), length(sigma), length(st), length(z1), length(delta))
  drift <- rep_len(drift, n)
  sigma <- rep_len(sigma, n)
  st <- rep_len(st, n)
  z1 <- rep_len(z1, n)
  delta <- rep_len(delta, n)

  phi1 <- stats::dnorm(z1)
  out <- numeric(n)

  small <- delta < 1e-4
  if (any(small)) {
    i <- small
    d <- delta[i]
    z <- z1[i]
    v <- drift[i]
    sg <- sigma[i]
    series <- (v + sg * z) -
      (d / 2) * (v * z + sg * (z^2 - 1)) +
      (d^2 / 6) * (v * (z^2 - 1) + sg * (z^3 - 3 * z))
    out[i] <- phi1[i] * series / st[i]
  }
  if (any(!small)) {
    i <- !small
    z2 <- z1[i] + delta[i]
    dPhi <- ifelse(
      z1[i] > 0,
      stats::pnorm(z1[i], lower.tail = FALSE) -
        stats::pnorm(z2, lower.tail = FALSE),
      stats::pnorm(z2) - stats::pnorm(z1[i])
    )
    dphi <- phi1[i] * -expm1(-delta[i] * (z1[i] + z2) / 2)
    out[i] <- (drift[i] * dPhi + sigma[i] * dphi) / (delta[i] * st[i])
  }
  out
}
