#' @title Shifted LogNormal Model
#'
#' @description
#' Density, random generation, and `brms` custom family for the shifted LogNormal
#' distribution. A LogNormal-distributed decision time is shifted by a
#' non-decision time `ndt`, and a fixed proportion `poutlier` of responses is
#' generated by an outlier process instead of by the decision process.
#'
#' Functions:
#' - `rrt_lognormal()`: Simulates random draws from the shifted LogNormal model.
#' - `drt_lognormal()`: Computes the density (likelihood).
#' - `rt_lognormal()`: Creates a `brms::custom_family()` for use in `brms` models.
#' - `rt_lognormal_stanvars()`: Generates the `stanvars` to pass to `brm()`.
#' - `p_outlier()`: Per-trial posterior probability of being an outlier.
#'
#' @details
#' # Parameterization
#'
#' The observed reaction time is `ndt + LogNormal(mu, sigma)`, so `mu` and
#' `sigma` are the mean and SD of the *decision time* on the log scale, and the
#' median reaction time is `ndt + exp(mu)`.
#'
#' `ndt` is expressed **directly, in seconds** (through a log link in the `brms`
#' family). Nothing about it is taken from the data: it is not bounded by the
#' fastest observed response, so a non-decision time that varies by condition or
#' by participant can exceed the sample minimum wherever the data support it.
#'
#' # The outlier component
#'
#' A shifted distribution assigns exactly zero density to any response faster
#' than `ndt`, which puts a hard boundary in the likelihood at the fastest
#' observed RT. Mixing in a component with support over the whole positive line
#' removes it: every response keeps positive density whatever `ndt` is, so the
#' boundary becomes a finite cost rather than a wall and the log-density stays
#' smooth and differentiable. That is what makes the direct parameterization of
#' `ndt` workable without taking a bound from the data.
#'
#' The outlier component is a **half Student-t** with `3` degrees of freedom and
#' scale `minrt`, i.e. `2 * dt(x / 0.3, df = 3) / 0.3` on `[0, Inf)` at the
#' default. Two properties motivate the shape. It is **flat at the origin**
#' (zero derivative), so the very fastest responses - the ones least plausibly
#' decisions - are not starved of density; a LogNormal or Gamma vanishes at zero
#' and an Exponential peaks there with maximal slope, and all three get this
#' backwards. And its tails are heavy, so it keeps positive density across the
#' whole plausible RT range rather than only in the fast region. Plot it with
#' `curve(2 * dt(x / 0.3, 3) / 0.3, 0, 3)`.
#'
#' # `minrt`
#'
#' `minrt` is the **fastest reaction time that could plausibly be a real
#' decision** - a conceptual floor for the task, not an observed statistic. It
#' is used directly as the scale of the outlier component, so it fixes what
#' "too fast to be a decision" means.
#'
#' It is a judgement about the task, not a statistic: nothing is read off the
#' sample, and `ndt` is not bounded by it. `minrt` only sets where the outlier
#' component has its mass.
#'
#' Because it is the scale itself, the component's shape relative to it is
#' fixed whatever value you choose: **61%** of the outlier mass falls below
#' `minrt`, and the density there is still 66% of its peak. The default of
#' `0.3` seconds suits keypress paradigms - the conditional accuracy functions
#' in the *Outliers* article show responses at chance below about 0.30 s across
#' three very different tasks.
#'
#' It is **not estimated**: it is a constant that fixes the timescale, in the
#' same way that the number of response options is a constant in an ordinal
#' model. It rarely needs touching, except when reaction times are not in
#' seconds:
#'
#' ```r
#' fam <- rt_lognormal(minrt = 300) # milliseconds
#' f <- brms::bf(RT ~ 1, sigma ~ 1, ndt ~ 1, poutlier ~ 1, family = fam)
#' brms::brm(f, data = df,
#'           prior = cogmod_priors(f, df),
#'           stanvars = rt_lognormal_stanvars(fam))
#' ```
#'
#' Put the family on the formula: `minrt` has to reach the Stan code, the
#' prediction methods and the priors, and carrying it in one place is what stops
#' them drifting apart. [cogmod_priors()] reads it off the formula, and
#' `rt_lognormal_stanvars()` accepts the family object directly.
#'
#' Leaving it at `0.3` with millisecond data is a silent failure rather than a
#' loud one: the component ends up many orders of magnitude below the decision
#' density everywhere in the data, `poutlier` collapses toward zero, and `ndt`
#' reverts to being pinned by the fastest observed response. Setting `minrt` in
#' the unit of the data makes the likelihood exactly equivariant to that unit,
#' so `ndt` comes back in whatever unit was supplied and `poutlier` is
#' unchanged.
#'
#' `poutlier` is a *rate*, not a classification: the model never labels
#' individual trials, it estimates what share of them came from elsewhere. Use
#' [p_outlier()] for per-trial posterior probabilities.
#'
#' Slow outliers are deliberately not handled by this component. A slow
#' contaminant is statistically confounded with the right tail of the RT
#' distribution itself, so it cannot be identified, and leaving such trials in
#' the data biases `ndt` upward. Filter implausibly slow responses before
#' fitting.
#'
#' # Predictions exclude the outlier component
#'
#' `posterior_predict()` and `posterior_epred()` describe the **decision process
#' alone** by default, as if `poutlier` were zero. For visualising effects the
#' outlier component is a nuisance that pulls expected values toward its own mean
#' and adds a spike of implausibly fast draws; it is also a fixed regularizer
#' rather than a claim about how guesses are distributed, so simulating from it
#' means simulating from something the model does not assert.
#'
#' ```r
#' brms::posterior_epred(m)
#' modelbased::estimate_means(m, by = "Condition")
#' marginaleffects::avg_predictions(m, by = "Condition")
#' ```
#'
#' Use [with_outliers()] for the fitted mixture, and [without_outliers()] to go
#' back. The one case that genuinely wants the mixture is a posterior predictive
#' check, since on untrimmed data the decision-only predictive has no fast spike
#' to match the one in the data:
#'
#' ```r
#' brms::pp_check(with_outliers(m))
#' ```
#'
#' The same flag can be set up front, with `rt_lognormal(predict_outliers =
#' TRUE)`.
#'
#' The flag is carried on the model rather than passed as an argument for a
#' reason. `brms` sends the `...` of `posterior_predict()` and
#' `posterior_epred()` to `prepare_predictions()`, not down to the family method;
#' `posterior_epred` reaches the family method with `prep` and nothing else. So
#' `posterior_epred(m, predict_outliers = TRUE)` is *silently ignored* rather
#' than erroring, and `insight`, `modelbased` and `marginaleffects` inherit that
#' behaviour. Carrying the flag on the object is what makes it work everywhere.
#'
#' The `predict_outliers` argument on the methods themselves still works when
#' they are called directly, and overrides the flag.
#'
#' `log_lik` has no such argument: the likelihood *is* the mixture, and dropping
#' a component from it would not be a different summary of the same model but a
#' different model. One consequence is that `posterior_predict()` and `log_lik()`
#' do not describe the same distribution by default. This also desyncs
#' `loo_pit()`, `loo_predict()` and `bayes_R2()` from `loo()`, not just
#' hand-rolled checks - anything that compares a simulated replicate against the
#' likelihood should be run on [with_outliers()].
#'
#' @param n Number of observations. If `length(n) > 1`, the length is taken to be
#'   the number required.
#' @param mu Mean of the decision time on the log scale (`meanlog`). Can take any
#'   real value. Range: (-Inf, Inf).
#' @param sigma SD of the decision time on the log scale (`sdlog`). Must be
#'   positive. Range: (0, Inf).
#' @param ndt Non-decision time (shift parameter), in seconds. Must be
#'   non-negative. Represents time for processes such as stimulus encoding and
#'   response execution. Range: [0, Inf).
#' @param poutlier Proportion of responses generated by the outlier process
#'   rather than by the decision process. Range: `[0, 1]`. At `poutlier = 0` the
#'   distribution reduces to the plain shifted LogNormal.
#' @param minrt Fastest reaction time that could plausibly be a real decision,
#'   in the same unit as the data. Used directly as the scale of the outlier
#'   component. A judgement about the task rather than a statistic: it is a
#'   constant, never estimated, is not read off the sample, and does not bound
#'   `ndt`. Defaults to `0.3`; change it for data that are not in seconds. See
#'   Details.
#'
#' @examples
#' # Simulate 1000 RTs with 2% outliers
#' rts <- rrt_lognormal(1000, mu = -0.7, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' # hist(rts, breaks = 100, main = "Simulated shifted LogNormal RTs", xlab = "RT (s)")
#'
#' # Responses faster than ndt have positive density, unlike the unmixed model
#' drt_lognormal(0.1, ndt = 0.3, poutlier = 0.02)
#' drt_lognormal(0.1, ndt = 0.3, poutlier = 0)
#'
#' # Setting minrt in the unit of the data makes the density equivariant to it
#' drt_lognormal(1, mu = -0.7, sigma = 0.5, ndt = 0.3, poutlier = 0.02)
#' 1000 * drt_lognormal(1000,
#'   mu = -0.7 + log(1000), sigma = 0.5, ndt = 300,
#'   poutlier = 0.02, minrt = 300
#' )
#'
#' # Density of the outlier component alone
#' # curve(2 * dt(x / 0.3, df = 3) / 0.3, from = 0, to = 3, n = 1000)
#'
#' @export
rrt_lognormal <- function(
  n,
  mu = -0.7,
  sigma = 0.5,
  ndt = 0.2,
  poutlier = 0,
  minrt = 0.3
) {
  # Prepare and validate all inputs for RNG
  params <- .prepare_rt_lognormal(
    x = NULL,
    n = n,
    mu = mu,
    sigma = sigma,
    ndt = ndt,
    poutlier = poutlier
  )
  m <- params$ndraws

  # Draw the mixture indicator, then the corresponding component
  is_out <- stats::runif(m) < params$poutlier
  out <- numeric(m)

  if (any(is_out)) {
    out[is_out] <- abs(
      .validate_minrt(minrt) * stats::rt(sum(is_out), df = .POUTLIER_DF)
    )
  }
  if (any(!is_out)) {
    keep <- !is_out
    out[keep] <- stats::rlnorm(
      sum(keep),
      meanlog = params$mu[keep],
      sdlog = params$sigma[keep]
    ) + params$ndt[keep]
  }
  out
}


#' @rdname rrt_lognormal
#' @param x Vector of quantiles (observed reaction times).
#' @param log Logical; if TRUE, probabilities p are given as log(p).
#' @export
drt_lognormal <- function(
  x,
  mu = -0.7,
  sigma = 0.5,
  ndt = 0.2,
  poutlier = 0,
  minrt = 0.3,
  log = FALSE
) {
  # Prepare and validate inputs for density. Invalid parameter values give a
  # zero density rather than an error, so that the function can be applied
  # across posterior draws without a single bad draw aborting the call.
  params <- tryCatch(
    .prepare_rt_lognormal(
      x = x,
      n = NULL,
      mu = mu,
      sigma = sigma,
      ndt = ndt,
      poutlier = poutlier
    ),
    error = function(e) {
      warning(conditionMessage(e), ". Returning 0 density / -Inf log-density.")
      list(ndraws = length(x), error = TRUE)
    }
  )
  if (!is.null(params$error)) {
    return(rep(ifelse(log, -Inf, 0), params$ndraws))
  }

  # Outlier component: supported over the whole positive line
  lp_out <- .dcontam(params$x, minrt = minrt, log = TRUE)

  # Decision component: zero density at or below ndt
  x_adj <- params$x - params$ndt
  lp_dec <- ifelse(
    x_adj > 0,
    stats::dlnorm(
      pmax(x_adj, 1e-300),
      meanlog = params$mu,
      sdlog = params$sigma,
      log = TRUE
    ),
    -Inf
  )

  log_density <- .log_mix(params$poutlier, lp_out, lp_dec)
  log_density[is.na(log_density)] <- -Inf

  if (log) {
    log_density
  } else {
    exp(log_density)
  }
}


# Internals ---------------------------------------------------------------

# The outlier component is a half Student-t on [0, Inf) with `.POUTLIER_DF`
# degrees of freedom and scale `minrt`.
#
# The half-t is flat at the origin (zero derivative), which matters: the fastest
# responses are the ones least likely to be decisions, so the component must not
# thin out there. A LogNormal or Gamma vanishes at 0 and an Exponential peaks
# there with maximal slope; all three get this wrong. df = 3 keeps the tails
# heavy while keeping the mean finite for posterior_epred().
.POUTLIER_DF <- 3

# `minrt` is used directly as the half-t scale, with no conversion factor. That
# fixes the component's shape relative to it: 61% of the mass falls below
# `minrt`, and the density there is still 66% of its peak, whatever value is
# supplied. Tying the scale to a quantity in the same unit as the data is what
# makes the likelihood equivariant to that unit.
#
# Raising it makes `poutlier` claim more of the body and the slow tail; lowering
# it much below 0.25 s stops the component covering contaminants that land near
# `ndt`, and `ndt` gets noisier. `ndt` itself is insensitive across the whole
# usable range.
#' @keywords internal
.validate_minrt <- function(minrt = 0.3) {
  if (!is.numeric(minrt) || length(minrt) != 1 || is.na(minrt) ||
    minrt <= 0) {
    stop("`minrt` must be a single positive number.", call. = FALSE)
  }
  minrt
}

# Read `minrt` off a family, a brmsprep or a brmsfit, falling back to the
# default for models fitted before it was adjustable.
#' @keywords internal
.minrt <- function(x) {
  m <- x$family$minrt
  if (is.null(m)) eval(formals(.validate_minrt)$minrt) else m
}

# Density of the half-t component.
#' @keywords internal
.dcontam <- function(x, minrt = 0.3, log = FALSE) {
  s <- .validate_minrt(minrt)
  ld <- log(2) + stats::dt(x / s, df = .POUTLIER_DF, log = TRUE) - log(s)
  ld[x <= 0] <- -Inf
  if (log) ld else exp(ld)
}

# Mean of the half-t; finite for df > 1.
#' @keywords internal
.mcontam <- function(minrt = 0.3) {
  nu <- .POUTLIER_DF
  2 * .validate_minrt(minrt) * sqrt(nu) * gamma((nu + 1) / 2) /
    (sqrt(pi) * (nu - 1) * gamma(nu / 2))
}


#' @keywords internal
.prepare_rt_lognormal <- function(x = NULL, n = NULL, mu, sigma, ndt, poutlier) {
  # --- Basic Validation ---
  if (any(sigma <= 0, na.rm = TRUE)) stop("`sigma` must be positive.")
  if (any(ndt < 0, na.rm = TRUE)) stop("`ndt` must be non-negative.")
  if (any(poutlier < 0 | poutlier > 1, na.rm = TRUE)) {
    stop("`poutlier` must be in [0, 1].")
  }
  # mu can be any real number, no check needed.

  # --- Determine Target Length ---
  if (!is.null(x)) {
    # For Density (drt_lognormal)
    m <- max(length(x), length(mu), length(sigma), length(ndt), length(poutlier))
    if (m == 0) stop("At least one input vector must have non-zero length.")
  } else if (!is.null(n)) {
    # For RNG (rrt_lognormal)
    if (length(n) > 1) n <- length(n)
    if (length(n) != 1 || n < 0 || n != floor(n)) {
      stop("n must be a single non-negative integer.")
    }
    m <- max(n, length(mu), length(sigma), length(ndt), length(poutlier))
    if (n == 0) m <- 0
  } else {
    stop("Either 'x' or 'n' must be provided.")
  }

  # --- Recycle Parameters ---
  params <- list(
    mu = rep_len(mu, m),
    sigma = rep_len(sigma, m),
    ndt = rep_len(ndt, m),
    poutlier = rep_len(poutlier, m)
  )
  if (!is.null(x)) params$x <- rep_len(x, m)

  params$ndraws <- m
  params
}
