<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dominique Makowski">
<meta name="keywords" content="cognitive modelling, Bayesian statistics, reaction times, evidence accumulation, subjective ratings, computational neuropsychology, R">
<meta name="description" content="THE COGMOD R PACKAGE">

<title>The cogmod R Package: Easy-to-Use Bayesian Cognitive Models for Reaction Times, Choices and Subjective Ratings, with Applications to Computational Neuropsychology</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="paper_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="paper_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="paper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_files/libs/bootstrap/bootstrap-15f85eb00547d308b9628b46447080fb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="_extensions/apaquarto/apa.css">
</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#firstheader" id="toc-firstheader" class="nav-link active" data-scroll-target="#firstheader">The cogmod R Package: Easy-to-Use Bayesian Cognitive Models for Reaction Times, Choices and Subjective Ratings, with Applications to Computational Neuropsychology</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#traditional-models-can-be-misleading" id="toc-traditional-models-can-be-misleading" class="nav-link" data-scroll-target="#traditional-models-can-be-misleading">Traditional models can be misleading</a></li>
  <li><a href="#from-means-to-mechanisms" id="toc-from-means-to-mechanisms" class="nav-link" data-scroll-target="#from-means-to-mechanisms">From means to mechanisms</a></li>
  <li><a href="#the-obstacle-is-practical" id="toc-the-obstacle-is-practical" class="nav-link" data-scroll-target="#the-obstacle-is-practical">The obstacle is practical</a></li>
  </ul></li>
  <li><a href="#design-and-implementation" id="toc-design-and-implementation" class="nav-link" data-scroll-target="#design-and-implementation">Design and Implementation</a>
  <ul class="collapse">
  <li><a href="#models-as-brms-custom-families" id="toc-models-as-brms-custom-families" class="nav-link" data-scroll-target="#models-as-brms-custom-families">Models as <code>brms</code> custom families</a></li>
  <li><a href="#relation-to-existing-software" id="toc-relation-to-existing-software" class="nav-link" data-scroll-target="#relation-to-existing-software">Relation to existing software</a></li>
  </ul></li>
  <li><a href="#example-1-five-decision-models-one-workflow" id="toc-example-1-five-decision-models-one-workflow" class="nav-link" data-scroll-target="#example-1-five-decision-models-one-workflow">Example 1: Five Decision Models, One Workflow</a>
  <ul class="collapse">
  <li><a href="#four-more-architectures" id="toc-four-more-architectures" class="nav-link" data-scroll-target="#four-more-architectures">Four more architectures</a></li>
  <li><a href="#the-comparison-as-a-diagnosis" id="toc-the-comparison-as-a-diagnosis" class="nav-link" data-scroll-target="#the-comparison-as-a-diagnosis">The comparison as a diagnosis</a></li>
  <li><a href="#what-the-architectures-cost" id="toc-what-the-architectures-cost" class="nav-link" data-scroll-target="#what-the-architectures-cost">What the architectures cost</a></li>
  </ul></li>
  <li><a href="#example-2-reaction-times-without-choices" id="toc-example-2-reaction-times-without-choices" class="nav-link" data-scroll-target="#example-2-reaction-times-without-choices">Example 2: Reaction Times Without Choices</a>
  <ul class="collapse">
  <li><a href="#from-a-mean-to-a-shape" id="toc-from-a-mean-to-a-shape" class="nav-link" data-scroll-target="#from-a-mean-to-a-shape">From a mean to a shape</a></li>
  <li><a href="#sixteen-families-one-call" id="toc-sixteen-families-one-call" class="nav-link" data-scroll-target="#sixteen-families-one-call">Sixteen families, one call</a></li>
  <li><a href="#from-a-group-effect-to-an-individual-score" id="toc-from-a-group-effect-to-an-individual-score" class="nav-link" data-scroll-target="#from-a-group-effect-to-an-individual-score">From a group effect to an individual score</a>
  <ul class="collapse">
  <li><a href="#fitting-and-reading-the-model" id="toc-fitting-and-reading-the-model" class="nav-link" data-scroll-target="#fitting-and-reading-the-model">Fitting and reading the model</a></li>
  <li><a href="#quantifying-it" id="toc-quantifying-it" class="nav-link" data-scroll-target="#quantifying-it">Quantifying it</a></li>
  </ul></li>
  <li><a href="#a-clinical-reanalysis" id="toc-a-clinical-reanalysis" class="nav-link" data-scroll-target="#a-clinical-reanalysis">A clinical reanalysis</a>
  <ul class="collapse">
  <li><a href="#what-the-conventional-analysis-finds" id="toc-what-the-conventional-analysis-finds" class="nav-link" data-scroll-target="#what-the-conventional-analysis-finds">What the conventional analysis finds</a></li>
  <li><a href="#what-the-model-finds" id="toc-what-the-model-finds" class="nav-link" data-scroll-target="#what-the-model-finds">What the model finds</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#example-3-the-same-interface-for-subjective-ratings" id="toc-example-3-the-same-interface-for-subjective-ratings" class="nav-link" data-scroll-target="#example-3-the-same-interface-for-subjective-ratings">Example 3: The Same Interface for Subjective Ratings</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#computational-neuropsychology" id="toc-computational-neuropsychology" class="nav-link" data-scroll-target="#computational-neuropsychology">Computational neuropsychology</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#open-practices-statement" id="toc-open-practices-statement" class="nav-link" data-scroll-target="#open-practices-statement">Open Practices Statement</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></li><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>Typst (apaquarto)</a></li><li><a href="paper.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<!-- This file is intentionally empty. The APA title page for HTML output
     is generated by frontmatter.lua. Do not add content here — it would
     override the Lua-generated title block. -->


<br>

<br>

<section id="title" class="level1 title unnumbered unlisted">
<h1 class="title unnumbered unlisted">The cogmod R Package: Easy-to-Use Bayesian Cognitive Models for Reaction Times, Choices and Subjective Ratings, with Applications to Computational Neuropsychology</h1>
<div class="Author">
<br>

<p>Dominique Makowski</p>
<p>School of Psychology, University of Sussex</p>
<p>Sussex Centre for Consciousness Science, University of Sussex</p>
<p><em>D.Makowski@sussex.ac.uk</em></p>
</div>
<br>

<br>

</section>
<section id="author-note" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Author Note</h1>
<p>Dominique Makowski <img src="_extensions/apaquarto/ORCID-iD_icon-vector.svg" id="orcid" class="img-fluid" style="width:4.23mm" alt="Orcid ID Logo: A green circle with white letters ID"> <a href="https://orcid.org/0000-0001-5375-9967">https://orcid.org/0000-0001-5375-9967</a></p>
<p>Correspondence concerning this article should be addressed to Dominique Makowski, School of Psychology, University of Sussex, Brighton BN1 9RH, UK, Email: <a href="mailto:D.Makowski@sussex.ac.uk">D.Makowski@sussex.ac.uk</a></p>
<br>
</section>
<section id="abstract" class="level1 unnumbered unlisted AuthorNote">
<h1 class="unnumbered unlisted AuthorNote">Abstract</h1>
<div class="AbstractFirstParagraph">
<p>Cognitive tasks yield far more information than the condition means that dominate published analyses. Descriptive distributional families such as the ex-Gaussian, and process models such as the Drift Diffusion Model, both recover structure that a mean difference discards. Adoption remains limited, and the obstacle is practical: each model family lives in its own package, with its own syntax, its own parameterization and its own output objects. Families are therefore rarely compared, and cognitive modelling sits apart from the regression workflow psychologists already use. We introduce <code>cogmod</code>, an R package implementing a growing collection of such models as <code>brms</code> custom families. Models are specified with ordinary <code>brms</code> formula syntax; any parameter (drift rate, boundary separation, non-decision time, dispersion, precision) can be predicted by covariates and given random effects; and the fitted object is a standard <code>brmsfit</code>, supporting the usual priors, diagnostics, posterior predictive checks, leave-one-out cross-validation and <code>easystats</code> post-processing. Three worked examples, one per family of models, use simulated, laboratory and clinical data. Five evidence accumulation architectures are fitted to the same choices and reaction times, compared in a single call, and the misfit of the simplest one traced to a specific missing parameter. Sixteen reaction time families are then compared with the choice discarded, before the same likelihood is used to ask whether its parameters are precise enough to serve as individual-level scores, and to reanalyse a task-switching dataset in which the conventional executive-control index does not separate ADHD participants from controls at all, while the model localises the group difference in two components that cancel at the level of the mean. A third example reaches bounded rating scales through the same interface. <code>cogmod</code> is openly available at <a href="https://github.com/DominiqueMakowski/cogmod" class="uri">https://github.com/DominiqueMakowski/cogmod</a>.</p>
</div>
<p><em>Keywords</em>: cognitive modelling, Bayesian statistics, reaction times, evidence accumulation, subjective ratings, computational neuropsychology, R</p>
<br>
</section>
<section id="firstheader" class="level1 title unnumbered">
<h1 class="title unnumbered">The cogmod R Package: Easy-to-Use Bayesian Cognitive Models for Reaction Times, Choices and Subjective Ratings, with Applications to Computational Neuropsychology</h1>
<!-- ==========================================================================
     REFERENCE PAPERS - for writing style, structure and framing
     ==========================================================================

     TARGET JOURNAL
     Behavior Research Methods (Springer). Chief editors: Erin M. Buchanan,
     Dora Matzke.  https://link.springer.com/journal/13428
     Note: Dora Matzke is a co-author of the EMC2 paper below. Frame cogmod as 
     complementary, not as a replacement.

     --------------------------------------------------------------------------
     PRIMARY TEMPLATE - closest thing to this paper, in the target journal
     --------------------------------------------------------------------------
     Stevenson, Donzallaz, Innes, Forstmann, Matzke & Heathcote (2026).
       Bayesian hierarchical cognitive modeling with the EMC2 package. BRM.
       https://doi.org/10.3758/s13428-025-02869-y
       Docs: https://ampl-psych.github.io/EMC2/
       WHAT TO BORROW: the paper is organised around a *workflow* (design ->
       Bayesian specification -> sampling -> diagnostics/evaluation ->
       inference) rather than around a list of models. Their "design phase"
       pitch - bridging standard regression and cognitive modelling via
       linear-model specifications for cognitive parameters - is very close to
       our own argument, so our differentiation has to be explicit and
       generous: they own the sampler and the accumulator architectures, we own
       the general-purpose regression interface and the descriptive-to-
       generative continuum (RTs AND ratings in one framework).

     Heathcote, Lin, Reynolds, Strickland, Gretton & Matzke (2019).
       Dynamic models of choice. BRM, 51, 961-985.
       https://doi.org/10.3758/s13428-018-1067-y
       WHAT TO BORROW: how much tutorial-level detail a BRM software paper is
       allowed to carry, and how to present a model zoo without it reading as
       a catalogue.

     --------------------------------------------------------------------------
     OWN PAPERS - for voice and for the "package paper" format
     --------------------------------------------------------------------------
     Makowski, Pham, Lau, Brammer, Lespinasse, Pham, Scholzel & Chen (2021).
       NeuroKit2: A Python toolbox for neurophysiological signal processing.
       Behavior Research Methods, 53(4), 1689-1696.
       https://doi.org/10.3758/s13428-020-01516-y
       <- own paper, same journal: the closest model for tone and length.

     Fisher & Makowski (2024). SequentialSamplingModels.jl.
       Proceedings of JuliaCon. https://doi.org/10.21105/jcon.00186

     Makowski, Ben-Shachar, Wiernik, Patil, Theriault & Ludecke (2025).
       modelbased: An R package to make the most out of your statistical
       models... JOSS, 10(109), 7969. https://doi.org/10.21105/joss.07969
     Makowski, Ben-Shachar & Ludecke (2019). bayestestR. JOSS, 4(40), 1541.
       https://doi.org/10.21105/joss.01541
     Ludecke, Ben-Shachar, Patil, Waggoner & Makowski (2021). performance.
       JOSS, 6(60), 3139. https://doi.org/10.21105/joss.03139
     Ludecke, Waggoner & Makowski (2019). insight. JOSS, 4(38), 1412.
       https://doi.org/10.21105/joss.01412
       <- JOSS format is much shorter and differently structured; use these for
          voice only, not for structure.

     Makowski, Ben-Shachar, Chen & Ludecke (2019). Indices of effect existence
       and significance in the Bayesian framework. Frontiers in Psychology, 10,
       2767. https://doi.org/10.3389/fpsyg.2019.02767
       <- own non-JOSS methods paper: useful model for how to argue a
          methodological point at length with simulations.

     --------------------------------------------------------------------------
     OTHER GOOD PACKAGE PAPERS IN NON-JOSS JOURNALS
     --------------------------------------------------------------------------
     Burkner (2017). brms. J. Stat. Software, 80(1).
       https://doi.org/10.18637/jss.v080.i01
     Burkner (2018). Advanced Bayesian multilevel modeling with brms.
       R Journal, 10(1), 395-411. https://doi.org/10.32614/RJ-2018-017
       <- the custom-family / distributional-regression framing we build on.
     Wiecki, Sofer & Frank (2013). HDDM. Front. Neuroinformatics, 7, 14.
       https://doi.org/10.3389/fninf.2013.00014
     Voss & Voss (2007). Fast-dm. BRM, 39(4), 767-775.
       https://doi.org/10.3758/BF03192967
     Vandekerckhove & Tuerlinckx (2008). DMAT primer. BRM, 40(1), 61-72.
       https://doi.org/10.3758/BRM.40.1.61
     Shinn, Lam & Murray (2020). PyDDM. eLife, 9, e56938.
       https://doi.org/10.7554/eLife.56938
     Ahn, Haines & Zhang (2017). hBayesDM. Computational Psychiatry, 1, 24-57.
       https://doi.org/10.1162/CPSY_a_00002
     Peirce et al. (2019). PsychoPy2. BRM, 51, 195-203.
       https://doi.org/10.3758/s13428-018-01193-y
     de Leeuw (2015). jsPsych. BRM, 47, 1-12.
       https://doi.org/10.3758/s13428-014-0458-y
     Mathot, Schreij & Theeuwes (2012). OpenSesame. BRM, 44, 314-324.
       https://doi.org/10.3758/s13428-011-0168-7
       <- the last three are BRM's house style for tool papers: short intro,
          heavy on worked examples, explicit about limitations.

     --------------------------------------------------------------------------
     METHODOLOGICAL FRAMING
     --------------------------------------------------------------------------
     Hedge, Powell & Sumner (2018). The reliability paradox. BRM, 50, 1166-1186.
       https://doi.org/10.3758/s13428-017-0935-1
     Burkner & Vuorre (2019). Ordinal regression models in psychology: A
       tutorial. AMPPS, 2(1), 77-101.
       https://doi.org/10.1177/2515245918823199
     Kubinec (2023). Ordered beta regression. Political Analysis, 31(4).
       https://doi.org/10.1017/pan.2022.20

     NOTE: DOIs above were assembled from search results and should be
     spot-checked before submission.
     ========================================================================== -->
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="traditional-models-can-be-misleading" class="level2">
<h2 data-anchor-id="traditional-models-can-be-misleading">Traditional models can be misleading</h2>
<p>Consider a dataset of reaction times (RTs) from 20 participants tested under two experimental conditions (25 trials each), available in <code>cogmod</code>. A traditional approach would involve fitting a linear mixed model testing the effect of condition, with participants entered as random intercepts:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lmer</span>(RT <span class="sc">~</span> Condition <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant), </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">data =</span> cogmod<span class="sc">::</span>badlm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>It finds no significant difference (<span class="math inline">b = -0.001</span>, <span class="math inline">t(996) = -0.08</span>, <span class="math inline">p = .94</span>; <a href="#fig-motivation" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> B), which one could misleadingly report as an absence of any difference in the RTs of the two conditions. Yet the two distributions could hardly be more different (<a href="#fig-motivation" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> A): condition A produces a lot of very fast and very slow responses, whereas condition B yields much more consistent RTs. But because the mean of their distribution is similar, the analysis does not capture any other differences. The problem is not the design, the data preprocessing, the random-effect structure or the post-processing, but the model itself: linear regressions estimate means and nothing else. Simply changing the model to use another distribution, such as ex-Gaussian, drastically changes the conclusions that can be drawn from the same data, revealing significant differences in the bulk of the distribution, its spread and its tail (<a href="#fig-motivation" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a> C). Despite the massive benefits we can get from using more appropriate models, they are rarely used in practice, which is what the <code>cogmod</code> package aims to address.</p>
<div id="fig-motivation" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" data-fig-align="center" prefix="" data-fignum="1" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-motivation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Simulated reaction times from two experimental conditions, available in the <code>cogmod</code> package. <strong>(A)</strong> Observed distributions; dashed lines mark the condition means. <strong>(B, C)</strong> The effect of condition as each model reports it, with 95% intervals; green marks an interval excluding zero, red one that does not. The linear mixed model has only a mean to report, and finds no effect in it. The ex-Gaussian splits the same data into a Gaussian bulk (<span class="math inline">\mu</span>), its spread (<span class="math inline">\sigma</span>) and an exponential tail (<span class="math inline">\tau</span>), and finds an effect on all three; because its mean is <span class="math inline">\mu + \tau</span>, the opposing effects on bulk and tail cancel into exactly the null of panel B.</p>
</div>
</figcaption>
<div aria-describedby="fig-motivation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_motivation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:85.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
</section>
<section id="from-means-to-mechanisms" class="level2">
<h2 data-anchor-id="from-means-to-mechanisms">From means to mechanisms</h2>
<p>Cognitive tasks yield complex data, resulting from a sequence of processes that unfold over time. Some responses come almost immediately, some follow a lapse of attention, some reflect an unusually cautious pass over the stimulus, and some are emitted before the evidence has really been weighed. The shape of the distribution, its mode, its spread and its tail, is where the underlying processes leave their trace. Most published analyses reduce all of it to a handful of condition means and test for their difference. That reduction is itself a modelling decision, and a costly one: most of what makes cognitive data distinctive is discarded in the process.</p>
<!-- Transforming the outcome is the usual first response to this, and it does -->
<!-- not help. Log- or inverse-transforming RTs before fitting a linear model -->
<!-- changes the quantity being tested: the model then compares means of -->
<!-- transformed values, which do not back-transform to mean RTs and can -->
<!-- reverse, create or mask effects relative to the untransformed scale -->
<!-- [@schramm2019transformations; see @liddell2018analyzing for the analogous -->
<!-- argument about ordinal data]. The underlying problem survives the -->
<!-- transformation anyway, since differences in shift, spread and tail weight -->
<!-- are still funnelled through a single location parameter. -->
<p>The traditional summary-statistics approach involving <em>t</em>-tests, ANOVAs, linear regressions, treats observations as Normally distributed around a predicted mean (<a href="#fig-approaches" class="quarto-xref" aria-expanded="false">Figure&nbsp;2</a>). Two alternatives can be distinguished from it. The <strong>distributional</strong> approach chooses a likelihood that matches the shape of the outcome, such as an ex-Gaussian or shifted LogNormal for reaction times <span class="citation" data-cites="matzke2009psychological balota2011moving">(<a href="#ref-balota2011moving" role="doc-biblioref">Balota &amp; Yap, 2011</a>; RTs, <a href="#ref-matzke2009psychological" role="doc-biblioref">Matzke &amp; Wagenmakers, 2009</a>)</span>, or an ordered Beta for bounded ratings <span class="citation" data-cites="kubinec2023ordered">(<a href="#ref-kubinec2023ordered" role="doc-biblioref">Kubinec, 2023</a>)</span>, so that skew, boundedness and dispersion are described rather than ignored. The <strong>computational</strong> approach goes further and derives the likelihood from an account of the process that generated the data. Evidence accumulation models (EAMs, or sequential sampling models) treat response times as the first-passage times of a noisy accumulation towards a decision boundary, and their parameters map onto theoretically distinct components of the decision: the quality of the evidence, how much of it is required before committing, and the time spent encoding the stimulus and executing the response <span class="citation" data-cites="ratcliff2008diffusion brown2008simplest">(<a href="#ref-brown2008simplest" role="doc-biblioref">Brown &amp; Heathcote, 2008</a>; <a href="#ref-ratcliff2008diffusion" role="doc-biblioref">Ratcliff &amp; McKoon, 2008</a>)</span>.</p>
<div id="fig-approaches" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" prefix="" data-fignum="2" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-approaches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>The three approaches applied to the same trials: correct responses from three participants in the lexical decision data of <span class="citation" data-cites="wagenmakers2008diffusion">Wagenmakers et al. (<a href="#ref-wagenmakers2008diffusion" role="doc-biblioref">2008</a>)</span>, used again in Examples 1 and 2. Observed reaction times are on the left; each row then shows what one model is made of and the distribution that follows from it, drawn back over the same data. The 141 ms difference between instruction conditions is first a single number, then a shift plus a shorter tail, then a statement about how evidence was accumulated. The ex-Gaussian and shifted Wald curves both use the posterior means reported in Example 2.</p>
</div>
</figcaption>
<div aria-describedby="fig-approaches-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_approaches.png" class="img-fluid figure-img" style="width:100.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>The case for moving past the first approach is well supported. Distributional analyses recover effects that mean comparisons miss and disambiguate effects that mean comparisons conflate <span class="citation" data-cites="balota2011moving deboeck2019overview">(<a href="#ref-balota2011moving" role="doc-biblioref">Balota &amp; Yap, 2011</a>; <a href="#ref-deboeck2019overview" role="doc-biblioref">De Boeck &amp; Jeon, 2019</a>)</span>. Process models turn an experimental effect into a statement about <em>which component of processing changed</em>, which is what most cognitive-theoretical claims are about <span class="citation" data-cites="ratcliff2016diffusion evans2020evidence">(<a href="#ref-evans2020evidence" role="doc-biblioref">Evans &amp; Wagenmakers, 2020</a>; <a href="#ref-ratcliff2016diffusion" role="doc-biblioref">Ratcliff et al., 2016</a>)</span>. Model-based parameters are also more reliable than the difference scores traditionally computed from the same data, making them one of the more promising responses to the “reliability paradox” <span class="citation" data-cites="hedge2018reliability haines2020learning">(<a href="#ref-haines2020learning" role="doc-biblioref">Haines et al., 2020</a>; <a href="#ref-hedge2018reliability" role="doc-biblioref">Hedge et al., 2018</a>)</span>.</p>
</div>
<p>The gap between what a task produces and what is taken from it is widest in neuropsychological assessment, which rests almost entirely on cognitive tasks. The indices extracted from them are total scores, completion times and differences between condition means: quantities inherited for historical rather than theoretical reasons, with no principled mapping onto the constructs they are said to measure <span class="citation" data-cites="ratcliff2022neuropsychological">(<a href="#ref-ratcliff2022neuropsychological" role="doc-biblioref">Ratcliff &amp; McKoon, 2022</a>)</span>. Older adults, for instance, are reliably slower, but a meta-analysis of diffusion model analyses locates the general age effect on boundary separation and non-decision time, with drift rate differences that are task-dependent and occasionally reversed <span class="citation" data-cites="theisen2021age">(<a href="#ref-theisen2021age" role="doc-biblioref">Theisen et al., 2021</a>)</span>. A latency difference reported as “cognitive slowing” would be more accurately framed as a statement about caution or motor execution. Computational neuropsychology <span class="citation" data-cites="steinke2020computational">(<a href="#ref-steinke2020computational" role="doc-biblioref">Steinke &amp; Kopp, 2020</a>)</span> proposes to keep the tasks and replace those scores with parameters that refer to identifiable components of processing, so that a deficit is characterized rather than merely detected.</p>
<p>The same holds for brain-behaviour correlations, a field burdened by weak associations and low reliability. Brain-wide association studies based on basic behavioural indices (such as mean RTs) need thousands of participants before their effects replicate <span class="citation" data-cites="marek2022reproducible">(<a href="#ref-marek2022reproducible" role="doc-biblioref">Marek et al., 2022</a>)</span>, and the test-retest reliability of common task-fMRI measures is typically low <span class="citation" data-cites="elliott2020test">(<a href="#ref-elliott2020test" role="doc-biblioref">Elliott et al., 2020</a>)</span>. In contrast, parameters derived from cognitive models are more reliable <span class="citation" data-cites="haines2020learning rouder2024signal">(<a href="#ref-haines2020learning" role="doc-biblioref">Haines et al., 2020</a>; <a href="#ref-rouder2024signal" role="doc-biblioref">Rouder &amp; Mehrvarz, 2024</a>)</span> and closer to what a neural account is about. The threshold adjustment made under time pressure is a case in point: it is a model parameter rather than an observable, and seems to accurately track striatal and pre-supplementary motor activation, and cortico-striatal connection strength, across individuals <span class="citation" data-cites="forstmann2008striatum forstmann2016sequential wiecki2015modelbased">(<a href="#ref-forstmann2008striatum" role="doc-biblioref">Forstmann et al., 2008</a>, <a href="#ref-forstmann2016sequential" role="doc-biblioref">2016</a>; <a href="#ref-wiecki2015modelbased" role="doc-biblioref">Wiecki et al., 2015</a>)</span>. Whether the target is a clinical score or a brain-behaviour correlation, the root cause is the same: we only get what we fit, and fitting means with linear models is a self-imposed limitation.</p>
</section>
<section id="the-obstacle-is-practical" class="level2">
<h2 data-anchor-id="the-obstacle-is-practical">The obstacle is practical</h2>
<p>Uptake of alternative approaches remains unfortunately modest, and the obstacle is mostly practical. The software landscape for fitting alternative models is fragmented. Diffusion models are fitted in HDDM or HSSM in Python <span class="citation" data-cites="wiecki2013hddm fengler2026hssm">(<a href="#ref-fengler2026hssm" role="doc-biblioref">Fengler et al., 2026</a>; <a href="#ref-wiecki2013hddm" role="doc-biblioref">Wiecki et al., 2013</a>)</span>, in fast-dm <span class="citation" data-cites="voss2007fastdm">(<a href="#ref-voss2007fastdm" role="doc-biblioref">Voss &amp; Voss, 2007</a>)</span>, in DMAT <span class="citation" data-cites="vandekerckhove2008diffusion">(<a href="#ref-vandekerckhove2008diffusion" role="doc-biblioref">Vandekerckhove &amp; Tuerlinckx, 2008</a>)</span>, or in PyDDM <span class="citation" data-cites="shinn2020flexible">(<a href="#ref-shinn2020flexible" role="doc-biblioref">Shinn et al., 2020</a>)</span>; racing accumulator models in DMC and EMC2 in R <span class="citation" data-cites="heathcote2019dynamic stevenson2026bayesian">(<a href="#ref-heathcote2019dynamic" role="doc-biblioref">Heathcote et al., 2019</a>; <a href="#ref-stevenson2026bayesian" role="doc-biblioref">Stevenson et al., 2026</a>)</span>, or with <code>SequentialSamplingModels.jl</code> in Julia <span class="citation" data-cites="fisher2024sequential">(<a href="#ref-fisher2024sequential" role="doc-biblioref">Fisher &amp; Makowski, 2024</a>)</span>; bounded and ordinal responses in yet another set, such as <code>ordbetareg</code> <span class="citation" data-cites="kubinec2025ordbetareg">(<a href="#ref-kubinec2025ordbetareg" role="doc-biblioref">Kubinec, 2025</a>)</span>. Each toolbox has its own syntax for specifying which parameters depend on which conditions, its own parameterizations, defaults, and its own output objects.</p>
<p>As a consequence, comparing families is difficult and therefore rare. Deciding between an ex-Gaussian and a shifted LogNormal, or asking whether a Weibull distribution would do as well as either, means re-fitting in different packages under different conventions, which slows exploratory work and leaves the choice of likelihood to be inherited from disciplinary convention rather than tested against the data at hand. Second, these toolboxes often sit apart from the regression workflow psychologists already use, such as <code>brms</code> in R <span class="citation" data-cites="burkner2017brms">(<a href="#ref-burkner2017brms" role="doc-biblioref">Bürkner, 2017</a>)</span>, which means missing on the expressive power of that workflow. Every design has to be restated in a toolbox-specific syntax, and features like complex random effects specifications, smooth terms, monotonic effects for ordinal predictors, or post-processing tools, such as marginal effects and means, are effectively out of reach <span class="citation" data-cites="wood2017generalized burkner2018advanced">(<a href="#ref-burkner2018advanced" role="doc-biblioref">Bürkner, 2018</a>; <a href="#ref-wood2017generalized" role="doc-biblioref">Wood, 2017</a>)</span>.</p>
<p><code>cogmod</code> aims to address these limitations by facilitting the application of these models inside a framework researchers already use. Every model is defined as a <code>brms</code> custom family <span class="citation" data-cites="burkner2017brms">(<a href="#ref-burkner2017brms" role="doc-biblioref">Bürkner, 2017</a>)</span>, and therefore a Stan model <span class="citation" data-cites="carpenter2017stan">(<a href="#ref-carpenter2017stan" role="doc-biblioref">B. Carpenter et al., 2017</a>)</span> specified with ordinary <code>brms</code> formula syntax. Everything a <code>brms</code> user already knows then applies unchanged to a Drift Diffusion Model or an ordered-Beta rating model: distributional regression on every parameter, multilevel structure, priors, convergence diagnostics, posterior predictive checks, leave-one-out cross-validation <span class="citation" data-cites="vehtari2017practical">(<a href="#ref-vehtari2017practical" role="doc-biblioref">Vehtari et al., 2017</a>)</span>. The <code>easystats</code> ecosystem <span class="citation" data-cites="ludecke2019insight makowski2019bayestestr ludecke2021performance">(<a href="#ref-ludecke2019insight" role="doc-biblioref">Lüdecke et al., 2019</a>, <a href="#ref-ludecke2021performance" role="doc-biblioref">2021</a>; <a href="#ref-makowski2019bayestestr" role="doc-biblioref">Makowski et al., 2019</a>)</span> has been adapted to accommodate these families, providing first-rate post-processing tools.</p>
<p>We describe below the design of the package and the models it provides, then give three worked examples, one per family of models, to illustrate the workflow and applications.</p>
</section>
</section>
<section id="design-and-implementation" class="level1">
<h1>Design and Implementation</h1>
<section id="models-as-brms-custom-families" class="level2">
<h2 data-anchor-id="models-as-brms-custom-families">Models as <code>brms</code> custom families</h2>
<p><code>brms</code> translates an R formula into Stan code. Its <em>custom family</em> mechanism allows users to supply their own likelihood: a <code>customfamily</code> object declaring the distributional parameters and their link functions, plus a <code>stanvars</code> object injecting the Stan functions that evaluate the log-density. <code>cogmod</code> packages both for each model, and additionally provides the post-processing methods (<code>log_lik_*</code>, <code>posterior_predict_*</code> and <code>posterior_epred_*</code>) that <code>brms</code> requires in order to compute information criteria and generate predictions used in post-processing.</p>
<p>In practice, using a <code>cogmod</code> model requires two arguments beyond a standard <code>brm()</code> call: <code>family</code> and <code>stanvars</code>. Two further helpers, <code>cogmod_priors()</code> and <code>cogmod_inits()</code>, are strictly speaking optional but should be treated as part of the call: the families carry parameters measured in seconds and parameters that <code>brms</code> cannot recognise by name, and the outlier mixture described below has a degenerate mode that a prior has to fence off. Everything in the package is stated in <strong>seconds</strong>, and nothing rescales itself, so RTs in milliseconds must be divided by 1000 before fitting.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cogmod)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the formula using brms' bf()</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  RT <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  sigma <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  ndt <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  poutlier <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">cogmod_lognormal</span>()</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  f,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">prior =</span> <span class="fu">cogmod_priors</span>(f, df),</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">init =</span> <span class="fu">cogmod_inits</span>(f, df),</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">stanvars =</span> <span class="fu">cogmod_stanvars</span>(f),</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">backend =</span> <span class="st">"cmdstanr"</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Everything else is <code>brms</code>. The formula syntax is the usual one, so any parameter can be predicted by covariates, given random effects, splines, autocorrelation structures or monotonic effects. The fitted object is a plain <code>brmsfit</code>, so <code>summary()</code>, <code>pp_check()</code>, <code>loo()</code>, <code>emmeans</code>, <code>bayesplot</code> and the <code>easystats</code> functions work out of the box.</p>
<p>Moreover, in most specialized software, the analyst declares which parameters are “free” and which are fixed, and condition effects enter through a toolbox-specific design matrix. Here, each distributional parameter is a regression target with its own formula. Testing the effect of a manipulation on various parameters becomes trivial, as is giving each participant their own parameters through random effects. This allows the location-scale modelling advocated by <span class="citation" data-cites="williams2021beneath">Williams et al. (<a href="#ref-williams2021beneath" role="doc-biblioref">2021</a>)</span>, in which the dispersion of a participant’s RTs is a person-specific quantity with its own predictors, to be the default rather than a special case.</p>
</section>
<section id="relation-to-existing-software" class="level2">
<h2 data-anchor-id="relation-to-existing-software">Relation to existing software</h2>
<p><a href="#fig-overview" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a> shows the families available at the time of writing. As adding a new model is a self-contained piece of work, the set is expected to grow to track cutting-edge advances in computational psychology. The package’s documentation website contains the list of available models, with each family’s distributional parameters, link functions and defaults, as well as hands-on tutorials. Because that set is still moving, the family constructors share a single <code>cogmod_*</code> naming scheme, and any name that has been retired remains available as an exact synonym so that existing scripts and stored fits keep working.</p>
<div id="fig-overview" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" prefix="" data-fignum="3" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Response formats covered by <code>cogmod</code> and the main families available for each at the time of writing; the package website carries the current list. Six further descriptive RT families are also available (<code>cogmod_weibull()</code>, <code>cogmod_logweibull()</code>, <code>cogmod_invweibull()</code>, <code>cogmod_gamma()</code>, <code>cogmod_invgamma()</code> and <code>cogmod_bisa()</code>) and are compared against the others in Example 2. Every family comes with a <code>_stanvars()</code> function supplying the corresponding Stan code, and with <code>d*()</code> and <code>r*()</code> functions for density evaluation and simulation.</p>
</div>
</figcaption>
<div aria-describedby="fig-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_overview.png" class="img-fluid figure-img" style="width:100.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p><code>cogmod</code> is not a replacement for the specialized evidence accumulation toolboxes, and the division of labour is worth stating. EMC2 <span class="citation" data-cites="stevenson2026bayesian">(<a href="#ref-stevenson2026bayesian" role="doc-biblioref">Stevenson et al., 2026</a>)</span> and HSSM <span class="citation" data-cites="fengler2026hssm">(<a href="#ref-fengler2026hssm" role="doc-biblioref">Fengler et al., 2026</a>)</span> provide sampling algorithms tailored to the geometry of accumulator models, hierarchical structures designed for them and, in HSSM’s case, likelihood approximation networks that make otherwise intractable variants estimable. For a study whose scientific question <em>is</em> the architecture of the decision process, those are the right tools, and they will be faster and more capable at the far end of model complexity.</p>
</div>
<p><code>cogmod</code> targets a different (and arguably more common) situation: a researcher with an experimental dataset, a regression-shaped question and a need for a likelihood that respects the data. For that user the relevant comparison is between a linear model and something better, not between one accumulator toolbox and another. Moving from <code>brm(RT ~ Condition)</code> to a shifted LogNormal or a Wald model means changing two arguments rather than changing software, and at every step the analysis remains a regression, with random effects, contrasts and marginal means available as usual.</p>
</section>
</section>
<section id="example-1-five-decision-models-one-workflow" class="level1">
<h1>Example 1: Five Decision Models, One Workflow</h1>
<p>To illustrate the typical workflow of fitting evidence accumulation models, we will fit them to the lexical decision task data of <span class="citation" data-cites="wagenmakers2008diffusion">Wagenmakers et al. (<a href="#ref-wagenmakers2008diffusion" role="doc-biblioref">2008</a>)</span> (Experiment 1), distributed in the <code>rtdists</code> package as <code>speed_acc</code>: participants classified letter strings as words or non-words under instructions emphasising either <strong>speed</strong> or <strong>accuracy</strong>. Responses slower than 2 s were excluded. This example uses three participants (<span class="math inline">n = 4{,}620</span> trials, 7.3% of them errors), pooled without random effects for clarity - a simplification we return to at the end of the section.</p>
<p>In order to fit a basic Drift Diffusion Model (DDM) in <code>cogmod</code>, one needs to specify 1) a formula for each of the parameters, 2) the model family (<code>cogmod_ddm()</code>) and attach the custom family Stan code with <code>cogmod_stanvars()</code>. As it is common in the field, the “decision” being modelled is <strong>correct vs.&nbsp;error</strong>, which is added to the formula with a <code>dec()</code> term on the response side of the formula. Everything else is the ordinary <code>brms</code> syntax:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(speed_acc, <span class="at">package =</span> <span class="st">"rtdists"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Condition =</span> <span class="fu">unname</span>(<span class="fu">c</span>(<span class="at">accuracy =</span> <span class="st">"Accuracy"</span>, <span class="at">speed =</span> <span class="st">"Speed"</span>)[</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.character</span>(speed_acc<span class="sc">$</span>condition)]),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">RT =</span> speed_acc<span class="sc">$</span>rt,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Error =</span> <span class="fu">as.integer</span>(<span class="fu">as.character</span>(speed_acc<span class="sc">$</span>response) <span class="sc">!=</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">as.character</span>(speed_acc<span class="sc">$</span>stim_cat)),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Participant =</span> <span class="fu">as.integer</span>(<span class="fu">as.character</span>(speed_acc<span class="sc">$</span>id))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[df<span class="sc">$</span>Participant <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>) <span class="sc">&amp;</span> df<span class="sc">$</span>RT <span class="sc">&lt;=</span> <span class="dv">2</span>, ]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  RT <span class="sc">|</span> <span class="fu">dec</span>(Error) <span class="sc">~</span> Condition,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  boundary <span class="sc">~</span> Condition,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  bias <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  ndt <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  poutlier <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">sigmadrift =</span> <span class="dv">0</span>, <span class="at">sigmabias =</span> <span class="dv">0</span>, <span class="at">sigmandt =</span> <span class="dv">0</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">cogmod_ddm</span>()</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>m_ddm <span class="ot">&lt;-</span> <span class="fu">brm</span>(f, <span class="at">data =</span> df,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">prior =</span> <span class="fu">cogmod_priors</span>(f, df),</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">init =</span> <span class="fu">cogmod_inits</span>(f, df),</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">stanvars =</span> <span class="fu">cogmod_stanvars</span>(f)) <span class="sc">|&gt;</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_criterion</span>(<span class="st">"loo"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The first unnamed parameter, referred to as <code>mu</code> in the Stan code as per <code>brms</code> convention, actually corresponds to the drift rate. The other parameters correspond to boundary separation (<code>boundary</code>), starting point bias (<code>bias</code>), and non-decision time (<code>ndt</code>), respectively. Estimating non-decision time is a common source of difficulty in fitting diffusion models: a shifted distribution assigns zero density to any response faster than <code>ndt</code>, which puts a hard wall in the likelihood at the fastest observed response. Every family that carries an <code>ndt</code> therefore mixes in a small contaminant component, of weight <code>poutlier</code>, that keeps early responses at positive density. The wall becomes a finite cost, and <code>ndt</code> is estimated directly in seconds rather than relative to a sample statistic. The contaminant is a half Normal with a fixed scale of 0.2 s, deliberately lighter-tailed than any decision density in the package: a heavier component eventually explains slow responses better than the model does, and drags <code>ndt</code> up behind it. Two helpers make the mixture inspectable rather than merely assumed - <code>p_outlier()</code> returns each trial’s posterior probability of having come from the contaminant, and <code>with_outliers()</code> switches predictions between the decision process alone and the fitted mixture. On these data the mechanism is visible trial by trial: of the 4,285 correct responses modelled in Example 2, the four faster than 200 ms are assigned to the contaminant with probability 1.00, the response at 329 ms with probability 0.51, and by 353 ms the probability is 0.008, against a mean of 0.0015 across all trials. The model discriminates by evidence rather than by a cutoff, which is what having the component buys over trimming the same trials by hand. Not every family is built this way, and the distinction follows the parameter: the descriptive <code>cogmod_exgaussian()</code> of Example 2 has neither <code>ndt</code> nor <code>poutlier</code>, since its exponential component already absorbs the shift, and nor do the rating families of Example 3.</p>
<p>The three <code>sigma*</code> arguments fix the between-trial variabilities of the full seven-parameter diffusion model <span class="citation" data-cites="ratcliff2008diffusion">(<a href="#ref-ratcliff2008diffusion" role="doc-biblioref">Ratcliff &amp; McKoon, 2008</a>)</span> at zero, giving the “simple” four-parameter DDM, which is a common simplification, since the variability parameters are expensive to sample and notoriously hard to recover <span class="citation" data-cites="boehm2018estimating">(<a href="#ref-boehm2018estimating" role="doc-biblioref">Boehm et al., 2018</a>)</span>. Setting them to exactly zero is also cheaper than a prior concentrated near zero, because the Stan code falls back to a dedicated density rather than to numerical quadrature. The effect of <code>Condition</code> is also estimated for the boundary separation, which is the textbook hypothesis for a speed-accuracy manipulation, and the results support it: boundary separation drops sharply under speed instructions (95% CI on the linear predictor <span class="math inline">[-0.65, -0.55]</span>). The drift rate also falls, by a smaller and less certain amount (<span class="math inline">-0.17</span>, 95% CI <span class="math inline">[-0.29, -0.04]</span>), which is not what the textbook account predicts; with three participants pooled and no random effects, some of that is likely to be between-participant differences with nowhere else to go.</p>
<section id="four-more-architectures" class="level2">
<h2 data-anchor-id="four-more-architectures">Four more architectures</h2>
<p>Whether that is the right model, however, is a separate question, and answering it means fitting the alternatives, which only involves a few code changes: a different <code>family</code>, its <code>stanvars</code>, and whichever distributional parameters that family owns. The <strong>DDM-5</strong> is the model above with between-trial variability in drift rate freed (<code>sigmadrift ~ 1</code>). The <strong>LogNormal race</strong> <span class="citation" data-cites="rouder2015lognormal">(LNR, <a href="#ref-rouder2015lognormal" role="doc-biblioref">Rouder et al., 2015</a>)</span>, the <strong>linear ballistic accumulator</strong> <span class="citation" data-cites="brown2008simplest">(LBA, <a href="#ref-brown2008simplest" role="doc-biblioref">Brown &amp; Heathcote, 2008</a>)</span> and the <strong>racing diffusion model</strong> <span class="citation" data-cites="tillman2020sequential">(RDM, <a href="#ref-tillman2020sequential" role="doc-biblioref">Tillman et al., 2020</a>)</span> replace the single diffusion with two accumulators racing towards a threshold, and differ in how each accumulator gets there: by drawing its finishing time from a LogNormal, by accumulating linearly with between-trial variability in its rate, or by diffusing with within-trial noise alone. In the last two, the start-point range and the threshold increment enter the likelihood only through their sum, so <code>sigmabias</code> needs either a weakly informative prior or to be pinned at zero; <code>cogmod_priors()</code> supplies the former, and the safer habit when a threshold is to be interpreted is to read <code>boundary + sigmabias</code> rather than either alone.</p>
<p>Because each fit is a <code>brmsfit</code> carrying a <code>loo</code> criterion, comparing the five is one call:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">loo_compare</span>(m_ddm, m_ddm5, m_lnr,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>            m_lba, m_rdm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-eam" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" data-tblnum="1" data-apa-twocolumn="true" prefix="" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-eam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Leave-one-out cross-validation for five evidence accumulation models fitted to the choices and reaction times of three participants (<span class="math inline">n = 4{,}620</span>). ENP is the effective number of parameters; Difference is the difference in expected log predictive density relative to the best model, with its standard error. Time is the median sampling duration per chain (4 chains, 500 iterations, on a consumer laptop). All Pareto <span class="math inline">k</span> values are below 0.5, so the estimates are reliable.</p>
</div>
</figcaption>
<div aria-describedby="tbl-eam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-eam" class="caption-top table" prefix="" data-tblnum="1">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">LOOIC</th>
<th style="text-align: right;">ENP</th>
<th style="text-align: right;">ELPD</th>
<th style="text-align: right;">Difference</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Time (s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LBA</td>
<td style="text-align: right;">−2657.7</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">1328.9</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">665.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">LNR</td>
<td style="text-align: right;">−2633.0</td>
<td style="text-align: right;">9.86</td>
<td style="text-align: right;">1316.5</td>
<td style="text-align: right;">−12.3</td>
<td style="text-align: right;">10.1</td>
<td style="text-align: right;">69.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DDM-5</td>
<td style="text-align: right;">−2507.3</td>
<td style="text-align: right;">10.74</td>
<td style="text-align: right;">1253.7</td>
<td style="text-align: right;">−75.2</td>
<td style="text-align: right;">17.3</td>
<td style="text-align: right;">484.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">DDM</td>
<td style="text-align: right;">−2436.3</td>
<td style="text-align: right;">10.70</td>
<td style="text-align: right;">1218.2</td>
<td style="text-align: right;">−110.7</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">241.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RDM</td>
<td style="text-align: right;">−2419.4</td>
<td style="text-align: right;">6.96</td>
<td style="text-align: right;">1209.7</td>
<td style="text-align: right;">−119.2</td>
<td style="text-align: right;">18.1</td>
<td style="text-align: right;">806.9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="the-comparison-as-a-diagnosis" class="level2">
<h2 data-anchor-id="the-comparison-as-a-diagnosis">The comparison as a diagnosis</h2>
<p>The ranking in <a href="#tbl-eam" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> is three participants’ worth of evidence and is not the point. What the comparison is <em>for</em> is visible in the simple DDM, 111 ELPD points behind the best model. It carries exactly the mechanism the manipulation is believed to act on, <code>Condition</code> on the boundary separation, and it recovered the expected effect; the two models that clearly outpredict it have no threshold parameter free to move at all. Its deficit lies on an axis nobody was testing, and a posterior predictive check locates it (<a href="#fig-eam" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a> A): the model puts its error distribution to the left of the observed errors. In the upper half of the same panel all five models are close, which is the part worth remembering: a model’s problem can be invisible if one only looks at the RTs of correct responses.</p>
<div id="fig-eam" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" prefix="" data-fignum="4" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-eam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Five evidence accumulation models fitted to the choices and reaction times of three participants. <strong>(A)</strong> Posterior predictive check: observed trials as histograms, 100 predictive draws per model as faint lines and their pooled density in bold, with correct responses drawn upwards and errors downwards. Both halves are scaled by the <em>proportion</em> of that response, so the area under each curve is its predicted frequency and the check is on the joint distribution of choices and RTs. Draws are taken with <code>with_outliers()</code>, so the check is on the same mixture the likelihood scores. <strong>(B)</strong> The same check reduced to one statistic per draw, the predicted difference between the mean error RT and the mean correct RT, against the value observed in the data. <strong>(C)</strong> Predictive accuracy against sampling cost. Predicted RTs above 3 s (0.05% of draws, produced by near-zero drift rates in the races) are excluded from panels A and B.</p>
</div>
</figcaption>
<div aria-describedby="fig-eam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_eam.png" class="img-fluid figure-img" style="width:100.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Reduced to a single statistic (<a href="#fig-eam" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a> B), the DDM predicts errors 100 ms <em>faster</em> than correct responses (95% CI <span class="math inline">[-119, -79]</span>) against an observed <span class="math inline">-15</span> ms: the direction is right, the magnitude is not. Errors that are barely faster than correct responses, at an unchanged leading edge, are the signature of between-trial variability in drift rate: errors are then contributed disproportionately by the trials that happened to draw a low drift, which lengthens the error tail without moving its onset <span class="citation" data-cites="ratcliff2008diffusion">(<a href="#ref-ratcliff2008diffusion" role="doc-biblioref">Ratcliff &amp; McKoon, 2008</a>)</span>. That is precisely the parameter DDM-5 frees, and freeing it is worth 36 ELPD points and closes about a third of the gap on the statistic (<span class="math inline">-64</span> ms, <span class="math inline">[-95, -30]</span>). The races need no such parameter, since each already carries a separate drift rate for the error accumulator.</p>
</div>
<p>The complication is worth stating rather than smoothing over: the model that matches this particular statistic best is the RDM (<span class="math inline">-7</span> ms, <span class="math inline">[-27, +14]</span>), and the RDM is last in <a href="#tbl-eam" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a>. A predictive check on one statistic and a global measure of predictive fit are answering different questions, and they need not agree. What the check buys is not a ranking but a <em>direction</em> - it says which parameter is missing, which the LOOIC column alone never does.</p>
<p>The lesson is therefore about diagnosis rather than about which family wins. A poor fit had an identifiable cause, the cause pointed at one parameter, and freeing that parameter improved both the fit and the statistic — with the comparison, the predictive check and the re-fit in one session and one syntax. The alternative arrangement, in which each architecture lives in its own package, does not forbid this sequence so much as make it unlikely to be attempted.</p>
</section>
<section id="what-the-architectures-cost" class="level2">
<h2 data-anchor-id="what-the-architectures-cost">What the architectures cost</h2>
<p><a href="#fig-eam" class="quarto-xref" aria-expanded="false">Figure&nbsp;4</a> C reports the other half of the decision, and it does not rank the models the same way. The LBA is nominally best and takes 665 seconds per chain; the LNR is 12 ELPD points behind it (SE 10.1) at 70 seconds, nearly ten times cheaper — a difference well within noise for a tenth of the cost, which on these data makes the LNR the sensible default. Freeing drift variability is not free either: DDM-5 costs twice the simple DDM. On three participants these are minutes; multiplied by a hierarchical model over a full sample, they are the difference between an afternoon and a week, and this is the boundary at which the specialized samplers of EMC2 <span class="citation" data-cites="stevenson2026bayesian">(<a href="#ref-stevenson2026bayesian" role="doc-biblioref">Stevenson et al., 2026</a>)</span> and HSSM <span class="citation" data-cites="fengler2026hssm">(<a href="#ref-fengler2026hssm" role="doc-biblioref">Fengler et al., 2026</a>)</span> earn their place.</p>
<p>Two caveats bound the example. Errors are rare here (335 trials), so the between-trial variability parameters are weakly identified and the comparison of the two DDMs is correspondingly soft; and three participants pooled without random effects, fitted with short chains, is a demonstration rather than a result. Example 2 returns to what that pooling costs.</p>
</section>
</section>
<section id="example-2-reaction-times-without-choices" class="level1">
<h1>Example 2: Reaction Times Without Choices</h1>
<p>Many datasets carry no informative choice. Accuracy is at ceiling, the task has one response, or errors are too few to estimate anything from — which is the usual situation in the clinical instruments this example ends on. What is left is a duration, and the question becomes which distribution to give it. We keep the same trials as Example 1, now dropping the 335 errors and modelling the correct responses of the same three participants (<span class="math inline">n = 4{,}285</span>).</p>
<section id="from-a-mean-to-a-shape" class="level2">
<h2 data-anchor-id="from-a-mean-to-a-shape">From a mean to a shape</h2>
<p>A Gaussian model gives the familiar answer: responses were 141 ms faster under speed instructions (95% CI <span class="math inline">[129, 152]</span>). Moving to a likelihood built for the shape of reaction times costs one changed argument and two extra formulas:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(RT <span class="sc">~</span> Condition,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>        sigma <span class="sc">~</span> Condition,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        tau <span class="sc">~</span> Condition,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">family =</span> <span class="fu">cogmod_exgaussian</span>())</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">brm</span>(f, <span class="at">data =</span> df,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">prior =</span> <span class="fu">cogmod_priors</span>(f, df),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">init =</span> <span class="fu">cogmod_inits</span>(f, df),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">stanvars =</span> <span class="fu">cogmod_stanvars</span>(f))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The three parameters reproduce the Gaussian estimate exactly (<span class="math inline">476 + 213 = 689</span> ms under accuracy instructions, <span class="math inline">429 + 120 = 549</span> ms under speed), but they attribute it: <strong>67% of the 141 ms speed-up is a shortening of the tail</strong>, only 33% a shift in the bulk. A speed instruction does not move every response earlier; it removes the slow ones. That is the whole argument of the distributional approach in one comparison, and it costs nothing to run.</p>
<p>Note that <code>mu</code> here is in seconds directly. It is the <em>location</em> of the Gaussian component rather than a scale, so it sits on an <code>identity</code> link and is free to go negative - which for fast, heavily-tailed data is sometimes where it belongs, with <code>tau</code> carrying the mass. Constraining it positive, as <code>cogmod</code> once did, distorts exactly the <code>mu</code>/<code>tau</code> split that makes the decomposition above worth reporting.</p>
</section>
<section id="sixteen-families-one-call" class="level2">
<h2 data-anchor-id="sixteen-families-one-call">Sixteen families, one call</h2>
<p>The ex-Gaussian is a choice among many, and because every <code>cogmod</code> model is a <code>brmsfit</code>, deciding between them is the ordinary <code>loo</code> workflow <span class="citation" data-cites="vehtari2017practical">(<a href="#ref-vehtari2017practical" role="doc-biblioref">Vehtari et al., 2017</a>)</span> rather than a bespoke one. Each fit is the same few lines with a different family, and the comparison is a single call:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m_exgaussian <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bf</span>(RT <span class="sc">~</span> Condition, sigma <span class="sc">~</span> Condition, tau <span class="sc">~</span> Condition,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">family =</span> <span class="fu">cogmod_exgaussian</span>()),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df, <span class="at">stanvars =</span> <span class="fu">cogmod_stanvars</span>(f)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">add_criterion</span>(<span class="st">"loo"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># the other fifteen differ only in `family` and which distributional</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters exist to receive `Condition`</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">loo_compare</span>(m_gaussian, m_exgaussian, m_lognormal, m_wald, m_lba, ...)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-loo" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" data-tblnum="2" data-apa-twocolumn="true" prefix="" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-loo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Leave-one-out cross-validation for sixteen RT families fitted to the same data (<span class="math inline">n = 4{,}285</span>). The LBA here is <code>cogmod_lba1()</code>, the single-accumulator variant that predicts a duration only, not the racing model of <a href="#tbl-eam" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a>; the recinormal is that same family with <code>sigmabias = 0</code>. ENP is the effective number of parameters; Difference is the difference in expected log predictive density relative to the best model, with its standard error. Time is the median sampling duration per chain (4 chains, 500 iterations, on a consumer laptop). Three families - the ex-Gaussian, the Gamma and the Weibull - have at least one Pareto <span class="math inline">k</span> above 0.7, so their positions are approximate and, on the evidence of the diagnostic, optimistic.</p>
</div>
</figcaption>
<div aria-describedby="tbl-loo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-loo" class="caption-top table" prefix="" data-tblnum="2">
<colgroup>
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 23%">
<col style="width: 7%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">LOOIC</th>
<th style="text-align: right;">ENP</th>
<th style="text-align: right;">ELPD</th>
<th style="text-align: right;">Difference</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">Time (s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Log-Student</td>
<td style="text-align: right;">−4801.1</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">2400.5</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">101.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wald + drift variability</td>
<td style="text-align: right;">−4796.6</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">2398.3</td>
<td style="text-align: right;">−2.2</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">579.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LogGamma</td>
<td style="text-align: right;">−4795.0</td>
<td style="text-align: right;">7.37</td>
<td style="text-align: right;">2397.5</td>
<td style="text-align: right;">−3.0</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">225.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inverse Gamma</td>
<td style="text-align: right;">−4792.0</td>
<td style="text-align: right;">6.84</td>
<td style="text-align: right;">2396.0</td>
<td style="text-align: right;">−4.5</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">143.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Single-accumulator LBA</td>
<td style="text-align: right;">−4789.7</td>
<td style="text-align: right;">8.07</td>
<td style="text-align: right;">2394.8</td>
<td style="text-align: right;">−5.7</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">370.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recinormal (LATER)</td>
<td style="text-align: right;">−4783.4</td>
<td style="text-align: right;">6.07</td>
<td style="text-align: right;">2391.7</td>
<td style="text-align: right;">−8.8</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">199.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LogWeibull</td>
<td style="text-align: right;">−4772.7</td>
<td style="text-align: right;">5.41</td>
<td style="text-align: right;">2386.4</td>
<td style="text-align: right;">−14.2</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">75.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inverse Weibull</td>
<td style="text-align: right;">−4772.5</td>
<td style="text-align: right;">5.24</td>
<td style="text-align: right;">2386.3</td>
<td style="text-align: right;">−14.3</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">93.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shifted LogNormal</td>
<td style="text-align: right;">−4763.3</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">2381.6</td>
<td style="text-align: right;">−18.9</td>
<td style="text-align: right;">6.7</td>
<td style="text-align: right;">35.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ex-Wald</td>
<td style="text-align: right;">−4744.8</td>
<td style="text-align: right;">9.69</td>
<td style="text-align: right;">2372.4</td>
<td style="text-align: right;">−28.1</td>
<td style="text-align: right;">8.6</td>
<td style="text-align: right;">941.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shifted Wald</td>
<td style="text-align: right;">−4723.5</td>
<td style="text-align: right;">9.35</td>
<td style="text-align: right;">2361.7</td>
<td style="text-align: right;">−38.8</td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">78.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Birnbaum–Saunders</td>
<td style="text-align: right;">−4703.4</td>
<td style="text-align: right;">10.22</td>
<td style="text-align: right;">2351.7</td>
<td style="text-align: right;">−48.8</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">56.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ExGaussian</td>
<td style="text-align: right;">−4607.9</td>
<td style="text-align: right;">13.45</td>
<td style="text-align: right;">2304.0</td>
<td style="text-align: right;">−96.6</td>
<td style="text-align: right;">31.6</td>
<td style="text-align: right;">41.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gamma</td>
<td style="text-align: right;">−4569.6</td>
<td style="text-align: right;">11.85</td>
<td style="text-align: right;">2284.8</td>
<td style="text-align: right;">−115.8</td>
<td style="text-align: right;">18.6</td>
<td style="text-align: right;">118.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weibull</td>
<td style="text-align: right;">−4292.3</td>
<td style="text-align: right;">25.96</td>
<td style="text-align: right;">2146.2</td>
<td style="text-align: right;">−254.4</td>
<td style="text-align: right;">27.7</td>
<td style="text-align: right;">1267.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gaussian</td>
<td style="text-align: right;">−1888.8</td>
<td style="text-align: right;">7.18</td>
<td style="text-align: right;">944.4</td>
<td style="text-align: right;">−1456.1</td>
<td style="text-align: right;">73.8</td>
<td style="text-align: right;">&lt;0.1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>The ranking itself is one dataset’s worth of evidence and is not the point. What matters is that three questions become answerable in an afternoon that would otherwise each require a separate toolchain: whether the Gaussian default is defensible (it is worse than the next-worst family by 1,202 units of expected log predictive density); whether the families the literature settled on are the right ones (four of the top five are the log-Student, the log-Gamma, the inverse Gamma and the single-accumulator LBA, none with any appreciable presence in the RT literature, while the ex-Gaussian - one of the two most reported families in the field - sits fourth from bottom); and what the better fits cost (the ex-Wald <span class="citation" data-cites="schwarz2001ex">(<a href="#ref-schwarz2001ex" role="doc-biblioref">Schwarz, 2001</a>)</span> takes 942 seconds per chain and is outpredicted by the log-Student at a ninth of that, while the shifted LogNormal reaches ninth place in 36 seconds). The last of these is a column in <a href="#tbl-loo" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a> rather than an inference the reader must assemble across papers.</p>
</div>
<p>The two nested pairs in the table are worth a second look, because they are the kind of comparison this arrangement makes cheap. Freeing between-trial variability in drift rate moves the Wald from 38.8 points behind to 2.2 (<code>sigmadrift</code>, the RT-only counterpart of the DDM-5 of Example 1), and pinning the LBA’s start-point range at zero - which gives the recinormal, or LATER model of <span class="citation" data-cites="carpenter1995neural">R. H. S. Carpenter and Williams (<a href="#ref-carpenter1995neural" role="doc-biblioref">1995</a>)</span> - costs 3.1 points and cuts the sampling time nearly in half. Both are one edited argument, and both are like-for-like: the nested model shares its likelihood with the general one.</p>
<p>As in Example 1, <em>where</em> a model fails is the more informative question, and the posterior predictive checks that answer it come out of the same call as for any <code>brmsfit</code>, since <code>cogmod</code> supplies <code>posterior_predict_*</code> methods for every family — <code>modelbased::estimate_prediction()</code> returns draws ready for plotting <span class="citation" data-cites="makowski2020modelbased">(<a href="#ref-makowski2020modelbased" role="doc-biblioref">Makowski et al., 2020</a>)</span>. <a href="#fig-ppcheck" class="quarto-xref" aria-expanded="false">Figure&nbsp;5</a> shows all sixteen families over the observed distributions: the Gaussian, the Weibull and the Gamma, which the table places far behind, miss the peak and the tail in visibly different ways, while the families at the top of the table are hard to tell apart by eye.</p>
<div id="fig-ppcheck" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" prefix="" data-fignum="5" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ppcheck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;5</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>The sixteen families of <a href="#tbl-loo" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a>, fitted to the same 4,285 trials and drawn back over them. Histograms are the observed RTs in the two instruction conditions; lines are posterior predictive draws. InvGaussian is the shifted Wald, ReciNormal the LATER model, and Wald-4 the Wald with between-trial drift variability freed. Reproduced from the package’s <em>RT-only Models</em> vignette, which works through the families one by one.</p>
</div>
</figcaption>
<div aria-describedby="fig-ppcheck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_ppcheck.png" class="img-fluid figure-img" style="width:100.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Three caveats apply to reading the table. These models pool three participants without random effects, so families that absorb between-participant heterogeneity more gracefully are advantaged; a hierarchical comparison is easy to specify but expensive to fit. The three families flagged in the caption for high Pareto <span class="math inline">k</span> are exactly the ones whose predictive draws sit worst over the data, which is what a failing importance-sampling diagnostic usually means - their positions should be read as upper bounds. And LOO measures predictive fit, not theoretical adequacy. The plain shifted Wald sits eleventh of sixteen, below six purely descriptive families, while being one of the five in the table whose parameters refer to a process — and even its parameters have to be read with care here. Placing <code>Condition</code> on its boundary separation, the textbook hypothesis for a speed-accuracy manipulation, returns the opposite of the textbook account: a large increase in drift rate under speed instructions (2.67 to 3.83) and no change in boundary separation (95% CI on the linear predictor <span class="math inline">[-0.27, 0.13]</span>). That is a limitation of the model rather than a discovery about the data. A single-boundary Wald sees only correct responses, and with RTs alone drift rate and boundary separation are weakly identified and trade off against each other <span class="citation" data-cites="matzke2009psychological">(<a href="#ref-matzke2009psychological" role="doc-biblioref">Matzke &amp; Wagenmakers, 2009</a>)</span>. Fixing one of the two is the usual remedy; the other is to give the model the errors as well, which is what Example 1 did.</p>
</div>
</section>
<section id="from-a-group-effect-to-an-individual-score" class="level2">
<h2 data-anchor-id="from-a-group-effect-to-an-individual-score">From a group effect to an individual score</h2>
<p>A significant group-level effect and a usable individual-level measure are different things, and a study designed to establish the first can be blind to the second <span class="citation" data-cites="hedge2018reliability">(<a href="#ref-hedge2018reliability" role="doc-biblioref">Hedge et al., 2018</a>)</span>. The distinction is decisive for neuropsychology and for differential research, where the point of a task is to produce a number that characterises a <em>person</em>, and where a task is often adopted on the strength of a group effect alone. The families just compared are the ones such a task would use, and the question is whether their parameters survive the move from the group to the individual.</p>
<p>We simulated the validation study such a task would need: 30 participants, 80 trials in each of three conditions, RTs generated from a shifted LogNormal process. Two effects were built in deliberately. Condition B produces a small slowing that is nearly identical for everybody (between-participant SD of 0.01 on the log scale). Condition C has a population mean of exactly zero but enormous interindividual variability (SD of 0.30): some participants dramatically slowed, others dramatically speeded.</p>
<section id="fitting-and-reading-the-model" class="level3">
<h3 data-anchor-id="fitting-and-reading-the-model">Fitting and reading the model</h3>
<p>The model mirrors the generative process, with random effects on every parameter of the family:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  RT <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  sigma <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  ndt <span class="sc">~</span> Condition <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    (Condition <span class="sc">|</span> Participant),</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">cogmod_lognormal</span>()</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The fixed effects reproduce the classic conclusion: a credible effect of condition B (<span class="math inline">b = 0.10</span>, 95% CI <span class="math inline">[0.04, 0.17]</span>, <span class="math inline">pd = 99.8\%</span>) and nothing for condition C (<span class="math inline">b = -0.02</span>, 95% CI <span class="math inline">[-0.15, 0.10]</span>, <span class="math inline">pd = 63\%</span>). The random-effect SDs invert the picture: 0.01 for the condition B slope against 0.28 for the condition C slope, more than twenty times larger. The effect that “worked” is the one on which participants do not differ.</p>
<p>The contrast with the analysis one would normally run is instructive. Computing each participant’s mean RT difference by hand yields a between-participant SD of ~31 ms for B − A, though the data were generated with essentially no true variability; a bootstrap shows why, with a per-participant standard error of ~26 ms. By estimating between-participant variability and trial-level noise jointly, the model assigns that spread to the residual term where it belongs and recovers the true SD. This is the model-based counterpart of the noise correction reliability coefficients perform, applied participant by participant rather than to the group as a whole, and it is why model-based individual scores outperform difference scores, especially when participants contribute few, noisy or unbalanced numbers of trials <span class="citation" data-cites="haines2020learning rouder2024signal">(<a href="#ref-haines2020learning" role="doc-biblioref">Haines et al., 2020</a>; <a href="#ref-rouder2024signal" role="doc-biblioref">Rouder &amp; Mehrvarz, 2024</a>)</span>.</p>
</section>
<section id="quantifying-it" class="level3">
<h3 data-anchor-id="quantifying-it">Quantifying it</h3>
<p>Participant-level estimates are extracted with <code>modelbased::estimate_grouplevel()</code>, and their usability as individual scores can be summarised by the <strong>Variance-Over-Uncertainty Ratio</strong> (D-vour), implemented in <code>performance::performance_dvour()</code> <span class="citation" data-cites="ludecke2021performance">(<a href="#ref-ludecke2021performance" role="doc-biblioref">Lüdecke et al., 2021</a>)</span>:</p>
<p><span class="math display">
D_{\text{vour}} = \frac{\sigma_{\text{between}}^2}{\sigma_{\text{between}}^2 + \mu_{\text{within}}^2}
</span></p>
<p>where <span class="math inline">\sigma_{\text{between}}^2</span> is the observed variability of the participant-level estimates and <span class="math inline">\mu_{\text{within}}^2</span> their mean squared uncertainty. It is bounded in <span class="math inline">[0, 1]</span>, and values near 1 mean participants differ far more than we are uncertain about where each of them stands. It is close to an intraclass correlation, but its denominator uses the <em>uncertainty of the estimates</em> rather than the raw within-participant variance, so that, unlike an ICC, collecting more trials per participant increases it. It is also a normalized version of the signal-to-noise ratio advocated by <span class="citation" data-cites="rouder2024signal">Rouder and Mehrvarz (<a href="#ref-rouder2024signal" role="doc-biblioref">2024</a>)</span>. The two functions compose directly, so the whole check is <code>performance_dvour(estimate_grouplevel(m))</code>.</p>
<p><a href="#tbl-dvour" class="quarto-xref" aria-expanded="false">Table&nbsp;3</a> reports the result for every parameter of the model. The ordering is the expected one; the magnitudes are what matter. Condition C reaches 0.93 while condition B collapses to 0.07, far below the 0.58 the same index returns on the raw empirical difference scores, which still contain the trial noise the model has reassigned to the residual. Taken at face value, the empirical value would have marked condition B as borderline usable. The model says it carries no individual-level information at all.</p>
<div id="tbl-dvour" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" data-tblnum="3" prefix="" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dvour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>D-vour (Variance-Over-Uncertainty Ratio) for every parameter of the mixed shifted LogNormal model. Values above 0.75 indicate strong group-level differences; values around 0.5 call for caution; values below 0.5 indicate that measurement noise dominates. <code>estimate_grouplevel()</code> labels the <code>mu</code> block “conditional”, since it is the response formula; it is written as <code>mu</code> here to match the family’s parameter names.</p>
</div>
</figcaption>
<div aria-describedby="tbl-dvour-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-dvour" class="caption-top table" prefix="" data-tblnum="3">
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">D-vour</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>mu</code></td>
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>mu</code></td>
<td style="text-align: left;">ConditionC</td>
<td style="text-align: right;">0.93</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>mu</code></td>
<td style="text-align: left;">ConditionB</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ndt</code></td>
<td style="text-align: left;">ConditionC</td>
<td style="text-align: right;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ndt</code></td>
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>ndt</code></td>
<td style="text-align: left;">ConditionB</td>
<td style="text-align: right;">0.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>sigma</code></td>
<td style="text-align: left;">ConditionC</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sigma</code></td>
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">0.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>sigma</code></td>
<td style="text-align: left;">ConditionB</td>
<td style="text-align: right;">0.03</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Two features of this table generalise beyond the simulation. First, the most reliable individual-level quantity the task produces is the <code>mu</code> intercept (0.94) — <em>how fast each participant is overall</em>, which the experimental design treats as a nuisance to be subtracted away. That is the usual situation, not an artefact of this simulation. Second, because <code>sigma</code> and <code>ndt</code> carry their own predictors and random effects, they get their own reliability verdicts. Here all six are correctly near zero, since every participant was simulated with the same dispersion and the same non-decision time — a useful negative control. Real data often look different: RT variability can discriminate between individuals better than the mean does <span class="citation" data-cites="williams2021beneath">(<a href="#ref-williams2021beneath" role="doc-biblioref">Williams et al., 2021</a>)</span>, and non-decision time is a natural candidate for a stable person-specific quantity. Had those been the reliable components, the sensible clinical index would have been <code>sigma</code> or <code>ndt</code>, and not a condition contrast at all.</p>
</div>
<p>The recommendation is simple, and a multi-parameter framework is what makes it followable: <strong>compute a reliability index for every parameter intended for use as an individual-level score</strong>, and report it alongside the effect itself.</p>
</section>
</section>
<section id="a-clinical-reanalysis" class="level2">
<h2 data-anchor-id="a-clinical-reanalysis">A clinical reanalysis</h2>
<p>The data so far have been a laboratory experiment and a simulation. The case for computational neuropsychology, though, is a case about clinical data, where trials are few, samples are heterogeneous and the index being reported was fixed decades ago. The rest of this example is the same family — a shifted LogNormal with random effects — applied to such a dataset.</p>
<p>We use the UCLA Consortium for Neuropsychiatric Phenomics dataset <span class="citation" data-cites="poldrack2016phenome">(<a href="#ref-poldrack2016phenome" role="doc-biblioref">Poldrack et al., 2016</a>)</span>, openly available on OpenNeuro as <code>ds000030</code>, and take the task-switching data from the 42 participants diagnosed with ADHD and the 125 healthy controls who completed it. Participants classified a coloured shape by either its colour or its shape, with the relevant dimension cued on each trial and switching on a quarter of them. Keeping correct responses between 200 ms and 2 s leaves 14,543 trials, at most 96 per participant. That is a realistic clinical quantity, and far below what demonstrations of these models usually assume.</p>
<section id="what-the-conventional-analysis-finds" class="level3">
<h3 data-anchor-id="what-the-conventional-analysis-finds">What the conventional analysis finds</h3>
<p>The standard index for this task is the <strong>switch cost</strong>, the difference between a participant’s mean RT on switch and non-switch trials, read as a measure of executive control. It finds nothing. Controls average 111 ms and the ADHD group 113 ms, <span class="math inline">t(82) = -0.13</span>, <span class="math inline">p = .90</span>. A linear mixed model agrees: a large switch cost overall (<span class="math inline">b = 0.11</span> s, <span class="math inline">t = 13.3</span>, <span class="math inline">p &lt; .001</span>, so the manipulation worked), no group difference in it (<span class="math inline">p = .89</span>), and no reliable group difference in overall speed (<span class="math inline">p = .12</span>).</p>
<p>No other summary statistic rescues the analysis. Across participants the groups do not differ in mean RT (<span class="math inline">p = .16</span>), RT standard deviation (<span class="math inline">p = .21</span>), coefficient of variation (<span class="math inline">p = .96</span>), or the 10th and 90th percentiles of their RT distributions (<span class="math inline">p = .39</span> and <span class="math inline">p = .18</span>). The one index that does differ is the skewness of the RT distribution (<span class="math inline">p = .02</span>), which is not a quantity anyone reports. On the conventional reading, this task detects no deficit in this sample.</p>
</section>
<section id="what-the-model-finds" class="level3">
<h3 data-anchor-id="what-the-model-finds">What the model finds</h3>
<p>We fitted a shifted LogNormal in which diagnosis and switching predict the location, the dispersion and the non-decision time, with random effects by participant:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  RT <span class="sc">~</span> Diagnosis <span class="sc">*</span> Switching <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    (Switching <span class="sc">|</span> Participant),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  sigma <span class="sc">~</span> Diagnosis <span class="sc">*</span> Switching <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> Participant),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  ndt <span class="sc">~</span> Diagnosis <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  poutlier <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="fu">cogmod_lognormal</span>()</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The model agrees about the switch cost: the interaction is null on the location (<span class="math inline">pd = 83\%</span>) and on the dispersion (<span class="math inline">pd = 59\%</span>). The conventional analysis was right about the question it asked. But diagnosis registers on all three parameters at once, and in opposing directions. On the response scale (<a href="#fig-adhd" class="quarto-xref" aria-expanded="false">Figure&nbsp;6</a>), the ADHD group’s decision component is <strong>96 ms slower</strong> (95% CI <span class="math inline">[26, 178]</span>, <span class="math inline">pd = 99.7\%</span>), their non-decision time is <strong>48 ms faster</strong> (<span class="math inline">[-75, -16]</span>, <span class="math inline">pd = 99.9\%</span>), and their log-scale dispersion is lower (<span class="math inline">pd = 96\%</span>). The two effects largely cancel, leaving a total mean difference of 49 ms that still straddles zero (<span class="math inline">[-17, 124]</span>, <span class="math inline">pd = 92\%</span>) — the null the <em>t</em>-test reported, arrived at from two credible components pointing opposite ways.</p>
<div id="fig-adhd" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" prefix="" data-fignum="6" data-apa-twocolumn="true" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-adhd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Figure&nbsp;6</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>The same task-switching data under two analyses (42 ADHD, 125 controls, 14,543 trials). <strong>(A)</strong> Per-participant switch costs, the conventional executive-control index, which does not separate the groups. <strong>(B)</strong> The RT distributions the index is computed from. <strong>(C)</strong> Posterior distributions of the group difference under the shifted LogNormal, on the response scale. The total mean difference straddles zero, but it is the sum of a slower decision component and a faster non-decision component, each credibly non-zero.</p>
</div>
</figcaption>
<div aria-describedby="fig-adhd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_adhd.png" class="img-fluid figure-img" style="width:100.0%" data-apa-twocolumn="true">
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>This is the cancellation of <a href="#fig-motivation" class="quarto-xref" aria-expanded="false">Figure&nbsp;1</a>, arriving in real clinical data: two components move in opposite directions, the mean records their sum, and a difference score computed from means is therefore blind to both. No amount of statistical power on the switch cost would have recovered this, because the switch cost is not where the effect is.</p>
</div>
<p>Three caveats bound what this shows. The decision and non-decision parameters trade off in the posterior (<span class="math inline">r = -0.44</span>), the same weak identification that limited the shifted Wald above, so the split between them is less certain than either interval taken alone; what is robust is that a group difference exists in the shape of the distributions and not in their means. The screen of summary statistics reported above is uncorrected, which makes the conventional analysis look, if anything, better than it is. And this is one task in one sample, analysed post hoc: it is a demonstration that the question becomes askable, not a claim about the neuropsychology of ADHD. The substantive point is the one the conventional analysis could not reach — that a task widely read as showing no deficit does distinguish the groups, once the analysis is allowed to say something other than a difference in means.</p>
<p>The two halves of this example are also two halves of one clinical argument. A group difference in a parameter, as here, is a statement about a population; using that parameter as a patient’s score requires the check of the previous section, run on the same fit. Both come out of one model, and neither requires the analyst to leave the regression they started from.</p>
</section>
</section>
</section>
<section id="example-3-the-same-interface-for-subjective-ratings" class="level1">
<h1>Example 3: The Same Interface for Subjective Ratings</h1>
<!-- NOTE FOR FUTURE EDITS: the CHOCO (Choice-Confidence) family is
     deliberately NOT *discussed* in this paper - it is the subject of a
     separate paper of its own. Do not re-introduce it in the prose, in the
     abstract, or in any caption.

     It does appear in @fig-overview, and that is intentional: the figure is
     an inventory of what the package ships, and omitting a shipped family
     from an inventory would be misleading. See the matching note in
     man/figures/make_fig_overview.py, which owns that figure. Inventory
     yes, prose no. -->
<p>Cognitive modelling is usually discussed in terms of RTs, but nothing in the interface is specific to them, and the two rating quadrants of <a href="#fig-overview" class="quarto-xref" aria-expanded="false">Figure&nbsp;3</a> are written for response formats psychology collects at least as often. Analog (slider) scales are bounded, and responses pile up at the endpoints, because answering “completely agree” is a different kind of act from answering “agree quite a lot”. A mean rating cannot tell the two apart.</p>
<p><code>cogmod_betagate()</code> is <code>cogmod</code>’s reparameterization of the ordered Beta model <span class="citation" data-cites="kubinec2023ordered">(<a href="#ref-kubinec2023ordered" role="doc-biblioref">Kubinec, 2023</a>)</span>, in which an observed 0 or 1 arises when an underlying continuous tendency passes a lower or upper “gate”. Its four parameters are separately interpretable: <code>mu</code> is that underlying tendency, <code>phi</code> the consistency of the non-extreme responses, <code>pex</code> the overall probability of an extreme response, and <code>bex</code> the direction of the extremity. As in every other family, each takes its own formula:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">bf</span>(score <span class="sc">~</span> Condition,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>        phi <span class="sc">~</span> Condition,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>        pex <span class="sc">~</span> Condition,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        bex <span class="sc">~</span> Condition,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">family =</span> <span class="fu">cogmod_betagate</span>())</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">brm</span>(f, <span class="at">data =</span> df, <span class="at">stanvars =</span> <span class="fu">cogmod_betagate_stanvars</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>We simulated 1,000 ratings (<code>rcogmod_betagate()</code>) from two conditions in which the manipulation raised both the underlying tendency and the inclination to answer at the top of the scale. The mean rating rises from 0.57 to 0.83, and a <em>t</em>-test duly returns one number (<span class="math inline">t = 17.5</span>, <span class="math inline">p &lt; .001</span>). <a href="#tbl-betagate" class="quarto-xref" aria-expanded="false">Table&nbsp;4</a> shows what the four parameters return instead. The underlying tendency does rise, but so does extreme responding, from 10% to 36% of trials, and those extremes shift towards the upper end — nearly half of the condition B responses sit exactly at the ceiling. Consistency is correctly reported as unchanged, a useful negative control. All four parameters recover their generating values.</p>
<div id="tbl-betagate" class="quarto-float quarto-figure quarto-figure-center FigureWithoutNote" data-tblnum="4" prefix="" data-custom-style="FigureWithoutNote">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-betagate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="FigureTitle" data-custom-style="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption" data-custom-style="Caption">
<p>Beta-Gate parameters for 1,000 simulated ratings; posterior means with 95% credible intervals on the response scale, against the values used to generate the data.</p>
</div>
</figcaption>
<div aria-describedby="tbl-betagate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="tbl-betagate" class="caption-top table" prefix="" data-tblnum="4">
<colgroup>
<col style="width: 19%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Condition A</th>
<th style="text-align: right;">Condition B</th>
<th style="text-align: right;">Generating values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>mu</code> — underlying tendency</td>
<td style="text-align: right;">0.56 [0.55, 0.58]</td>
<td style="text-align: right;">0.71 [0.69, 0.74]</td>
<td style="text-align: right;">0.55 → 0.70</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>phi</code> — consistency</td>
<td style="text-align: right;">3.29 [2.92, 3.68]</td>
<td style="text-align: right;">2.82 [2.36, 3.32]</td>
<td style="text-align: right;">3.00 → 3.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pex</code> — extreme responding</td>
<td style="text-align: right;">0.10 [0.07, 0.13]</td>
<td style="text-align: right;">0.36 [0.31, 0.40]</td>
<td style="text-align: right;">0.10 → 0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>bex</code> — direction of extremes</td>
<td style="text-align: right;">0.55 [0.41, 0.69]</td>
<td style="text-align: right;">0.79 [0.69, 0.87]</td>
<td style="text-align: right;">0.50 → 0.80</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="AfterWithoutNote" data-custom-style="AfterWithoutNote">
<p>Beta-Gate is one of several ways to give a bounded response its point masses — the zero-one inflated Beta and the extended-support Beta <span class="citation" data-cites="kosmidis2024extended">(<a href="#ref-kosmidis2024extended" role="doc-biblioref">Kosmidis &amp; Zeileis, 2024</a>)</span> are others, and each attributes the endpoints to a different mechanism. Choosing between them is the same problem as choosing an RT family, and it is solved the same way: <code>loo_compare()</code> and <code>modelbased::estimate_prediction()</code> behave here exactly as they did for the accumulator models of Example 1, and the package’s <em>Subjective Ratings</em> vignette runs the comparison.</p>
</div>
<p>The simulation is not the point; the arrangement is. A response format that ordinarily calls for its own specialised package is here one more <code>family</code> argument, carrying the same formula syntax, the same diagnostics and the same post-processing as the diffusion model in Example 1.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="summary" class="level2">
<h2 data-anchor-id="summary">Summary</h2>
<p><code>cogmod</code> implements Bayesian cognitive models as <code>brms</code> custom families: descriptive RT distributions, evidence accumulation models, and process models for bounded and Likert-type ratings. The design commitment is minimal. The package supplies likelihoods and the post-processing methods that make them first-class citizens of the <code>brms</code> ecosystem, and inherits the rest. The particular families it ships today matter less than the arrangement, which is built so that the set can grow without any of the surrounding workflow changing. The three examples show what this buys. Five accumulator architectures fitted to the same choices and RTs are compared in one call, and the simplest of them is not merely ranked but diagnosed: a predictive check names the missing parameter, and freeing it is one line (Example 1). Dropping the choice, sixteen RT families are compared just as cheaply; because every parameter of the chosen one can carry random effects, the reliability of each as an individual-level score becomes a routine check, and in clinical data the same decomposition recovers a group difference that the task’s conventional index, and every other summary statistic we computed, entirely misses (Example 2). The same interface then reaches outcomes the RT literature does not usually address, such as bounded ratings (Example 3).</p>
<p>What the three have in common is that <strong>what you fit is what you get</strong>. A likelihood is not only a claim about the shape of the data; it fixes the vocabulary in which any result can be stated. A Gaussian model can report that two conditions differ by 141 ms and nothing else, because a mean difference is the only quantity it owns. An ex-Gaussian attributes that difference to the bulk or to the tail, a diffusion model to evidence, threshold or encoding, and Beta-Gate separates how highly a participant rates something from how readily they answer at the ends of the scale. Fit and interpretability usually improve together along this sequence, though <a href="#tbl-loo" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a> is a reminder that they need not: the shifted Wald is outpredicted by six descriptive families whose parameters mean nothing in particular, and the ex-Gaussian, whose decomposition earns its keep in the same example, is outpredicted by seven. Choosing a likelihood is choosing which questions can be asked at all, and the choice deserves to be made rather than inherited.</p>
</section>
<section id="computational-neuropsychology" class="level2">
<h2 data-anchor-id="computational-neuropsychology">Computational neuropsychology</h2>
<p>That argument bites hardest in neuropsychological assessment. A neuropsychological test is a cognitive task, so everything above applies to it directly, with higher stakes attached. The quantity a clinician reports — a completion time, a total score, an interference effect — is exactly the aggregate that the opening example shows to be several things at once, and a patient’s deviation from a normative sample is therefore a deviation on an index corresponding to no single mechanism. Model parameters turn “impaired on the Stroop” into a claim about which component is impaired, and two patients with the same score but opposite parameter profiles stop being indistinguishable <span class="citation" data-cites="ratcliff2022neuropsychological steinke2020computational">(<a href="#ref-ratcliff2022neuropsychological" role="doc-biblioref">Ratcliff &amp; McKoon, 2022</a>; <a href="#ref-steinke2020computational" role="doc-biblioref">Steinke &amp; Kopp, 2020</a>)</span>. Ageing shows what this changes in practice <span class="citation" data-cites="theisen2021age">(<a href="#ref-theisen2021age" role="doc-biblioref">Theisen et al., 2021</a>)</span>, and the clinical reanalysis of Example 2 shows the sharper version of the same point: a conventional index can report no group difference at all while two components underneath it differ substantially, because the index is their sum. The logic covers any group whose deficit could be caution, encoding, motor execution or evidence quality.</p>
<p>The reliability check that precedes it supplies the rest of the argument. A parameter is usable as a clinical score only if it separates people by more than it is uncertain about each of them, and this framework makes that checkable for every parameter rather than assumed for whichever one the test happens to report. It also makes visible that the best individual-level quantity a task yields is often not a condition contrast, but a person’s overall speed, dispersion or non-decision time — quantities the experimental tradition subtracts away as nuisance and a clinical tradition has no reason to.</p>
<p>The same reparameterization helps on the neural side. Correlating brain measures with mean RT or accuracy asks the brain to explain a quantity that mixes mechanisms; correlating them with drift rate, threshold or non-decision time asks it to explain one at a time, which is why parameters have proven the more tractable targets in model-based cognitive neuroscience <span class="citation" data-cites="forstmann2016sequential wiecki2015modelbased">(<a href="#ref-forstmann2016sequential" role="doc-biblioref">Forstmann et al., 2016</a>; <a href="#ref-wiecki2015modelbased" role="doc-biblioref">Wiecki et al., 2015</a>)</span>. <code>cogmod</code> does not replace the joint approaches that estimate behavioural and neural parameters together, but it lowers the cost of the two-stage version. Clinical datasets arrive with covariates (age, education, group, medication) and unbalanced trial counts; here both are handled by the formula syntax used for everything else, and participant-level estimates come out of <code>estimate_grouplevel()</code> ready to be correlated with imaging or clinical measures. The obstacle to a computational neuropsychology was never the argument, which has been on record for two decades. It was that the modelling stayed expensive enough to remain a research activity rather than an analysis step.</p>
</section>
<section id="limitations" class="level2">
<h2 data-anchor-id="limitations">Limitations</h2>
<p><strong>Computational cost.</strong> General-purpose HMC on custom Stan code is slower than a sampler built for a specific model class. <a href="#tbl-eam" class="quarto-xref" aria-expanded="false">Table&nbsp;1</a> and <a href="#tbl-loo" class="quarto-xref" aria-expanded="false">Table&nbsp;2</a> make this concrete: the LBA took between 6 and 10 minutes per chain on datasets of two to four thousand trials without random effects, and hierarchical versions cost substantially more. Users whose primary question concerns the fine structure of the decision process, or who must fit many participants with complex accumulator architectures, are better served by EMC2 <span class="citation" data-cites="stevenson2026bayesian">(<a href="#ref-stevenson2026bayesian" role="doc-biblioref">Stevenson et al., 2026</a>)</span> or HSSM <span class="citation" data-cites="fengler2026hssm">(<a href="#ref-fengler2026hssm" role="doc-biblioref">Fengler et al., 2026</a>)</span>.</p>
<p><strong>Identifiability.</strong> The flexibility of the interface makes it easy to write down models the data cannot support. Regressing every parameter of an LBA on every condition is one line of code and usually a bad idea: evidence accumulation parameters trade off against each other, and between-trial variability parameters are notoriously poorly identified <span class="citation" data-cites="boehm2018estimating evans2020evidence">(<a href="#ref-boehm2018estimating" role="doc-biblioref">Boehm et al., 2018</a>; <a href="#ref-evans2020evidence" role="doc-biblioref">Evans &amp; Wagenmakers, 2020</a>)</span>. The package does not, and cannot, prevent this. Prior predictive checks, parameter recovery on simulated data and the standard Bayesian workflow <span class="citation" data-cites="gelman2020bayesian">(<a href="#ref-gelman2020bayesian" role="doc-biblioref">Gelman et al., 2020</a>)</span> remain the user’s responsibility; the <code>d*()</code> and <code>r*()</code> functions provided for every family - and the <code>p*()</code> cumulative distribution functions available for the diffusion, racing diffusion and Wald families - exist to make those checks cheap.</p>
<p><strong>Maturity.</strong> The package is under active development, and the set of families reported here is a snapshot rather than a specification. Parameterizations may still change, and have: <code>ndt</code> was until recently a fraction of a user-supplied minimum RT rather than a quantity in seconds, and the ex-Gaussian’s <code>mu</code> was constrained positive. The package website and <code>NEWS.md</code> track the current state, and record what to change in existing code. Several descriptive RT families have little precedent in this literature, and while Example 2 suggests they deserve attention, their behaviour is correspondingly less well documented than the ex-Gaussian’s or the shifted LogNormal’s.</p>
<p><strong>Scope.</strong> <code>cogmod</code> currently covers single-stage decisions and rating responses. Reinforcement learning models, sequential-sampling models with more than two accumulators, collapsing boundaries and joint modelling of behaviour with neural measures are not yet available; some are planned, and some are poorly suited to the custom-family mechanism and may never be.</p>
<p><strong>Analytically tractable likelihoods only.</strong> That last point is the sharpest boundary on what <code>cogmod</code> can become, and it follows directly from the design. A <code>brms</code> custom family is a Stan model, so every family shipped here needs a likelihood that can be written down in closed form and evaluated cheaply enough for HMC. Several of the models a user might reasonably want next do not have one: the leaky competing accumulator <span class="citation" data-cites="usher2001time">(<a href="#ref-usher2001time" role="doc-biblioref">Usher &amp; McClelland, 2001</a>)</span>, diffusion processes with collapsing boundaries or time-varying drift <span class="citation" data-cites="hawkins2015revisiting">(<a href="#ref-hawkins2015revisiting" role="doc-biblioref">Hawkins et al., 2015</a>)</span>, and richer racing architectures are defined by a generative simulation rather than by a density, and where a density does exist it often requires numerical integration, which gradient-based sampling tolerates poorly. The general remedy is to stop requiring the likelihood. Simulation-based inference <span class="citation" data-cites="cranmer2020frontier">(<a href="#ref-cranmer2020frontier" role="doc-biblioref">Cranmer et al., 2020</a>)</span> trains a neural network on data simulated from the model, either to approximate the likelihood — the route taken by the likelihood approximation networks that make otherwise intractable variants estimable in HSSM <span class="citation" data-cites="fengler2021likelihood fengler2026hssm">(<a href="#ref-fengler2021likelihood" role="doc-biblioref">Fengler et al., 2021</a>, <a href="#ref-fengler2026hssm" role="doc-biblioref">2026</a>)</span> — or to amortize the posterior directly, as in BayesFlow <span class="citation" data-cites="radev2020bayesflow radev2023bayesflow">(<a href="#ref-radev2020bayesflow" role="doc-biblioref">Radev et al., 2020</a>, <a href="#ref-radev2023bayesflow" role="doc-biblioref">2023</a>)</span>. That literature is moving quickly and <code>cogmod</code> follows it closely; whether such approximations can be exposed behind the same formula interface, so that a simulation-defined model is specified, sampled and post-processed like any other family, is an open question and the direction in which we hope to extend the package.</p>
</section>
<section id="conclusion" class="level2">
<h2 data-anchor-id="conclusion">Conclusion</h2>
<p>The gap between what cognitive data contain and what is extracted from them is large, and it is maintained by friction rather than by disagreement. Few researchers would defend a mean difference as an adequate summary of a reaction time distribution, yet many report one, because the alternative has meant learning a new toolchain for every model worth trying. By implementing cognitive models as families within a regression framework psychologists already use, <code>cogmod</code> aims to make the better analysis the easier one; by putting descriptive and generative models under one interface, it aims to make the choice between them an empirical question rather than an inherited convention.</p>
</section>
</section>
<section id="open-practices-statement" class="level1">
<h1>Open Practices Statement</h1>
<p><code>cogmod</code> is open source (MIT licence) and available at <a href="https://github.com/DominiqueMakowski/cogmod" class="uri">https://github.com/DominiqueMakowski/cogmod</a>, with documentation at <a href="https://dominiquemakowski.github.io/cogmod/" class="uri">https://dominiquemakowski.github.io/cogmod/</a>. The lexical decision data of <span class="citation" data-cites="wagenmakers2008diffusion">Wagenmakers et al. (<a href="#ref-wagenmakers2008diffusion" role="doc-biblioref">2008</a>)</span> are not redistributed with the package; they are read from the <code>rtdists</code> package, where they appear as <code>speed_acc</code> courtesy of the original authors, and the subset used here is reconstructed by <code>paper/wagenmakers.R</code> in the repository. The simulated data used in the Introduction are bundled as <code>badlm</code> (with their generating script in <code>data-raw/</code>). The clinical data of Example 2 are not redistributed; they are downloaded from OpenNeuro (<code>ds000030</code>) by <code>paper/download_cnp.R</code> in the same repository, and <code>paper/example_cnp.R</code> performs the trial-level extraction described above. All models reported here, the scripts used to fit them, and the code reproducing every figure and table are available in that repository; the two model-comparison tables are regenerated by <code>paper/make_tables.R</code> from the fits the package vignettes own, so the paper and the documentation cannot report different numbers for the same model. None of the analyses were preregistered; the Introduction, Example 3 and the reliability section of Example 2 use simulated data, while Example 1 and the rest of Example 2 reanalyse previously published data.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-balota2011moving" class="csl-entry" role="listitem">
Balota, D. A., &amp; Yap, M. J. (2011). Moving beyond the mean in studies of mental chronometry: The power of response time distributional analyses. <em>Current Directions in Psychological Science</em>, <em>20</em>(3), 160–166. <a href="https://doi.org/10.1177/0963721411408885">https://doi.org/10.1177/0963721411408885</a>
</div>
<div id="ref-boehm2018estimating" class="csl-entry" role="listitem">
Boehm, U., Annis, J., Frank, M. J., Hawkins, G. E., Heathcote, A., Kellen, D., Krypotos, A.-M., Lerche, V., Logan, G. D., Palmeri, T. J., et al. (2018). Estimating across-trial variability parameters of the diffusion decision model: Expert advice and recommendations. <em>Journal of Mathematical Psychology</em>, <em>87</em>, 46–75. <a href="https://doi.org/10.1016/j.jmp.2018.09.004">https://doi.org/10.1016/j.jmp.2018.09.004</a>
</div>
<div id="ref-brown2008simplest" class="csl-entry" role="listitem">
Brown, S. D., &amp; Heathcote, A. (2008). The simplest complete model of choice response time: Linear ballistic accumulation. <em>Cognitive Psychology</em>, <em>57</em>(3), 153–178. <a href="https://doi.org/10.1016/j.cogpsych.2007.12.002">https://doi.org/10.1016/j.cogpsych.2007.12.002</a>
</div>
<div id="ref-burkner2017brms" class="csl-entry" role="listitem">
Bürkner, P.-C. (2017). <span class="nocase">brms</span>: An <span>R</span> package for <span>Bayesian</span> multilevel models using <span>Stan</span>. <em>Journal of Statistical Software</em>, <em>80</em>(1), 1–28. <a href="https://doi.org/10.18637/jss.v080.i01">https://doi.org/10.18637/jss.v080.i01</a>
</div>
<div id="ref-burkner2018advanced" class="csl-entry" role="listitem">
Bürkner, P.-C. (2018). Advanced <span>Bayesian</span> multilevel modeling with the <span>R</span> package <span class="nocase">brms</span>. <em>The R Journal</em>, <em>10</em>(1), 395–411. <a href="https://doi.org/10.32614/RJ-2018-017">https://doi.org/10.32614/RJ-2018-017</a>
</div>
<div id="ref-carpenter2017stan" class="csl-entry" role="listitem">
Carpenter, B., Gelman, A., Hoffman, M. D., Lee, D., Goodrich, B., Betancourt, M., Brubaker, M., Guo, J., Li, P., &amp; Riddell, A. (2017). <span>Stan</span>: A probabilistic programming language. <em>Journal of Statistical Software</em>, <em>76</em>(1), 1–32. <a href="https://doi.org/10.18637/jss.v076.i01">https://doi.org/10.18637/jss.v076.i01</a>
</div>
<div id="ref-carpenter1995neural" class="csl-entry" role="listitem">
Carpenter, R. H. S., &amp; Williams, M. L. L. (1995). Neural computation of log likelihood in control of saccadic eye movements. <em>Nature</em>, <em>377</em>(6544), 59–62. <a href="https://doi.org/10.1038/377059a0">https://doi.org/10.1038/377059a0</a>
</div>
<div id="ref-cranmer2020frontier" class="csl-entry" role="listitem">
Cranmer, K., Brehmer, J., &amp; Louppe, G. (2020). The frontier of simulation-based inference. <em>Proceedings of the National Academy of Sciences</em>, <em>117</em>(48), 30055–30062. <a href="https://doi.org/10.1073/pnas.1912789117">https://doi.org/10.1073/pnas.1912789117</a>
</div>
<div id="ref-deboeck2019overview" class="csl-entry" role="listitem">
De Boeck, P., &amp; Jeon, M. (2019). An overview of models for response times and processes in cognitive tests. <em>Frontiers in Psychology</em>, <em>10</em>, 102. <a href="https://doi.org/10.3389/fpsyg.2019.00102">https://doi.org/10.3389/fpsyg.2019.00102</a>
</div>
<div id="ref-elliott2020test" class="csl-entry" role="listitem">
Elliott, M. L., Knodt, A. R., Ireland, D., Morris, M. L., Poulton, R., Ramrakha, S., Sison, M. L., Moffitt, T. E., Caspi, A., &amp; Hariri, A. R. (2020). What is the test-retest reliability of common task-functional <span>MRI</span> measures? <span>New</span> empirical evidence and a meta-analysis. <em>Psychological Science</em>, <em>31</em>(7), 792–806. <a href="https://doi.org/10.1177/0956797620916786">https://doi.org/10.1177/0956797620916786</a>
</div>
<div id="ref-evans2020evidence" class="csl-entry" role="listitem">
Evans, N. J., &amp; Wagenmakers, E.-J. (2020). Evidence accumulation models: Current limitations and future directions. <em>The Quantitative Methods for Psychology</em>, <em>16</em>(2), 73–90. <a href="https://doi.org/10.20982/tqmp.16.2.p073">https://doi.org/10.20982/tqmp.16.2.p073</a>
</div>
<div id="ref-fengler2021likelihood" class="csl-entry" role="listitem">
Fengler, A., Govindarajan, L. N., Chen, T., &amp; Frank, M. J. (2021). Likelihood approximation networks (<span>LANs</span>) for fast inference of simulation models in cognitive neuroscience. <em>eLife</em>, <em>10</em>, e65074. <a href="https://doi.org/10.7554/eLife.65074">https://doi.org/10.7554/eLife.65074</a>
</div>
<div id="ref-fengler2026hssm" class="csl-entry" role="listitem">
Fengler, A., Xu, P., Bera, K., Paniagua, C., Omar, A., &amp; Frank, M. J. (2026). <span>HSSM</span>: A widely applicable toolbox for hierarchical <span>Bayesian</span> neurocognitive modeling. <em>bioRxiv</em>. <a href="https://doi.org/10.1101/2026.06.05.730398">https://doi.org/10.1101/2026.06.05.730398</a>
</div>
<div id="ref-fisher2024sequential" class="csl-entry" role="listitem">
Fisher, C. R., &amp; Makowski, D. (2024). <span class="nocase">SequentialSamplingModels.jl</span>: A julia package for simulating and evaluating sequential sampling models. <em>Proceedings of the JuliaCon Conferences</em>. <a href="https://doi.org/10.21105/jcon.00186">https://doi.org/10.21105/jcon.00186</a>
</div>
<div id="ref-forstmann2008striatum" class="csl-entry" role="listitem">
Forstmann, B. U., Dutilh, G., Brown, S., Neumann, J., von Cramon, D. Y., Ridderinkhof, K. R., &amp; Wagenmakers, E.-J. (2008). Striatum and pre-<span>SMA</span> facilitate decision-making under time pressure. <em>Proceedings of the National Academy of Sciences</em>, <em>105</em>(45), 17538–17542. <a href="https://doi.org/10.1073/pnas.0805903105">https://doi.org/10.1073/pnas.0805903105</a>
</div>
<div id="ref-forstmann2016sequential" class="csl-entry" role="listitem">
Forstmann, B. U., Ratcliff, R., &amp; Wagenmakers, E.-J. (2016). Sequential sampling models in cognitive neuroscience: Advantages, applications, and extensions. <em>Annual Review of Psychology</em>, <em>67</em>, 641–666. <a href="https://doi.org/10.1146/annurev-psych-122414-033645">https://doi.org/10.1146/annurev-psych-122414-033645</a>
</div>
<div id="ref-gelman2020bayesian" class="csl-entry" role="listitem">
Gelman, A., Vehtari, A., Simpson, D., Margossian, C. C., Carpenter, B., Yao, Y., Kennedy, L., Gabry, J., Bürkner, P.-C., &amp; Modrák, M. (2020). Bayesian workflow. <em>arXiv Preprint</em>, <em>arXiv:2011.01808</em>. <a href="https://doi.org/10.48550/arXiv.2011.01808">https://doi.org/10.48550/arXiv.2011.01808</a>
</div>
<div id="ref-haines2020learning" class="csl-entry" role="listitem">
Haines, N., Kvam, P. D., Irving, L. H., Smith, C., Beauchaine, T. P., Pitt, M. A., Ahn, W.-Y., &amp; Turner, B. M. (2020). <em>Theoretically informed generative models can advance the psychological and brain sciences: Lessons from the reliability paradox</em>. PsyArXiv. <a href="https://doi.org/10.31234/osf.io/xr7y3">https://doi.org/10.31234/osf.io/xr7y3</a>
</div>
<div id="ref-hawkins2015revisiting" class="csl-entry" role="listitem">
Hawkins, G. E., Forstmann, B. U., Wagenmakers, E.-J., Ratcliff, R., &amp; Brown, S. D. (2015). Revisiting the evidence for collapsing boundaries and urgency signals in perceptual decision-making. <em>Journal of Neuroscience</em>, <em>35</em>(6), 2476–2484. <a href="https://doi.org/10.1523/JNEUROSCI.2410-14.2015">https://doi.org/10.1523/JNEUROSCI.2410-14.2015</a>
</div>
<div id="ref-heathcote2019dynamic" class="csl-entry" role="listitem">
Heathcote, A., Lin, Y.-S., Reynolds, A., Strickland, L., Gretton, M., &amp; Matzke, D. (2019). Dynamic models of choice. <em>Behavior Research Methods</em>, <em>51</em>(2), 961–985. <a href="https://doi.org/10.3758/s13428-018-1067-y">https://doi.org/10.3758/s13428-018-1067-y</a>
</div>
<div id="ref-hedge2018reliability" class="csl-entry" role="listitem">
Hedge, C., Powell, G., &amp; Sumner, P. (2018). The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences. <em>Behavior Research Methods</em>, <em>50</em>(3), 1166–1186. <a href="https://doi.org/10.3758/s13428-017-0935-1">https://doi.org/10.3758/s13428-017-0935-1</a>
</div>
<div id="ref-kosmidis2024extended" class="csl-entry" role="listitem">
Kosmidis, I., &amp; Zeileis, A. (2024). Extended-support beta regression for <span class="math inline">[0, 1]</span> responses. <em>arXiv Preprint</em>, <em>arXiv:2409.07233</em>. <a href="https://doi.org/10.48550/arXiv.2409.07233">https://doi.org/10.48550/arXiv.2409.07233</a>
</div>
<div id="ref-kubinec2023ordered" class="csl-entry" role="listitem">
Kubinec, R. (2023). Ordered beta regression: A parsimonious, well-fitting model for continuous data with lower and upper bounds. <em>Political Analysis</em>, <em>31</em>(4), 519–536. <a href="https://doi.org/10.1017/pan.2022.20">https://doi.org/10.1017/pan.2022.20</a>
</div>
<div id="ref-kubinec2025ordbetareg" class="csl-entry" role="listitem">
Kubinec, R. (2025). <em>Ordbetareg: Ordered beta regression models with ’brms’</em>. <a href="https://doi.org/10.32614/CRAN.package.ordbetareg">https://doi.org/10.32614/CRAN.package.ordbetareg</a>
</div>
<div id="ref-ludecke2021performance" class="csl-entry" role="listitem">
Lüdecke, D., Ben-Shachar, M. S., Patil, I., Waggoner, P., &amp; Makowski, D. (2021). <span class="nocase">performance</span>: An <span>R</span> package for assessment, comparison and testing of statistical models. <em>Journal of Open Source Software</em>, <em>6</em>(60), 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>
</div>
<div id="ref-ludecke2019insight" class="csl-entry" role="listitem">
Lüdecke, D., Waggoner, P., &amp; Makowski, D. (2019). <span class="nocase">insight</span>: A unified interface to access information from model objects in <span>R</span>. <em>Journal of Open Source Software</em>, <em>4</em>(38), 1412. <a href="https://doi.org/10.21105/joss.01412">https://doi.org/10.21105/joss.01412</a>
</div>
<div id="ref-makowski2019bayestestr" class="csl-entry" role="listitem">
Makowski, D., Ben-Shachar, M. S., &amp; Lüdecke, D. (2019). <span class="nocase">bayestestR</span>: Describing effects and their uncertainty, existence and significance within the <span>Bayesian</span> framework. <em>Journal of Open Source Software</em>, <em>4</em>(40), 1541. <a href="https://doi.org/10.21105/joss.01541">https://doi.org/10.21105/joss.01541</a>
</div>
<div id="ref-makowski2020modelbased" class="csl-entry" role="listitem">
Makowski, D., Ben-Shachar, M. S., Patil, I., &amp; Lüdecke, D. (2020). <em><span class="nocase">modelbased</span>: Estimation of model-based predictions, contrasts and means</em>. <a href="https://easystats.github.io/modelbased/">https://easystats.github.io/modelbased/</a>
</div>
<div id="ref-marek2022reproducible" class="csl-entry" role="listitem">
Marek, S., Tervo-Clemmens, B., Calabro, F. J., Montez, D. F., Kay, B. P., Hatoum, A. S., Donohue, M. R., Foran, W., Miller, R. L., Hendrickson, T. J., et al. (2022). Reproducible brain-wide association studies require thousands of individuals. <em>Nature</em>, <em>603</em>(7902), 654–660. <a href="https://doi.org/10.1038/s41586-022-04492-9">https://doi.org/10.1038/s41586-022-04492-9</a>
</div>
<div id="ref-matzke2009psychological" class="csl-entry" role="listitem">
Matzke, D., &amp; Wagenmakers, E.-J. (2009). Psychological interpretation of the ex-<span>Gaussian</span> and shifted <span>Wald</span> parameters: A diffusion model analysis. <em>Psychonomic Bulletin &amp; Review</em>, <em>16</em>(5), 798–817. <a href="https://doi.org/10.3758/PBR.16.5.798">https://doi.org/10.3758/PBR.16.5.798</a>
</div>
<div id="ref-poldrack2016phenome" class="csl-entry" role="listitem">
Poldrack, R. A., Congdon, E., Triplett, W., Gorgolewski, K. J., Karlsgodt, K. H., Mumford, J. A., Sabb, F. W., Freimer, N. B., London, E. D., Cannon, T. D., &amp; Bilder, R. M. (2016). A phenome-wide examination of neural and cognitive function. <em>Scientific Data</em>, <em>3</em>, 160110. <a href="https://doi.org/10.1038/sdata.2016.110">https://doi.org/10.1038/sdata.2016.110</a>
</div>
<div id="ref-radev2020bayesflow" class="csl-entry" role="listitem">
Radev, S. T., Mertens, U. K., Voss, A., Ardizzone, L., &amp; Köthe, U. (2020). <span>BayesFlow</span>: Learning complex stochastic models with invertible neural networks. <em>IEEE Transactions on Neural Networks and Learning Systems</em>, <em>33</em>(4), 1452–1466. <a href="https://doi.org/10.1109/TNNLS.2020.3042395">https://doi.org/10.1109/TNNLS.2020.3042395</a>
</div>
<div id="ref-radev2023bayesflow" class="csl-entry" role="listitem">
Radev, S. T., Schmitt, M., Schumacher, L., Elsemüller, L., Pratz, V., Schälte, Y., Köthe, U., &amp; Bürkner, P.-C. (2023). <span>BayesFlow</span>: Amortized <span>Bayesian</span> workflows with neural networks. <em>Journal of Open Source Software</em>, <em>8</em>(89), 5702. <a href="https://doi.org/10.21105/joss.05702">https://doi.org/10.21105/joss.05702</a>
</div>
<div id="ref-ratcliff2008diffusion" class="csl-entry" role="listitem">
Ratcliff, R., &amp; McKoon, G. (2008). The diffusion decision model: Theory and data for two-choice decision tasks. <em>Neural Computation</em>, <em>20</em>(4), 873–922. <a href="https://doi.org/10.1162/neco.2008.12-06-420">https://doi.org/10.1162/neco.2008.12-06-420</a>
</div>
<div id="ref-ratcliff2022neuropsychological" class="csl-entry" role="listitem">
Ratcliff, R., &amp; McKoon, G. (2022). Can neuropsychological testing be improved with model-based approaches? <em>Trends in Cognitive Sciences</em>, <em>26</em>(11), 899–901. <a href="https://doi.org/10.1016/j.tics.2022.08.015">https://doi.org/10.1016/j.tics.2022.08.015</a>
</div>
<div id="ref-ratcliff2016diffusion" class="csl-entry" role="listitem">
Ratcliff, R., Smith, P. L., Brown, S. D., &amp; McKoon, G. (2016). Diffusion decision model: Current issues and history. <em>Trends in Cognitive Sciences</em>, <em>20</em>(4), 260–281. <a href="https://doi.org/10.1016/j.tics.2016.01.007">https://doi.org/10.1016/j.tics.2016.01.007</a>
</div>
<div id="ref-rouder2024signal" class="csl-entry" role="listitem">
Rouder, J. N., &amp; Mehrvarz, M. (2024). A psychometrics of individual differences in experimental tasks. <em>Current Directions in Psychological Science</em>. <a href="https://doi.org/10.1177/09637214231220923">https://doi.org/10.1177/09637214231220923</a>
</div>
<div id="ref-rouder2015lognormal" class="csl-entry" role="listitem">
Rouder, J. N., Province, J. M., Morey, R. D., Gomez, P., &amp; Heathcote, A. (2015). The lognormal race: A cognitive-process model of choice and latency with desirable psychometric properties. <em>Psychometrika</em>, <em>80</em>(2), 491–513. <a href="https://doi.org/10.1007/s11336-013-9396-3">https://doi.org/10.1007/s11336-013-9396-3</a>
</div>
<div id="ref-schwarz2001ex" class="csl-entry" role="listitem">
Schwarz, W. (2001). The ex-<span>Wald</span> distribution as a descriptive model of response times. <em>Behavior Research Methods, Instruments, &amp; Computers</em>, <em>33</em>(4), 457–469. <a href="https://doi.org/10.3758/bf03195403">https://doi.org/10.3758/bf03195403</a>
</div>
<div id="ref-shinn2020flexible" class="csl-entry" role="listitem">
Shinn, M., Lam, N. H., &amp; Murray, J. D. (2020). A flexible framework for simulating and fitting generalized drift-diffusion models. <em>eLife</em>, <em>9</em>, e56938. <a href="https://doi.org/10.7554/eLife.56938">https://doi.org/10.7554/eLife.56938</a>
</div>
<div id="ref-steinke2020computational" class="csl-entry" role="listitem">
Steinke, A., &amp; Kopp, B. (2020). Toward a computational neuropsychology of cognitive flexibility. <em>Brain Sciences</em>, <em>10</em>(12), 1000. <a href="https://doi.org/10.3390/brainsci10121000">https://doi.org/10.3390/brainsci10121000</a>
</div>
<div id="ref-stevenson2026bayesian" class="csl-entry" role="listitem">
Stevenson, N., Donzallaz, M. C., Innes, R. J., Forstmann, B. U., Matzke, D., &amp; Heathcote, A. (2026). Bayesian hierarchical cognitive modeling with the <span>EMC2</span> package. <em>Behavior Research Methods</em>. <a href="https://doi.org/10.3758/s13428-025-02869-y">https://doi.org/10.3758/s13428-025-02869-y</a>
</div>
<div id="ref-theisen2021age" class="csl-entry" role="listitem">
Theisen, M., Lerche, V., von Krause, M., &amp; Voss, A. (2021). Age differences in diffusion model parameters: A meta-analysis. <em>Psychological Research</em>, <em>85</em>(5), 2012–2021. <a href="https://doi.org/10.1007/s00426-020-01371-8">https://doi.org/10.1007/s00426-020-01371-8</a>
</div>
<div id="ref-tillman2020sequential" class="csl-entry" role="listitem">
Tillman, G., Van Zandt, T., &amp; Logan, G. D. (2020). Sequential sampling models without random between-trial variability: The racing diffusion model of speeded decision making. <em>Psychonomic Bulletin &amp; Review</em>, <em>27</em>(5), 911–936. <a href="https://doi.org/10.3758/s13423-020-01738-8">https://doi.org/10.3758/s13423-020-01738-8</a>
</div>
<div id="ref-usher2001time" class="csl-entry" role="listitem">
Usher, M., &amp; McClelland, J. L. (2001). The time course of perceptual choice: The leaky, competing accumulator model. <em>Psychological Review</em>, <em>108</em>(3), 550–592. <a href="https://doi.org/10.1037/0033-295X.108.3.550">https://doi.org/10.1037/0033-295X.108.3.550</a>
</div>
<div id="ref-vandekerckhove2008diffusion" class="csl-entry" role="listitem">
Vandekerckhove, J., &amp; Tuerlinckx, F. (2008). Diffusion model analysis with <span>MATLAB</span>: A <span>DMAT</span> primer. <em>Behavior Research Methods</em>, <em>40</em>(1), 61–72. <a href="https://doi.org/10.3758/BRM.40.1.61">https://doi.org/10.3758/BRM.40.1.61</a>
</div>
<div id="ref-vehtari2017practical" class="csl-entry" role="listitem">
Vehtari, A., Gelman, A., &amp; Gabry, J. (2017). Practical <span>Bayesian</span> model evaluation using leave-one-out cross-validation and <span>WAIC</span>. <em>Statistics and Computing</em>, <em>27</em>(5), 1413–1432. <a href="https://doi.org/10.1007/s11222-016-9696-4">https://doi.org/10.1007/s11222-016-9696-4</a>
</div>
<div id="ref-voss2007fastdm" class="csl-entry" role="listitem">
Voss, A., &amp; Voss, J. (2007). Fast-dm: A free program for efficient diffusion model analysis. <em>Behavior Research Methods</em>, <em>39</em>(4), 767–775. <a href="https://doi.org/10.3758/BF03192967">https://doi.org/10.3758/BF03192967</a>
</div>
<div id="ref-wagenmakers2008diffusion" class="csl-entry" role="listitem">
Wagenmakers, E.-J., Ratcliff, R., Gomez, P., &amp; McKoon, G. (2008). A diffusion model account of criterion shifts in the lexical decision task. <em>Journal of Memory and Language</em>, <em>58</em>(1), 140–159. <a href="https://doi.org/10.1016/j.jml.2007.04.006">https://doi.org/10.1016/j.jml.2007.04.006</a>
</div>
<div id="ref-wiecki2015modelbased" class="csl-entry" role="listitem">
Wiecki, T. V., Poland, J., &amp; Frank, M. J. (2015). Model-based cognitive neuroscience approaches to computational psychiatry: Clustering and classification. <em>Clinical Psychological Science</em>, <em>3</em>(3), 378–399. <a href="https://doi.org/10.1177/2167702614565359">https://doi.org/10.1177/2167702614565359</a>
</div>
<div id="ref-wiecki2013hddm" class="csl-entry" role="listitem">
Wiecki, T. V., Sofer, I., &amp; Frank, M. J. (2013). <span>HDDM</span>: Hierarchical <span>Bayesian</span> estimation of the drift-diffusion model in <span>Python</span>. <em>Frontiers in Neuroinformatics</em>, <em>7</em>, 14. <a href="https://doi.org/10.3389/fninf.2013.00014">https://doi.org/10.3389/fninf.2013.00014</a>
</div>
<div id="ref-williams2021beneath" class="csl-entry" role="listitem">
Williams, D. R., Mulder, J., Rouder, J. N., &amp; Rast, P. (2021). Beneath the surface: Unearthing within-person variability and mean relations with <span>Bayesian</span> mixed models. <em>Psychological Methods</em>, <em>26</em>(1), 74–95. <a href="https://doi.org/10.1037/met0000270">https://doi.org/10.1037/met0000270</a>
</div>
<div id="ref-wood2017generalized" class="csl-entry" role="listitem">
Wood, S. N. (2017). <em>Generalized additive models: An introduction with <span>R</span></em> (2nd ed.). Chapman; Hall/CRC. <a href="https://doi.org/10.1201/9781315370279">https://doi.org/10.1201/9781315370279</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>